// User-facing strings of the Text Advisor's pages (docs/plans/text-advisor/01-architecture.md
// § touch points: every advisor page string lives here so scripts/check_copy.mjs
// lints it). TA-C4 adds the upload page, TA-C3 the web chat; TA-W1 adds the site pages' copy.

/** The upload link page, dist/upload.html + dist/advisor/upload.js (03 § Uploads for compressed channels). */
export const UPLOAD_COPY = {
  heading: 'Send a photo or video',
  intro: 'Pick one file from your phone. It goes straight to SkipperCast, and you get a text back once it is in.',
  choose: 'Choose a file',
  send: 'Send it',
  sending: 'Sending…',
  progress: (percent: number): string => `Sent ${percent}%`,
  done: 'Got it. Watch your texts for the reply.',
  another: 'Send another',
  tooLarge: 'That file is over 300 MB. Send a shorter clip.',
  unsupported: 'That file type cannot be used. Send a JPEG, PNG, HEIC photo or an MP4 or MOV video.',
  expired: 'This link has expired. Text SkipperCast for a new one.',
  failed: 'The upload did not finish. Check your signal and try again.',
  noFile: 'Choose a file first.',
} as const;

/** Largest file the upload page accepts, in bytes (the server checks it again). */
export const UPLOAD_MAX_BYTES = 300 * 1024 * 1024;

/** The web chat island, web/advisor/chat.tsx on dist/chat.html (08 § Web chat; TA-C3). */
export const CHAT_COPY = {
  pageTitle: 'Text SkipperCast',
  pageIntro: 'Ask about the bite, the weather window or what you can keep. Or text the same questions from your phone.',
  open: 'Text SkipperCast',
  close: 'Close chat',
  panelLabel: 'Chat with SkipperCast',
  logLabel: 'Messages',
  heading: 'SkipperCast',
  greeting: 'Hi. Ask me where to fish, what the ocean is doing or what you can keep.',
  inputLabel: 'Message',
  placeholder: 'Type a message',
  send: 'Send',
  attach: 'Add a photo',
  attached: (name: string): string => `Photo ready: ${name}`,
  removePhoto: 'Remove photo',
  uploading: 'Adding the photo…',
  thinking: 'Thinking…',
  stillThinking: 'Still thinking. This one takes a moment.',
  pending: 'That is taking longer than usual. Ask again in a minute.',
  failed: 'The message did not go through. Check your connection and try again.',
  limited: 'Too many messages at once. Wait a minute, then try again.',
  photoTooLarge: 'That photo is over 8 MB. Pick a smaller one.',
  photoType: 'Send a photo: JPEG, PNG, HEIC, GIF or WebP.',
  photoFailed: 'The photo did not upload. Try again.',
  you: 'You',
  skippercast: 'SkipperCast',
  continueHeading: 'Continue by text',
  saveContact: 'Save the number',
  textUs: 'Text us',
} as const;

/** Largest photo the chat accepts, in bytes (the server checks it again). */
export const CHAT_MAX_PHOTO_BYTES = 8 * 1024 * 1024;
/** When the chat says "still thinking", and when it stops waiting (08: 40 s on the server). */
export const CHAT_STILL_THINKING_MS = 8000;
export const CHAT_TIMEOUT_MS = 45000;

// TA-W2: the admin app (dist/admin.html, web/admin/; 08 § Admin). English only; still under the copy lint.
/** The admin app's strings: shell, Queue and Health views. */
export const ADMIN_COPY = {
  pageTitle: 'SkipperCast admin',
  brand: 'SkipperCast admin',
  navLabel: 'Admin views',
  views: {queue: 'Queue', skippers: 'Skippers', rules: 'Rules', posts: 'Posts', funnel: 'Funnel', health: 'Health'},
  placeholder: (view: string): string => `The ${view} view arrives in a later step of the build plan.`,
  loading: 'Loading…',
  loadFailed: 'Could not load this view. Reload to try again.',
  signedOut: 'Sign in with an admin account to use this page.',
  relayDown: (since: string): string => `The Mac relay is down (last good ping ${since}). Texts are held for up to 6 hours.`,
  relayNever: 'never',
  // Queue
  queueHeading: 'Review queue',
  kindLabel: 'Kind',
  statusLabel: 'Status',
  allKinds: 'All kinds',
  kinds: {media: 'Photo', report: 'Report', post: 'Social draft', skipper: 'Skipper', conversation: 'Conversation', rule: 'Rule change'},
  statuses: {open: 'Open', approved: 'Approved', edited: 'Edited', rejected: 'Rejected', all: 'All'},
  empty: 'Nothing waiting. New items show up here as they arrive.',
  more: 'Load more',
  shortcuts: 'Keys on a focused item: a approves, r rejects, e edits.',
  opened: (when: string): string => `Opened ${when}`,
  reason: 'Reason',
  approve: 'Approve',
  verify: 'Verify',
  reject: 'Reject',
  edit: 'Edit',
  save: 'Save edit',
  cancel: 'Cancel',
  dismiss: 'Dismiss',
  done: 'Done',
  noteLabel: 'Note (optional)',
  decided: (status: string): string => `Marked ${status}.`,
  alreadyDecided: (status: string): string => `Already ${status}; nothing changed.`,
  decisionFailed: 'That did not save. Try again.',
  sentTexts: (n: number): string => (n === 1 ? 'One text sent.' : `${n} texts sent.`),
  heldTexts: 'Replies are switched off, so no text went out.',
  missing: 'The item this review points at no longer exists.',
  // Media
  photoAlt: 'The submitted photo',
  noPhoto: 'No stored image to show.',
  personBox: 'Person in photo',
  labels: 'Vision labels',
  credit: 'Credit',
  openOriginal: 'Open the original',
  publishState: 'Publish state',
  // Report
  boat: 'Boat',
  date: 'Date',
  trip: 'Trip',
  anglers: 'Anglers',
  notes: 'Notes',
  species: 'Species',
  kept: 'Kept',
  released: 'Released',
  version: (n: number): string => `Version ${n}`,
  unverifiedBoat: 'Unverified boat',
  // Skipper
  port: 'Port',
  landing: 'Landing',
  instagram: 'Instagram',
  booking: 'Booking',
  publicPhone: 'Public phone',
  channel: 'Channel',
  language: 'Language',
  firstMessages: 'First messages',
  consent: 'Photo consent',
  consentGiven: 'Given',
  consentNone: 'Not given',
  // Conversation
  lastMessages: 'Last messages',
  fromContact: 'Contact',
  fromAdvisor: 'SkipperCast',
  fromTeam: 'Team',
  replyLabel: 'Reply as team',
  sendReply: 'Send reply',
  // Rule and post
  rule: 'Rule',
  source: 'Source',
  reviewed: 'Reviewed',
  postLater: 'Social drafts are decided in the Posts view.',
  // Health
  healthHeading: 'Health',
  refresh: 'Refresh',
  checkedAt: (when: string): string => `Checked ${when}`,
  relay: 'Mac relay',
  relayState: 'State',
  relayUnknown: 'Never checked',
  relayUp: 'Up',
  relayDownWord: 'Down',
  lastOk: 'Last good ping',
  failures: 'Failed pings in a row',
  advisor: 'Advisor',
  enabled: 'On',
  disabled: 'Off',
  replies: 'Replies',
  outbound: 'Outbound channel',
  queue: 'Message queue',
  staleQueued: 'Queued over 2 minutes',
  oldestQueued: 'Oldest queued',
  heldOutbound: 'Held outbound',
  failedToday: 'Failed today',
  vision: 'Vision providers',
  providerUp: 'Available',
  providerDown: (until: string): string => `Skipped until ${until}`,
  caps: 'Caps today (UTC)',
  llmCalls: 'Model turns',
  visionCalls: 'Vision calls',
  mediaJobs: 'Media job',
  mediaPending: 'Images and graphics waiting',
  openReviews: 'Open reviews',
  meta: 'Instagram and Facebook',
  metaLater: 'Arrives with the social step',
} as const;

export type AdminView = keyof typeof ADMIN_COPY.views;
