// User-facing strings of the Text Advisor's pages (docs/plans/text-advisor/01-architecture.md
// § touch points: every advisor page string lives here so scripts/check_copy.mjs
// lints it). TA-C4 adds the upload page, TA-C3 the web chat; TA-W1 adds the site pages' copy.

/** The upload link page, dist/upload.html + dist/advisor/upload.js (03 § Uploads for compressed channels). */
export const UPLOAD_COPY = {
  heading: 'Send a photo or video',
  intro: 'Pick one file from your phone. It goes straight to SkipperCast, and you get a text back once it is in.',
  choose: 'Choose a file',
  send: 'Send it',
  sending: 'Sending…',
  progress: (percent: number): string => `Sent ${percent}%`,
  done: 'Got it. Watch your texts for the reply.',
  another: 'Send another',
  tooLarge: 'That file is over 300 MB. Send a shorter clip.',
  unsupported: 'That file type cannot be used. Send a JPEG, PNG, HEIC photo or an MP4 or MOV video.',
  expired: 'This link has expired. Text SkipperCast for a new one.',
  failed: 'The upload did not finish. Check your signal and try again.',
  noFile: 'Choose a file first.',
} as const;

/** Largest file the upload page accepts, in bytes (the server checks it again). */
export const UPLOAD_MAX_BYTES = 300 * 1024 * 1024;

/** The web chat island, web/advisor/chat.tsx on dist/chat.html (08 § Web chat; TA-C3). */
export const CHAT_COPY = {
  pageTitle: 'Text SkipperCast',
  pageIntro: 'Ask about the bite, the weather window or what you can keep. Or text the same questions from your phone.',
  open: 'Text SkipperCast',
  close: 'Close chat',
  panelLabel: 'Chat with SkipperCast',
  logLabel: 'Messages',
  heading: 'SkipperCast',
  greeting: 'Hi. Ask me where to fish, what the ocean is doing or what you can keep.',
  inputLabel: 'Message',
  placeholder: 'Type a message',
  send: 'Send',
  attach: 'Add a photo',
  attached: (name: string): string => `Photo ready: ${name}`,
  removePhoto: 'Remove photo',
  uploading: 'Adding the photo…',
  thinking: 'Thinking…',
  stillThinking: 'Still thinking. This one takes a moment.',
  pending: 'That is taking longer than usual. Ask again in a minute.',
  failed: 'The message did not go through. Check your connection and try again.',
  limited: 'Too many messages at once. Wait a minute, then try again.',
  photoTooLarge: 'That photo is over 8 MB. Pick a smaller one.',
  photoType: 'Send a photo: JPEG, PNG, HEIC, GIF or WebP.',
  photoFailed: 'The photo did not upload. Try again.',
  you: 'You',
  skippercast: 'SkipperCast',
  continueHeading: 'Continue by text',
  saveContact: 'Save the number',
  textUs: 'Text us',
} as const;

/** Largest photo the chat accepts, in bytes (the server checks it again). */
export const CHAT_MAX_PHOTO_BYTES = 8 * 1024 * 1024;
/** When the chat says "still thinking", and when it stops waiting (08: 40 s on the server). */
export const CHAT_STILL_THINKING_MS = 8000;
export const CHAT_TIMEOUT_MS = 45000;

// TA-W2: the admin app (dist/admin.html, web/admin/; 08 § Admin). English only; still under the copy lint.
/** The admin app's strings: shell, Queue and Health views. */
export const ADMIN_COPY = {
  pageTitle: 'SkipperCast admin',
  brand: 'SkipperCast admin',
  navLabel: 'Admin views',
  views: {queue: 'Queue', skippers: 'Skippers', rules: 'Rules', posts: 'Posts', funnel: 'Funnel', health: 'Health'},
  placeholder: (view: string): string => `The ${view} view arrives in a later step of the build plan.`,
  loading: 'Loading…',
  loadFailed: 'Could not load this view. Reload to try again.',
  signedOut: 'Sign in with an admin account to use this page.',
  relayDown: (since: string): string => `The Mac relay is down (last good ping ${since}). Texts are held for up to 6 hours.`,
  relayNever: 'never',
  // Queue
  queueHeading: 'Review queue',
  kindLabel: 'Kind',
  statusLabel: 'Status',
  allKinds: 'All kinds',
  kinds: {media: 'Photo', report: 'Report', post: 'Social draft', skipper: 'Skipper', conversation: 'Conversation', rule: 'Rule change'},
  statuses: {open: 'Open', approved: 'Approved', edited: 'Edited', rejected: 'Rejected', all: 'All'},
  empty: 'Nothing waiting. New items show up here as they arrive.',
  more: 'Load more',
  shortcuts: 'Keys on a focused item: a approves, r rejects, e edits.',
  opened: (when: string): string => `Opened ${when}`,
  reason: 'Reason',
  approve: 'Approve',
  verify: 'Verify',
  reject: 'Reject',
  edit: 'Edit',
  save: 'Save edit',
  cancel: 'Cancel',
  dismiss: 'Dismiss',
  done: 'Done',
  noteLabel: 'Note (optional)',
  decided: (status: string): string => `Marked ${status}.`,
  alreadyDecided: (status: string): string => `Already ${status}; nothing changed.`,
  decisionFailed: 'That did not save. Try again.',
  sentTexts: (n: number): string => (n === 1 ? 'One text sent.' : `${n} texts sent.`),
  heldTexts: 'Replies are switched off, so no text went out.',
  missing: 'The item this review points at no longer exists.',
  // Media
  photoAlt: 'The submitted photo',
  noPhoto: 'No stored image to show.',
  personBox: 'Person in photo',
  labels: 'Vision labels',
  credit: 'Credit',
  openOriginal: 'Open the original',
  publishState: 'Publish state',
  // Report
  boat: 'Boat',
  date: 'Date',
  trip: 'Trip',
  anglers: 'Anglers',
  notes: 'Notes',
  species: 'Species',
  kept: 'Kept',
  released: 'Released',
  version: (n: number): string => `Version ${n}`,
  unverifiedBoat: 'Unverified boat',
  // Skipper
  port: 'Port',
  landing: 'Landing',
  instagram: 'Instagram',
  booking: 'Booking',
  publicPhone: 'Public phone',
  channel: 'Channel',
  language: 'Language',
  firstMessages: 'First messages',
  consent: 'Photo consent',
  consentGiven: 'Given',
  consentNone: 'Not given',
  // Conversation
  lastMessages: 'Last messages',
  fromContact: 'Contact',
  fromAdvisor: 'SkipperCast',
  fromTeam: 'Team',
  replyLabel: 'Reply as team',
  sendReply: 'Send reply',
  // Rule and post
  rule: 'Rule',
  source: 'Source',
  reviewed: 'Reviewed',
  postLater: 'Social drafts are decided in the Posts view.',
  // Health
  healthHeading: 'Health',
  refresh: 'Refresh',
  checkedAt: (when: string): string => `Checked ${when}`,
  relay: 'Mac relay',
  relayState: 'State',
  relayUnknown: 'Never checked',
  relayUp: 'Up',
  relayDownWord: 'Down',
  lastOk: 'Last good ping',
  failures: 'Failed pings in a row',
  advisor: 'Advisor',
  enabled: 'On',
  disabled: 'Off',
  replies: 'Replies',
  outbound: 'Outbound channel',
  queue: 'Message queue',
  staleQueued: 'Queued over 2 minutes',
  oldestQueued: 'Oldest queued',
  heldOutbound: 'Held outbound',
  failedToday: 'Failed today',
  vision: 'Vision providers',
  providerUp: 'Available',
  providerDown: (until: string): string => `Skipped until ${until}`,
  caps: 'Caps today (UTC)',
  llmCalls: 'Model turns',
  visionCalls: 'Vision calls',
  mediaJobs: 'Media job',
  mediaPending: 'Images and graphics waiting',
  openReviews: 'Open reviews',
  meta: 'Instagram and Facebook',
  metaLater: 'Arrives with the social step',
} as const;

export type AdminView = keyof typeof ADMIN_COPY.views;

// ---- TA-W1: the public port, species and boat pages ------------------------------------
// (08 § Public pages; server/advisor/pages/*.ts render them on the server.) English and
// Spanish side by side; the pages pick one with ?lang=es or Accept-Language. The
// footer line is the short form of caveats C1 and C3 in docs/legal/disclaimers.md;
// the Spanish wording of both is a translation awaiting the owner's review.

export type PageLanguage = 'en' | 'es';
export type RuleState = 'open' | 'closed' | 'review' | 'unknown';

export interface PageCopy {
  home: string; ports: string; species: string; boats: string; breadcrumbs: string; skip: string; otherLanguage: string;
  openMap: string; terms: string; privacy: string; disclaimer: string; forecastNote: string;
  ctaHeading: string; ctaBody: string; ctaButton: string; ctaChat: string; ctaDefaultMessage: string; saveContact: string; qrAlt: string;
  notFoundTitle: string; notFoundBody: string;
  date: string; boat: string; trip: string; anglers: string; catch: string; port: string; kept: string; releasedHeader: string; reports: string;
  anotherBoat: string; edited: string; released: (n: number) => string; releasedOnly: (n: number, label: string) => string;
  trips: Record<string, string>;
  portTitle: (port: string) => string; portDescription: (port: string) => string; portRegion: (region: string) => string;
  portCtaMessage: (port: string) => string;
  todayHeading: string;
  reportsHeading: string; reportsNone: string; reportsUnverifiedNote: string;
  conditionsHeading: string; conditionsNone: string; seas: string; wind: string; ride: string;
  seasValue: (range: string, period: number | null) => string; windValue: (range: string, from: string | null) => string;
  comfort: Record<string, string>; rideValue: (word: string) => string;
  advisoriesHeading: string;
  boatsHeading: (port: string) => string; boatsNone: string;
  seasonsHeading: string; seasonsNote: string; ruleState: Record<RuleState, string>;
  speciesTitle: (name: string) => string; speciesDescription: (name: string) => string; speciesNames: (en: string, es: string) => string;
  idHeading: string; lookalikesHeading: string; idNone: string;
  rulesHeading: string; rulesNone: string; underReview: string; underReviewNote: string; groupRule: (label: string) => string; regionRule: (region: string) => string;
  minSize: string; maxSize: string; bag: string; season: string; depth: string; area: string; gear: string; source: string; reviewed: string;
  inches: (n: number) => string; feetMax: (n: number) => string; seasonRange: (open: string, close: string) => string;
  noTake: string; noSeasonDates: string; bagValue: (n: number) => string;
  catchesHeading: string; catchesNone: string; catchesNote: string;
  strategyHeading: string; strategyNone: string; strategyLanguageNote: string; rig: string; baitOrLure: string; where: string; when: string; howTo: string;
  sourcesHeading: string;
  boatTitle: (boat: string) => string; boatDescription: (boat: string, port: string) => string;
  verified: string; unverified: string; unverifiedNote: string; landing: (landing: string, port: string) => string;
  boatReportsHeading: string; boatReportsNone: string; photosHeading: string; photoAlt: (boat: string) => string; photoCredit: (credit: string) => string;
  bookHeading: string; bookingLink: string; call: (phone: string) => string; instagram: (handle: string) => string;
}

const PAGES_EN: PageCopy = {
  home: 'SkipperCast',
  ports: 'Ports',
  species: 'Species',
  boats: 'Boats',
  breadcrumbs: 'Breadcrumb',
  skip: 'Skip to the report',
  otherLanguage: 'En español',
  openMap: 'Open the map',
  terms: 'Terms',
  privacy: 'Privacy',
  disclaimer: 'Planning aid · not a navigation chart. Rules change. Verify with CDFW and NOAA before you fish.',
  forecastNote: 'Forecasts are estimates; conditions can differ. Check the NWS marine forecast.',
  ctaHeading: 'Get the report by text',
  ctaBody: 'Text SkipperCast for the bite, the weather window or what you can keep. Same answers, right on your phone.',
  ctaButton: "Text SkipperCast for today's report",
  ctaChat: 'Ask SkipperCast',
  ctaDefaultMessage: 'Hi SkipperCast',
  saveContact: 'Save the number',
  qrAlt: 'QR code: scan it to text SkipperCast',
  notFoundTitle: 'Page not found',
  notFoundBody: 'We have no page at this address. The map has every port and species.',
  date: 'Date',
  boat: 'Boat',
  trip: 'Trip',
  anglers: 'Anglers',
  catch: 'Catch',
  port: 'Port',
  kept: 'Kept',
  releasedHeader: 'Released',
  reports: 'Reports',
  anotherBoat: 'Another boat',
  edited: 'edited',
  released: n => `${n} released`,
  releasedOnly: (n, label) => `${n} ${label} released`,
  trips: {'half-day': 'Half day', '3/4 day': 'Three-quarter day', 'full-day': 'Full day', overnight: 'Overnight'},
  portTitle: port => `${port} fishing report`,
  portDescription: port => `What's biting out of ${port}: skipper reports, today's conditions and seasons, updated through the day.`,
  portRegion: region => `Region: ${region}`,
  portCtaMessage: port => `What's biting out of ${port}?`,
  todayHeading: "Today's report",
  reportsHeading: 'Skipper reports, last 14 days',
  reportsNone: 'No skipper reports in the last 14 days.',
  reportsUnverifiedNote: 'Another boat: a boat the SkipperCast team has yet to verify.',
  conditionsHeading: "Today's fishing window",
  conditionsNone: 'No forecast for today yet.',
  seas: 'Seas',
  wind: 'Wind',
  ride: 'Ride',
  seasValue: (range, period) => `${range} ft${period ? ` at ${period} s` : ''}`,
  windValue: (range, from) => `${range} kt${from ? ` from the ${from}` : ''}`,
  comfort: {comfortable: 'Comfortable', bumpy: 'Bumpy', rough: 'Rough'},
  rideValue: word => `${word} for a mid-size center console`,
  advisoriesHeading: 'Advisories',
  boatsHeading: port => `Boats out of ${port}`,
  boatsNone: 'No verified boats here yet.',
  seasonsHeading: 'Species and seasons',
  seasonsNote: 'From the SkipperCast rules table, checked against CDFW. Open a species for its rules and source.',
  ruleState: {open: 'Open today', closed: 'Closed today', review: 'Under review', unknown: 'Check the rules'},
  speciesTitle: name => `${name}: how to tell it apart, rules and recent catches`,
  speciesDescription: name => `${name}: field marks and look-alikes, the current rules with their source, and recent catches reported to SkipperCast.`,
  speciesNames: (en, es) => `English: ${en} · Spanish: ${es}`,
  idHeading: 'How to tell it apart',
  lookalikesHeading: 'Often confused with',
  idNone: 'No field marks on file yet.',
  rulesHeading: 'Rules',
  rulesNone: 'No rule on file for this species yet. Check CDFW before you keep one.',
  underReview: 'Under review',
  underReviewNote: 'This rule is due for review. Check the source before you keep a fish.',
  groupRule: label => `Group rule: ${label}`,
  regionRule: region => `CDFW ${region} region`,
  minSize: 'Minimum size',
  maxSize: 'Maximum size',
  bag: 'Daily bag',
  season: 'Season',
  depth: 'Depth',
  area: 'Area',
  gear: 'Gear',
  source: 'Source',
  reviewed: 'Reviewed',
  inches: n => `${n} in`,
  feetMax: n => `${n} ft or shallower`,
  seasonRange: (open, close) => `${open} to ${close}`,
  noTake: 'No take',
  noSeasonDates: 'No season dates on file',
  bagValue: n => (n === 0 ? 'None: release every fish' : `${n} per angler`),
  catchesHeading: 'Recent catches, last 14 days',
  catchesNone: 'No reported catches in the last 14 days.',
  catchesNote: 'Counts from verified boats that report to SkipperCast.',
  strategyHeading: 'How it is fished',
  strategyNone: 'No method notes for this species yet.',
  strategyLanguageNote: '',
  rig: 'Rig',
  baitOrLure: 'Bait or lure',
  where: 'Where',
  when: 'When',
  howTo: 'How',
  sourcesHeading: 'Sources',
  boatTitle: boat => `${boat}: fish reports`,
  boatDescription: (boat, port) => `Fish counts and photos from ${boat} out of ${port}, as the boat reports them to SkipperCast.`,
  verified: 'Verified boat',
  unverified: 'Not verified yet',
  unverifiedNote: 'The SkipperCast team has yet to confirm this boat. Its reports show here meanwhile.',
  landing: (landing, port) => `${landing}, ${port}`,
  boatReportsHeading: 'Reports, last 30 days',
  boatReportsNone: 'No reports in the last 30 days.',
  photosHeading: 'Photos',
  photoAlt: boat => `Photo from ${boat}`,
  photoCredit: credit => `Photo: ${credit}`,
  bookHeading: 'Book a trip',
  bookingLink: 'Booking page',
  call: phone => `Call ${phone}`,
  instagram: handle => `Instagram: @${handle}`,
};

const PAGES_ES: PageCopy = {
  home: 'SkipperCast',
  ports: 'Puertos',
  species: 'Especies',
  boats: 'Barcos',
  breadcrumbs: 'Ruta de navegación',
  skip: 'Ir al reporte',
  otherLanguage: 'In English',
  openMap: 'Abrir el mapa',
  terms: 'Términos',
  privacy: 'Privacidad',
  disclaimer: 'Ayuda para planear · no es una carta náutica. Las reglas cambian. Confírmalas con CDFW y NOAA antes de pescar.',
  forecastNote: 'Los pronósticos son estimaciones; las condiciones pueden cambiar. Revisa el pronóstico marino del NWS.',
  ctaHeading: 'Recibe el reporte por mensaje',
  ctaBody: 'Escribe a SkipperCast para saber qué está picando, cómo viene el tiempo o qué puedes quedarte. Las mismas respuestas, en tu teléfono.',
  ctaButton: 'Escribe a SkipperCast para el reporte de hoy',
  ctaChat: 'Pregunta a SkipperCast',
  ctaDefaultMessage: 'Hola SkipperCast',
  saveContact: 'Guarda el número',
  qrAlt: 'Código QR: escanéalo para escribir a SkipperCast',
  notFoundTitle: 'Página no encontrada',
  notFoundBody: 'No hay ninguna página en esta dirección. El mapa tiene todos los puertos y especies.',
  date: 'Fecha',
  boat: 'Barco',
  trip: 'Viaje',
  anglers: 'Pescadores',
  catch: 'Captura',
  port: 'Puerto',
  kept: 'Guardados',
  releasedHeader: 'Liberados',
  reports: 'Reportes',
  anotherBoat: 'Otro barco',
  edited: 'editado',
  released: n => `${n} liberados`,
  releasedOnly: (n, label) => `${n} ${label} liberados`,
  trips: {'half-day': 'Medio día', '3/4 day': 'Tres cuartos de día', 'full-day': 'Día completo', overnight: 'Toda la noche'},
  portTitle: port => `Reporte de pesca de ${port}`,
  portDescription: port => `Qué está picando en ${port}: reportes de capitanes, las condiciones de hoy y las temporadas, al día.`,
  portRegion: region => `Región: ${region}`,
  portCtaMessage: port => `¿Qué está picando en ${port}?`,
  todayHeading: 'El reporte de hoy',
  reportsHeading: 'Reportes de capitanes, últimos 14 días',
  reportsNone: 'Sin reportes de capitanes en los últimos 14 días.',
  reportsUnverifiedNote: 'Otro barco: un barco que el equipo de SkipperCast aún no verifica.',
  conditionsHeading: 'La ventana de pesca de hoy',
  conditionsNone: 'Aún no hay pronóstico para hoy.',
  seas: 'Mar',
  wind: 'Viento',
  ride: 'Navegación',
  seasValue: (range, period) => `${range} pies${period ? ` a ${period} s` : ''}`,
  windValue: (range, from) => `${range} nudos${from ? ` del ${from}` : ''}`,
  comfort: {comfortable: 'Cómodo', bumpy: 'Movido', rough: 'Duro'},
  rideValue: word => `${word} para una lancha mediana de consola central`,
  advisoriesHeading: 'Avisos',
  boatsHeading: port => `Barcos de ${port}`,
  boatsNone: 'Aún no hay barcos verificados aquí.',
  seasonsHeading: 'Especies y temporadas',
  seasonsNote: 'De la tabla de reglas de SkipperCast, revisada contra CDFW. Abre una especie para ver sus reglas y la fuente.',
  ruleState: {open: 'Abierta hoy', closed: 'Cerrada hoy', review: 'En revisión', unknown: 'Revisa las reglas'},
  speciesTitle: name => `${name}: cómo distinguirlo, reglas y capturas recientes`,
  speciesDescription: name => `${name}: señas para identificarlo y especies parecidas, las reglas vigentes con su fuente y las capturas recientes reportadas a SkipperCast.`,
  speciesNames: (en, es) => `Inglés: ${en} · Español: ${es}`,
  idHeading: 'Cómo distinguirlo',
  lookalikesHeading: 'Se confunde con',
  idNone: 'Aún no hay señas registradas.',
  rulesHeading: 'Reglas',
  rulesNone: 'Aún no hay reglas registradas para esta especie. Revisa con CDFW antes de quedarte uno.',
  underReview: 'En revisión',
  underReviewNote: 'Esta regla está pendiente de revisión. Revisa la fuente antes de quedarte un pez.',
  groupRule: label => `Regla del grupo: ${label}`,
  regionRule: region => `Región ${region} de CDFW`,
  minSize: 'Talla mínima',
  maxSize: 'Talla máxima',
  bag: 'Límite diario',
  season: 'Temporada',
  depth: 'Profundidad',
  area: 'Zona',
  gear: 'Equipo',
  source: 'Fuente',
  reviewed: 'Revisada',
  inches: n => `${n} pulg`,
  feetMax: n => `${n} pies o menos`,
  seasonRange: (open, close) => `del ${open} al ${close}`,
  noTake: 'Prohibido quedarse',
  noSeasonDates: 'Sin fechas de temporada registradas',
  bagValue: n => (n === 0 ? 'Ninguno: libera cada pez' : `${n} por pescador`),
  catchesHeading: 'Capturas recientes, últimos 14 días',
  catchesNone: 'Sin capturas reportadas en los últimos 14 días.',
  catchesNote: 'Conteos de barcos verificados que reportan a SkipperCast.',
  strategyHeading: 'Cómo se pesca',
  strategyNone: 'Aún no hay notas de pesca para esta especie.',
  strategyLanguageNote: 'Las notas de pesca están en inglés.',
  rig: 'Aparejo',
  baitOrLure: 'Carnada o señuelo',
  where: 'Dónde',
  when: 'Cuándo',
  howTo: 'Cómo',
  sourcesHeading: 'Fuentes',
  boatTitle: boat => `${boat}: reportes de pesca`,
  boatDescription: (boat, port) => `Conteos y fotos de ${boat}, de ${port}, tal como el barco los reporta a SkipperCast.`,
  verified: 'Barco verificado',
  unverified: 'Aún sin verificar',
  unverifiedNote: 'El equipo de SkipperCast aún no confirma este barco. Mientras tanto, sus reportes aparecen aquí.',
  landing: (landing, port) => `${landing}, ${port}`,
  boatReportsHeading: 'Reportes, últimos 30 días',
  boatReportsNone: 'Sin reportes en los últimos 30 días.',
  photosHeading: 'Fotos',
  photoAlt: boat => `Foto de ${boat}`,
  photoCredit: credit => `Foto: ${credit}`,
  bookHeading: 'Reserva un viaje',
  bookingLink: 'Página de reservas',
  call: phone => `Llama al ${phone}`,
  instagram: handle => `Instagram: @${handle}`,
};

/** Every string of the public pages, by language. */
export const PAGES_COPY: Readonly<Record<PageLanguage, PageCopy>> = {en: PAGES_EN, es: PAGES_ES};
// TA-W1 end.
