import {daily,canPlayForecast,forecastHour,localWave,quietestHours,selectedArea,isToday,type AppState} from '../state/experience.ts';
import {availableDays} from '../daily.ts';
import {nearshoreSampleLabel} from '../presentation.ts';
import {escapeHTML as esc,value,time,range,direction,ageLabel} from './format.ts';
import {icon} from './icons.ts';
import {fleetBrief,recentCatchTrips} from './catches.ts';
import {chart,type Series} from '../charts/series.ts';
export const atTime=(s:AppState,at:string)=>time(at,s.county.timezone,{hour:'numeric',minute:'2-digit'});
export function timeSpan(s:AppState,start:string,end:string){return `${Date.parse(start)<s.now.getTime()&&Date.parse(end)>s.now.getTime()?'Now':time(start,s.county.timezone,{hour:'numeric'})}–${time(end,s.county.timezone,{hour:'numeric'})}`;}
export function tideAt(s:AppState){const b=daily(s),t=Date.parse(s.at),i=b.tides.findIndex(p=>Math.abs(Date.parse(p.at)-t)<=4*60000),p=b.tides[i];return {point:p,trend:p&&b.tides[i+1]&&Date.parse(b.tides[i+1].at)-Date.parse(p.at)<=15*60000?Math.abs(b.tides[i+1].heightFt-p.heightFt)<.005?'Turning':b.tides[i+1].heightFt>p.heightFt?'Rising':'Falling':'Station prediction'};}
function metric(s:AppState,label:string,v:string,unit:string,note:string,color:string,symbol:string){return `<div class="glance-metric ${color}"><span>${icon(symbol)}${label}</span><strong>${v}<small>${unit}</small></strong><small>${esc(note)}</small></div>`;}
export function briefing(s:AppState){
 const b=daily(s),h=forecastHour(s),wave=localWave(s),tide=tideAt(s),window=quietestHours(s),area=selectedArea(s),night=b.sunset&&s.now.getTime()>Date.parse(b.sunset)&&isToday(s);
 const headline=b.alerts.length?b.alerts[0].event:!h?'The coast needs a fresh reading.':night?'One last look. Plan the morning.':b.seas.max!==null&&b.seas.max>=5?'Swell sets the terms today.':b.wind.max!==null&&b.wind.max>=12?'Find your water before the wind.':s.mode==='spear'?'Read the swell. Check the visibility.':'A clearer picture of your coast.';
 const health=s.report.sources.find(x=>x.id==='slo-beach-water-quality'),healthAge=health?s.now.getTime()-Date.parse(health.fetchedAt):Infinity,advisory=health?.outcome==='ok'&&healthAge>=-300000&&healthAge<3*3600000?(s.report.waterQuality??[]).filter(x=>x.areaId===s.areaId&&/advisory|closed|warning/i.test(x.status)):[];
 const when=night?'Explore tomorrow':window?timeSpan(s,window.start,window.end):'No window qualified';
 return `<div class="brief-kicker"><span><i class="signal-dot"></i>${esc(b.label)}’s fishing report</span><span>${time(s.date+'T20:00:00Z',s.county.timezone,{month:'short',day:'numeric'})}</span></div>
 <h1>${esc(headline)}</h1><p class="brief-deck">${h?`${range(b.wind.min,b.wind.max)} kt wind. ${range(b.seas.min,b.seas.max,1)} ft offshore seas${b.seas.period!==null?' at up to '+value(b.seas.period)+'s':''}.`: 'Fresh marine forecasts are unavailable.'} ${s.mode==='spear'?'In-water visibility is unverified.':b.seas.period!==null&&b.seas.period>=15?'Long-period swell can amplify surge.':''}${b.confidence.includes('provisional')?' Provisional outlook; check again closer to departure.':''}</p>
 <div class="plan-answer"><div><span class="eyebrow">${night?'NEXT DAYLIGHT':window?.qualified?'LOWER EXPOSURE':'TIMING TO EXPLORE'}</span><strong>${esc(when)}</strong><small>${night?'Daylight has ended locally.':window?(window.qualified?'Wind + seas screening · local check required':'Relative lull · local checks required'):'Open the conditions before choosing a time.'}</small></div>${night?`<button data-next-day class="round-action" aria-label="Explore tomorrow">${icon('arrow')}</button>`:icon('sun')}</div>
 <button class="brief-map-action" data-explore-map>${icon('map')}Explore the coast map${icon('arrow')}</button>
 <div class="glance-grid">
 ${metric(s,'Wind',value(h?.windKnots),'kt',`${direction(h?.windDirectionDeg)} · gust ${value(h?.gustKnots)} kt`,'mint','wind')}
 ${metric(s,'Nearshore',value(wave?.hour?.waveFt,1),'ft',`${value(wave?.hour?.periodS)}s · ${wave?nearshoreSampleLabel(wave.site,wave.hour,s.county.timezone):'No local model'}`,'blue','wave')}
 ${metric(s,'Water',value(b.tempObservation?.waterTempF,1),'°F',b.tempObservation?'Buoy · '+atTime(s,b.tempObservation.observedAt):isToday(s)?'No fresh local buoy':'Water temperature is not forecast','coral','temperature')}
 ${metric(s,'Tide',value(tide.point?.heightFt,1),'ft',`${tide.trend} · MLLW`,'amber','tide')}
 </div><div class="brief-subline"><span>${icon('temperature')}Air ${value(h?.airTempF)}°</span><span>${icon('cloud')}Cloud ${value(h?.cloudCoverPct)}%</span><span>${icon('sun')}${b.sunset?atTime(s,b.sunset):'—'} sunset</span></div>
 <div class="mini-tide">${tideChart(s)}<div><span>${esc(s.county.tideStation.name)} tide</span><span>${b.tideEvents.map(e=>`${e.type==='H'?'H':'L'} ${atTime(s,e.at)}`).join(' · ')}</span></div></div>
 <div class="spot-heading"><span class="eyebrow">WHERE TO INVESTIGATE</span><span>${icon('target')}</span></div><div id="spot-list" class="spot-list"><p class="subtle">Reading mapped habitat…</p></div>
 ${fleetBrief(s)}
 ${advisory.length?`<a class="brief-advisory" href="${esc(advisory[0].url)}" target="_blank" rel="noopener">${icon('shield')}${advisory.length} beach-health notice${advisory.length===1?'':'s'} · check county report ${icon('arrow')}</a>`:''}<div class="brief-footer"><span>${esc(area.name)}</span><button data-open="sources">${icon('info')}Data & confidence</button></div>`;
}
export function tideChart(s:AppState){const b=daily(s);if(b.tides.length<2)return '<div class="empty-chart">Tide series unavailable</div>';return chart([{label:'Tide',unit:'ft MLLW',color:'#eabd76',points:b.tides.map(p=>({at:p.at,value:p.heightFt})),gapMs:15*60000,min:b.tideRange.min??0,max:(b.tideRange.max??5)+.3}],b.tides[0].at,b.tides.at(-1)!.at,s.at,s.county.timezone,{mini:true,sunrise:b.sunrise,sunset:b.sunset});}
export function days(s:AppState){return availableDays(s.report,s.county,selectedArea(s),s.now).map(d=>`<button data-day="${d.date}" class="day-tab ${d.date===s.date?'active':''}" aria-pressed="${d.date===s.date}"><b>${esc(d.label)}</b><span>${d.dayNumber} ${time(d.date+'T20:00:00Z',s.county.timezone,{month:'short'})}${d.provisional?' · outlook':''}</span></button>`).join('');}
export function timeline(s:AppState){const b=daily(s),h=forecastHour(s);return `<div class="day-tabs" aria-label="Forecast day">${days(s)}</div><div class="time-dock-center"><div class="time-dock-heading"><button id="play" class="icon-button" ${canPlayForecast(s)?'':'disabled'} aria-label="${s.playing?'Pause':'Play'} forecast">${icon(s.playing?'pause':'play')}</button><div><b id="selected-clock">${time(s.at,s.county.timezone,{weekday:'short',hour:'numeric',timeZoneName:'short'})}</b><span>${h?'Forecast hour · slide to explore':'No forecast hours'}</span></div><div class="time-values"><span class="mint">${value(h?.windKnots)}<small> kt</small></span><span class="blue">${value(h?.waveFt,1)}<small> ft</small></span><span class="amber">${value(tideAt(s).point?.heightFt,1)}<small> ft tide</small></span></div></div><input id="hour-slider" type="range" aria-label="Forecast hour" min="0" max="${Math.max(0,b.hours.length-1)}" step="1" value="${Math.max(0,b.hours.findIndex(h=>h.at===s.at))}" ${b.hours.length?'':'disabled'} aria-valuetext="${esc(time(s.at,s.county.timezone,{weekday:'long',hour:'numeric'}))}"><div class="time-ticks">${[0,.25,.5,.75,1].map(f=>{const h=b.hours[Math.round(f*(b.hours.length-1))];return `<span>${h?time(h.at,s.county.timezone,{hour:'numeric'}):'—'}</span>`;}).join('')}</div></div><div class="timeline-note">${icon('tide')}<div><b>Read the whole day</b><span>Map + forecast move together.<br>Observations keep their actual time.</span></div></div>`;}
export function conditions(s:AppState){
 const b=daily(s),h=forecastHour(s),wave=localWave(s),start=b.hours[0]?.at??b.tides[0]?.at??s.at,end=b.hours.at(-1)?.at??b.tides.at(-1)?.at??s.at;
 const rows:Series[]=[{label:'Wind',unit:'knots',color:'#64e4c0',points:b.hours.map(h=>({at:h.at,value:h.windKnots})),min:0},{label:'Gusts',unit:'knots',color:'#a5f4d8',points:b.hours.map(h=>({at:h.at,value:h.gustKnots})),min:0},{label:'Offshore',unit:'feet',color:'#60b9ff',points:b.hours.map(h=>({at:h.at,value:h.waveFt})),min:0},{label:'Nearshore',unit:'feet · 3h',color:'#ab94ff',points:(wave?.site.hours??[]).map(h=>({at:h.at,value:h.waveFt})),min:0,gapMs:3*3600000},{label:'Tide',unit:'ft MLLW',color:'#eabd76',points:b.tides.map(p=>({at:p.at,value:p.heightFt})),gapMs:15*60000},{label:'Air',unit:'°F',color:'#ff9580',points:b.hours.map(h=>({at:h.at,value:h.airTempF})),min:Math.min(40,...b.hours.map(h=>h.airTempF??60))-5},{label:'Cloud',unit:'percent',color:'#abc5d7',points:b.hours.map(h=>({at:h.at,value:h.cloudCoverPct})),min:0,max:100}];
 return `<div class="view-heading"><div><span class="eyebrow">${esc(selectedArea(s).name)} / ${esc(b.label)}</span><h2>The water, hour by hour.</h2><p>One time axis. Every part of the picture.</p></div><span class="source-chip">NWS · CDIP · NOAA</span></div><div class="conditions-summary"><div><span>Selected hour</span><b>${atTime(s,s.at)}</b></div><div><span>Wind / gust</span><b class="mint">${value(h?.windKnots)} / ${value(h?.gustKnots)}<small> kt</small></b></div><div><span>Seas / period</span><b class="blue">${value(h?.waveFt,1)}<small> ft · </small>${value(h?.wavePeriodS)}<small>s</small></b></div><div><span>Air / rain</span><b class="coral">${value(h?.airTempF)}°<small> / </small>${value(h?.precipPct)}%</b></div></div><div class="chart-overflow forecast-chart-overflow" role="region" aria-label="Scrollable hourly forecast chart" tabindex="0"><div class="chart-card" id="forecast-chart">${chart(rows,start,end,s.at,s.county.timezone,{sunrise:b.sunrise,sunset:b.sunset,windows:b.windows})}</div></div><p class="chart-swipe-hint">Scroll sideways through the hourly outlook.</p><div class="chart-caption"><span><i class="legend-dot mint-bg"></i>Shading: screened lower-exposure window</span><span>Dark shading: night · Separate vertical scales</span></div><div class="conditions-notes"><section><h3>${icon('tide')}Tide events</h3>${b.tideEvents.map(t=>`<div class="event-row"><span>${t.type==='H'?'High water':'Low water'}</span><b>${atTime(s,t.at)}</b><strong class="amber">${value(t.heightFt,1)} ft</strong></div>`).join('')}<p>${esc(s.county.tideStation.note)} High water does not mean slack current.</p></section><section><h3>${icon('eye')}${s.mode==='spear'?'Before you enter':'Before you go'}</h3><p>${esc(selectedArea(s).accessNote)}</p><p>${wave?`${esc(nearshoreSampleLabel(wave.site,wave.hour,s.county.timezone))}. This is a nearshore model point; beach breakers can differ.`:''} ${s.mode==='spear'?'Visibility is unknown without an in-water report. Surface currents cannot clear a dive.':'Habitat and timing describe a place to investigate; fish presence is unverified.'}</p><a class="text-link" href="${esc(s.county.ruleLinks[0].url)}" target="_blank" rel="noopener">Current CDFW rules ${icon('arrow')}</a></section></div>`;
}
export function sourceSheet(s:AppState){return `<div class="sheet-heading"><span class="eyebrow">THE EVIDENCE BEHIND YOUR REPORT</span><h2>Know what you’re looking at.</h2><p>Forecasts, observations, predictions and habitat carry separate clocks.</p></div><div class="source-summary"><b>${s.report.sources.filter(x=>x.outcome==='ok').length}</b><span>feeds retrieved<br>Report assembled ${ageLabel(s.report.generatedAt,s.now)}</span></div><div class="source-list">${s.report.sources.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener"><i class="source-dot ${x.outcome}"></i><div><b>${esc(x.label)}</b><span>${esc(x.kind)} · ${x.outcome==='ok'?'retrieved '+ageLabel(x.fetchedAt,s.now):x.outcome==='pending'?'not integrated':x.id==='landing-reports'&&s.report.catchContext?'partial dated evidence':'collection failed'}${x.issuedAt?' · '+time(x.issuedAt,s.county.timezone,{month:'short',day:'numeric',hour:'numeric'}):''}</span></div>${icon('arrow')}</a>`).join('')}</div><h3>Local fleet reports</h3><p>${recentCatchTrips(s).length?'Dated local trip reports are available; the original trip dates and source links are preserved.':'Fresh local catch reports have not been verified for this edition.'}</p>${recentCatchTrips(s).length?'<button class="text-link" data-open="catches">Read dated fleet reports '+icon('arrow')+'</button>':''}<div class="sheet-links">${s.county.catchLinks.map(link=>`<a href="${esc(link.url)}" target="_blank" rel="noopener">${esc(link.label)}</a>`).join('')}</div><h3>Confidence, in plain language</h3><p>Habitat fit is a relative physical match, not a catch probability. A lighter-wind window is not a measured bite forecast. Offshore wave height does not measure surf at an entry. Sea surface temperature is not bottom temperature.</p><p>${s.mode==='spear'?'In-water visibility remains unknown. ':''}Permanent protected-area screening does not establish current season, gear or fishery eligibility.</p><div class="sheet-links"><a href="/methodology">Full methodology</a><a href="/feed.xml">Follow the report</a><a href="/privacy">Privacy</a></div>`;}
