import type {HistoryBundle,HistoryMetric,StationHistory,MonthlyDistribution} from '../history-types.ts';
import type {County} from '../types.ts';
import {linePath} from '../charts/series.ts';
import {escapeHTML as esc,time,value,ageLabel} from './format.ts';
import {icon} from './icons.ts';
const HOUR=3600000;
const metrics:Record<HistoryMetric,{label:string;unit:string;color:string}>={waterTempF:{label:'Sea temperature',unit:'°F',color:'#ff9e86'},waveFt:{label:'Wave height',unit:'ft',color:'#66bfff'},windKnots:{label:'Wind',unit:'kt',color:'#65e3c0'},airTempF:{label:'Air temperature',unit:'°F',color:'#ecbb70'},gustKnots:{label:'Reported gust',unit:'kt',color:'#b5eaaa'},periodS:{label:'Dominant wave period',unit:'sec',color:'#bb9aff'}};
const finite=(n:unknown):n is number=>typeof n==='number'&&Number.isFinite(n);
export type HistorySelection={station:string;metric:HistoryMetric;days:number};
const unavailable=()=>`<div class="view-heading"><div><span class="eyebrow">RECORDED OCEAN HISTORY</span><h2>A longer view of the coast.</h2><p>Historical observations are unavailable for this county.</p></div></div>`;
const supportedSeason=(m:MonthlyDistribution|undefined):m is MonthlyDistribution=>!!m&&m.count>0&&finite(m.median)&&finite(m.p10)&&finite(m.p90)&&m.p10<=m.median&&m.median<=m.p90;
// The fields of AppState this view reads; declared here so the view type-checks without state/experience.ts.
export type HistoryViewContext={county:County;now:Date};
export function historyView(s:HistoryViewContext,bundle:HistoryBundle|null,selection:HistorySelection){
 if(!bundle||bundle.countyId!==s.county.id||!Array.isArray(bundle.stations)||!bundle.stations.length)return unavailable();
 const station=bundle.stations.find(st=>st.stationId===selection.station)??bundle.stations[0];if(!station)return unavailable();
 const selected:HistorySelection={station:station.stationId,metric:metrics[selection.metric]?selection.metric:'waterTempF',days:[7,14,45].includes(selection.days)?selection.days:45};
 const spec=metrics[selected.metric],cut=Math.floor(s.now.getTime()/HOUR)*HOUR-selected.days*86400000;
 const hours=station.recent.hours.filter(h=>Number.isFinite(Date.parse(h.at))&&Date.parse(h.at)>=cut&&Date.parse(h.at)<=s.now.getTime()).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));
 const valid=hours.filter(h=>finite(h[selected.metric])),latest=valid.at(-1),vals=valid.map(h=>h[selected.metric]!);
 const mean=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;
 // Baseline buckets are UTC months. Compare actual observations, independently of forecast date selection.
 const contextAt=latest?.at??s.now.toISOString(),month=new Date(contextAt).getUTCMonth()+1;
 const found=station.baseline.months.find(m=>m.month===month&&m.metric===selected.metric),season=supportedSeason(found)?found:undefined;
 const fresh=!!latest&&s.now.getTime()-Date.parse(latest.at)<3*HOUR;
 const expectedHours=Math.ceil((s.now.getTime()-cut)/HOUR),coverage=expectedHours?valid.length/expectedHours:0;
 const difference=latest&&season?latest[selected.metric]!-season.median!:null;
 const hasMetric=(metric:HistoryMetric)=>station.recent.hours.some(h=>finite(h[metric]))||station.baseline.months.some(m=>m.metric===metric&&m.count>0&&finite(m.median));
 const sourceClock=station.recent.lastObservedAt;
 return `<div class="view-heading"><div><span class="eyebrow">RECORDED OCEAN HISTORY</span><h2>Know the pattern. Notice the change.</h2><p>${esc(station.name)} · recorded buoy measurements and seasonal context.</p></div><span class="source-chip">NOAA NDBC · ${station.archive.availableYears.length} indexed annual archives</span></div>
 <div class="history-controls"><label>Station<select id="history-station">${bundle.stations.map(st=>`<option value="${esc(st.stationId)}" ${station.stationId===st.stationId?'selected':''}>${esc(st.name)} · ${esc(st.stationId)}</option>`).join('')}</select></label><label>Measurement<select id="history-metric">${Object.entries(metrics).map(([id,m])=>`<option value="${id}" ${selected.metric===id?'selected':''}>${m.label}${hasMetric(id as HistoryMetric)?'':' · unavailable here'}</option>`).join('')}</select></label><div class="range-switch" aria-label="History time range">${[7,14,45].map(d=>`<button type="button" data-history-days="${d}" class="${selected.days===d?'active':''}" aria-pressed="${selected.days===d}">${d} days</button>`).join('')}</div></div>
 ${!hasMetric(selected.metric)?`<p class="history-measurement-note">This station has no supported ${spec.label.toLowerCase()} measurements in the collected record. Choose another measurement or station.</p>`:''}
 <div class="history-stats"><div><span>Latest hourly mean</span><b style="color:${spec.color}">${value(latest?.[selected.metric],1)}<small> ${spec.unit}</small></b><small>${latest?'Hour starting '+time(latest.at,s.county.timezone,{month:'short',day:'numeric',hour:'numeric',timeZoneName:'short'})+(fresh?'':' · historical, not current'):'No measurement'}</small></div><div><span>${selected.days}-day average</span><b>${value(mean,1)}<small> ${spec.unit}</small></b><small>${valid.length.toLocaleString()} / ${expectedHours.toLocaleString()} hourly bins · ${value(coverage*100,1)}% metric coverage</small></div><div><span>Recorded UTC ${time(contextAt,'UTC',{month:'long'})} median</span><b>${value(season?.median,1)}<small> ${spec.unit}</small></b><small>${season?.yearsWithData.length??0} contributing ${(season?.yearsWithData.length??0)===1?'year':'years'} · ${(season?.count??0).toLocaleString()} ${(season?.count??0)===1?'hour':'hours'}${season?' · '+value(season.coverageFraction*100,1)+'% coverage':''}</small></div><div><span>Versus that month's median</span><b class="${difference!==null&&difference>0?'coral':'blue'}">${difference===null?'—':(difference>0?'+':'')+value(difference,1)}<small> ${spec.unit}</small></b><small>${latest?'Recorded hourly comparison':'No supported comparison'} · not a forecast</small></div></div>
 <section class="history-chart-card"><div class="chart-title"><h3>${spec.label}</h3><span>${spec.unit} · hourly means · ${esc(s.county.timezone)}</span></div><div class="chart-overflow" role="region" aria-label="Scrollable recorded observations chart" tabindex="0">${recentChart(s,station,selected,cut)}</div><p class="chart-swipe-hint">Scroll sideways to explore the full chart.</p><div class="chart-caption"><span><i class="legend-dot" style="background:${spec.color}"></i>Hourly observations</span><span>Missing measurements remain gaps</span></div></section>
 <section class="season-card"><div class="chart-title"><div><span class="eyebrow">THE SEASONAL CONTEXT</span><h3>What this buoy has recorded.</h3></div><span>${station.baseline.years.length===1?station.baseline.years[0]:station.baseline.years.length?`${station.baseline.years[0]}–${station.baseline.years.at(-1)}`:'No annual reference'}</span></div><div class="chart-overflow" role="region" aria-label="Scrollable seasonal observations chart" tabindex="0">${seasonChart(station,selected.metric,month)}</div><p class="chart-swipe-hint">Scroll sideways to explore all twelve months.</p><div class="chart-caption"><span><i class="legend-dot" style="background:${spec.color}"></i>Median · band is 10th–90th percentile</span><span>UTC-month buckets · coverage varies</span></div><p>These distributions describe recorded UTC-hour means over the listed archive years. The highlighted month matches the latest displayed observation, independently of the forecast date. They are not a standard 30-year climatology, a forecast, or a prediction of fishing success. Each observed hour has equal weight; missing years and hours are not filled.</p></section>
 <details class="history-measurement-note"><summary>Reference coverage and contributing years</summary><p>${season?`UTC ${time(contextAt,'UTC',{month:'long'})} ${spec.label.toLowerCase()}: ${season.count.toLocaleString()} observed hours out of ${season.expectedHours.toLocaleString()} calendar hours; ${season.rawSampleCount.toLocaleString()} valid original samples. 10th / median / 90th percentile: ${value(season.p10,1)} / ${value(season.median,1)} / ${value(season.p90,1)} ${spec.unit}.`:'No supported monthly reference for this measurement.'}</p><p>Contributing years: ${season?.yearsWithData.length?season.yearsWithData.join(', '):'none'}.</p></details><div class="history-provenance"><span>${icon('history')}${station.sources.filter(x=>x.role==='annual'&&x.outcome==='ok').length} annual archives loaded</span><span>${icon('check')}${value(station.recent.hourCoverageFraction*100,1)}% coverage for any metric in the collected ${bundle.recentWindowDays}-day series</span><span>Latest source report: ${sourceClock?time(sourceClock,s.county.timezone,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'})+' · '+ageLabel(sourceClock,s.now):'unknown'}</span><a href="https://www.ndbc.noaa.gov/station_history.php?station=${esc(station.stationId)}" target="_blank" rel="noopener">Original NOAA record ${icon('arrow')}</a></div><p class="history-measurement-note">Current station position is a reference; historical deployments and sensors can change. ${selected.metric==='gustKnots'?'Hourly gust means are not the worst gust in each hour. ':''}${selected.metric==='periodS'?'Hourly dominant-period means are not a spectral wave distribution. ':''}Surface buoy measurements do not describe bottom temperature or exact beach breakers.</p>`;
}
function recentChart(s:HistoryViewContext,station:StationHistory,selection:HistorySelection,cut:number){
 const spec=metrics[selection.metric],points=station.recent.hours.filter(h=>Number.isFinite(Date.parse(h.at))&&Date.parse(h.at)>=cut&&Date.parse(h.at)<=s.now.getTime()).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)).map(h=>({at:h.at,value:finite(h[selection.metric])?h[selection.metric]:null}));
 const values=points.map(p=>p.value).filter((n):n is number=>finite(n)),width=1000,height=270,left=47,right=20,top=20,bottom=40,low=values.length?Math.floor(Math.min(...values)-1):0,high=values.length?Math.ceil(Math.max(...values)+1):10,x=(at:string)=>left+(Date.parse(at)-cut)/(s.now.getTime()-cut)*(width-left-right),y=(v:number)=>height-bottom-(v-low)/(high-low)*(height-top-bottom),path=linePath(points,x,y,90*60000);
 return `<svg class="history-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="${spec.label}, previous ${selection.days} days, ${spec.unit}. Missing observations remain gaps.">${[0,.25,.5,.75,1].map(f=>{const v=low+(high-low)*f;return `<line x1="${left}" x2="${width-right}" y1="${y(v)}" y2="${y(v)}" stroke="#9db6cc" stroke-opacity=".1"/><text x="32" y="${y(v)+4}" text-anchor="end" class="axis">${value(v,1)}</text>`;}).join('')}${[0,.2,.4,.6,.8,1].map(f=>`<text x="${left+f*(width-left-right)}" y="${height-10}" text-anchor="middle" class="axis">${time(new Date(cut+f*(s.now.getTime()-cut)).toISOString(),s.county.timezone,{month:'short',day:'numeric'})}</text>`).join('')}<path d="${path}" fill="none" stroke="${spec.color}" stroke-width="1.7" vector-effect="non-scaling-stroke"/>${!values.length?`<text x="500" y="130" class="axis" text-anchor="middle">No supported ${spec.label.toLowerCase()} observations in this interval.</text>`:''}</svg>`;
}
function seasonChart(station:StationHistory,metric:HistoryMetric,month:number){
 const spec=metrics[metric],months=Array.from({length:12},(_,i)=>station.baseline.months.find(m=>m.metric===metric&&m.month===i+1)),valid=months.filter(supportedSeason),vals=valid.flatMap(m=>[m.p10!,m.p90!]),low=vals.length?Math.floor(Math.min(...vals)-1):0,high=vals.length?Math.ceil(Math.max(...vals)+1):10,x=(i:number)=>65+i*80,y=(v:number)=>165-(v-low)/(high-low)*132;
 return `<svg class="season-chart" viewBox="0 0 1000 215" role="img" aria-label="Recorded UTC-month ${spec.label}, median and tenth to ninetieth percentile, ${spec.unit}."><rect x="${x(month-1)-24}" y="15" width="48" height="165" rx="8" fill="${spec.color}" opacity=".06"/>${months.map((m,i)=>`<text x="${x(i)}" y="203" text-anchor="middle" class="axis">${['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'][i]}</text>${supportedSeason(m)?`<line x1="${x(i)}" x2="${x(i)}" y1="${y(m.p10!)}" y2="${y(m.p90!)}" stroke="${spec.color}" stroke-width="16" stroke-linecap="round" stroke-opacity=".2"/><circle cx="${x(i)}" cy="${y(m.median!)}" r="4" fill="${spec.color}"/><text x="${x(i)}" y="${y(m.p90!)-14}" text-anchor="middle" class="axis">${value(m.median,1)}</text>`:''}`).join('')}<text x="8" y="26" class="axis">${spec.unit}</text>${!valid.length?'<text x="500" y="100" text-anchor="middle" class="axis">No supported annual reference for this measurement.</text>':''}</svg>`;
}
