import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {readableReportURL} from '../web/readable-links.ts';
const source=readFileSync(new URL('../dist/coastal-current-control.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export function','function');
function fixture(t,current){const saved={document:globalThis.document,window:globalThis.window,location:globalThis.location,MutationObserver:globalThis.MutationObserver};const handlers={},options=[],select={value:'off',querySelector:()=>options.find(o=>o.dataset?.unsupported),append(o){o.remove=()=>options.splice(options.indexOf(o),1);options.push(o)},addEventListener(k,f){handlers[k]=f},removeEventListener(k){delete handlers[k]}},status={},root={querySelector:s=>s==='select'?select:status,remove(){this.removed=true}},mapHost={append(x){x.host=this}},forecastHost={append(x){x.host=this}};let mutation;
 globalThis.document={dispatchEvent(e){handlers.sourceEvent=e.type;},body:{dataset:{view:'map'}},createElement:tag=>tag==='section'?root:{dataset:{}}};globalThis.window={addEventListener(k,f){handlers[k]=f},removeEventListener(k){delete handlers[k]}};globalThis.location={href:'https://example.test/?coast=central&hour=2026-10-07T12:00Z&target=cabezon#map'};if(current!==null){const u=new URL(location.href);u.searchParams.set('current',current);location.href=u.href;}globalThis.MutationObserver=class{constructor(fn){mutation=fn}observe(){}disconnect(){}};
 const init=new Function('navigate',source+';return initCoastalCurrentControl')(u=>location.href=u.href),control=init({mapHost,forecastHost});t.after(()=>{control.destroy();Object.assign(globalThis,saved)});return {control,select,status,root,mapHost,forecastHost,handlers,move:()=>mutation()};}
test('one source control moves Map/Conditions and retains explicit choice and public state',t=>{const h=fixture(t,'hfr-6'),changes=[];h.control.subscribe(id=>changes.push(id));assert.equal(h.control.get(),'hfr-6');assert.equal(h.root.host,h.mapHost);document.body.dataset.view='forecast';h.move();assert.equal(h.root.host,h.forecastHost);h.select.value='wcofs';h.handlers.change();assert.equal(h.control.get(),'wcofs');assert.equal(h.handlers.sourceEvent,'skippercast:current-source');assert.equal(new URL(location.href).searchParams.get('hour'),'2026-10-07T12:00Z');assert.deepEqual(changes,['hfr-6','wcofs']);const u=new URL(location.href);u.searchParams.set('current','off');location.href=u.href;h.handlers.popstate();assert.equal(h.control.get(),'off');assert.match(h.status.textContent,/off/);});
test('unsupported and empty explicit sources preserve URL and labelled gap, never borrow a provider',t=>{const h=fixture(t,'constructor');assert.equal(h.control.get(),'off');assert.equal(h.select.value,'constructor');h.control.status('Surface currents off.');assert.match(h.status.textContent,/Unsupported/);const u=new URL(location.href);u.searchParams.set('current','');location.href=u.href;h.handlers.popstate();assert.equal(h.select.value,'');assert.match(h.status.textContent,/Unsupported/);assert.equal(new URL(location.href).searchParams.get('current'),'');});
test('absent source defaults Off and destroyed controller withdraws listeners',t=>{const h=fixture(t,null);assert.equal(h.control.get(),'off');h.control.destroy();assert.equal(h.handlers.popstate,undefined);assert.equal(h.handlers.change,undefined);assert.equal(h.root.removed,true);});

test('readable return preserves exact public current choice including unknown and empty values',()=>{for(const current of ['wcofs','hfr-6','constructor','']){const u=new URL('https://example.test/?coast=central&profile=spear&private=excluded');u.searchParams.set('current',current);const report=readableReportURL(u.href);assert.equal(report.searchParams.get('current'),current);assert.equal(report.searchParams.has('private'),false);}});
