import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {signal,effect,untracked} from '@preact/signals';import {parseHour,hourParam} from '../web/state.ts';
const source=readFileSync(new URL('../dist/coastal-clock.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export function initCoastalClock','function initCoastalClock');
function fixture(t,value){const saved={document:globalThis.document,MutationObserver:globalThis.MutationObserver,CustomEvent:globalThis.CustomEvent};const timers=[],events=[],writes=[],changes=[],listeners=new Map(),input={value:'0',addEventListener(k,f){listeners.set('input:'+k,f)}},output={},button={addEventListener(k,f){listeners.set('button:'+k,f)}},root={querySelector(s){return s==='input'?input:s==='output'?output:button},remove(){this.removed=true}};let mutation;globalThis.document={body:{dataset:{view:'map'}},hidden:false,createElement:()=>root,dispatchEvent:e=>events.push(e.detail),addEventListener(k,f){listeners.set('document:'+k,f)},removeEventListener(k){listeners.delete('document:'+k)}};globalThis.MutationObserver=class{constructor(fn){mutation=fn}observe(){}disconnect(){}};globalThis.CustomEvent=class{constructor(type,options){this.type=type;this.detail=options.detail}};
const hour=signal(value),mapHost={append(x){x.host=this}},forecastHost={append(x){x.host=this}};let now=Date.parse('2026-11-01T08:00Z');const setParams=p=>{writes.push(p);hour.value=p.hour};const init=new Function('effect','untracked','hour','parseHour','hourParam','setParams','setTimeout','clearTimeout',source+';return initCoastalClock')(effect,untracked,hour,parseHour,hourParam,setParams,(f,ms)=>{timers.push({f,ms});return timers.length},()=>{});const clock=init({scopeId:'coast:central',mapHost,forecastHost,now:()=>now,onChange:v=>changes.push(v)});t.after(()=>{clock.destroy();Object.assign(globalThis,saved)});return {timers,setNow:v=>now=v,clock,hour,input,output,root,mapHost,forecastHost,events,writes,changes,listeners,mutation};}
test('one clock follows URL hours and moves its same control between Map and Conditions',t=>{const h=fixture(t,'2026-11-01T09:00Z');assert.equal(h.clock.getHour(),Date.parse('2026-11-01T09:00Z')/1000);assert.equal(h.root.host,h.mapHost);document.body.dataset.view='forecast';h.mutation();assert.equal(h.root.host,h.forecastHost);h.hour.value='2026-11-01T10:00Z';assert.equal(h.events.at(-1).regionId,'coast:central');assert.equal(h.clock.getHour(),Date.parse('2026-11-01T10:00Z')/1000);assert.equal(h.writes.length,0);});
test('outside-range shared hours remain selected through unavailable models and only explicit Now resets them',t=>{const h=fixture(t,'2026-12-01T08:00Z');assert.equal(h.input.disabled,true);assert.match(h.output.textContent,/outside this timeline/);assert.equal(h.writes.length,0);assert.equal(h.hour.value,'2026-12-01T08:00Z');h.listeners.get('button:click')();assert.equal(h.hour.value,null);assert.equal(h.input.disabled,false);h.input.value='168';h.listeners.get('input:input')();assert.equal(h.hour.value,'2026-11-08T08:00Z');const count=h.events.length;h.clock.destroy();h.hour.value='2026-11-01T09:00Z';assert.equal(h.events.length,count);});

test('explicit malformed hours publish a gap rather than current readings',t=>{const h=fixture(t,'2026-02-30T12:00Z');for(const bad of ['2026-02-30T12:00Z','','2026-11-01T09:30Z','2026-11-01T09:00-07:00']){h.hour.value=bad;assert.ok(Number.isNaN(h.clock.getHour()));assert.ok(Number.isNaN(h.events.at(-1).epoch));assert.equal(h.input.disabled,true);assert.match(h.output.textContent,/Unsupported UTC hour/);assert.equal(h.hour.value,bad);}assert.equal(h.writes.length,0);});

test('visible Now follows the next UTC boundary without changing the URL',t=>{const h=fixture(t,null);assert.ok(h.timers.at(-1).ms<=3600010);h.setNow(Date.parse('2026-11-01T09:00Z'));h.timers.at(-1).f();assert.equal(h.clock.getHour(),Date.parse('2026-11-01T09:00Z')/1000);assert.equal(h.hour.value,null);assert.equal(h.writes.length,0);});
