import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../dist/coast-conditions.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export function initCoastConditions','function initCoastConditions').replace("await import('../packages/coast/src/coast3d/report.ts')",'await loadReport()');
async function host(initialView='forecast',deferred=null){
 const keys=['document','window','MutationObserver'],saved=Object.fromEntries(keys.map(k=>[k,globalThis[k]]));const events=new Map();const target={value:'surfperch',addEventListener(k,f){events.set('target:'+k,f)},removeEventListener(){}};const root={};const element={attachShadow:()=>root};
 const doc={body:{dataset:{view:initialView}},hidden:false,getElementById:id=>id==='species-select'?target:element,addEventListener(k,f){events.set(k,f)},removeEventListener(){}};let visibility;const win={addEventListener(k,f){events.set(k,f)},removeEventListener(){}};
 Object.assign(globalThis,{document:doc,window:win,MutationObserver:class{constructor(fn){visibility=fn}observe(){}disconnect(){}}});let report;class FakeReport{constructor(options){report=this;this.options=options;this.contexts=[];this.visibility=[]}setContext(c){this.contexts.push(c)}setVisible(v){this.visibility.push(v)}destroy(){}}
 const profile={value:'shore'},selected={point:{latitude:35.4,longitude:-121},localId:'estero-bay'},region={id:'morro-bay',map:{local_areas:[{id:'estero-bay',bounds:[-122,35,-120,36]}]}};
 const factory=new Function('getRegion','profile','effect','loadReport','const stylesURL="/synthetic.css";'+source+';return initCoastConditions;');const init=factory(()=>region,profile,fn=>{fn();return()=>{}},async()=>{if(deferred)await deferred;return {CoastReport:FakeReport}});const result=init({locationUI:{get:()=>selected},weather:{getHour:()=>1791288000}});const flush=async()=>{for(let i=0;i<10;i++)await Promise.resolve()};await flush();return {doc,events,profile,selected,visibility,report:()=>report,flush,cleanup(){result.destroy();Object.assign(globalThis,saved)}};
}
test('Conditions uses canonical location, target, profile and exact shared hour even without model payload',async()=>{const h=await host();try{assert.equal(h.report().options.initialContext.target,'surfperch');assert.equal(h.report().options.initialContext.localId,'estero-bay');h.events.get('skippercast:time')({detail:{regionId:'morro-bay',epoch:1791892800}});assert.equal(h.report().contexts.at(-1).at.getTime(),1791892800000);h.events.get('skippercast:time')({detail:{regionId:'other',epoch:1791896400}});assert.equal(h.report().contexts.at(-1).at.getTime(),1791892800000);h.profile.value='spear';h.events.get('skippercast:species')();assert.equal(h.report().contexts.at(-1).profile,'spear');}finally{h.cleanup()}});
test('delayed Conditions module cannot keep fetching or render as visible after navigation away',async()=>{let release;const pending=new Promise(r=>release=r);const h=await host('forecast',pending);try{h.doc.body.dataset.view='export';release();await h.flush();assert.equal(h.report().visibility.at(-1),false);}finally{h.cleanup()}});
