import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {overviewReportContext} from '../web/overview-context.ts';
const region=JSON.parse(readFileSync(new URL('../dist/regions/morro-bay/region.json',import.meta.url))),point={latitude:35.36,longitude:-120.94},at=new Date('2026-10-07T08:00Z');
test('overview never inherits Morro from bare scope or a nearby unpublished selection',()=>{for(const s of [null,{...point,region:'morro-bay'},{...point,id:'synthetic',region:'constructor'},{...point,id:'synthetic',region:'monterey-point-sur'}])assert.equal(overviewReportContext(point,s,[region],'spear','surfperch',at).regionId,'');});
test('published identity and actual original bounds admit local source context without moving the UTC clock',()=>{const c=overviewReportContext(point,{...point,id:'synthetic-original',region:'morro-bay'},[region],'shore','surfperch',at);assert.equal(c.regionId,'morro-bay');assert.equal(c.at,at);assert.equal(c.point,point);assert.equal(c.profile,'shore');});
test('pan, wrong original region, missing coordinate and bad bounds withdraw local binding',()=>{const s={...point,id:'synthetic-original',region:'morro-bay'};for(const p of [{latitude:36,longitude:-121}, {...point,latitude:NaN}])assert.equal(overviewReportContext(p,s,[region],'boat','lingcod',at).regionId,'');assert.equal(overviewReportContext(point,s,[{...region,fishing_bounds:[0,0,0,0]}],'boat','lingcod',at).regionId,'');});

test('malformed selection and package metadata cannot admit a source or throw',()=>{const s={...point,id:'original',region:'morro-bay'};for(const selection of [{id:'original',region:'morro-bay'},{...s,latitude:NaN},{...s,longitude:Infinity}])assert.equal(overviewReportContext(point,selection,[region],'boat','lingcod',at).regionId,'');for(const fishing_bounds of [undefined,null,{},[]])assert.equal(overviewReportContext(point,s,[{...region,fishing_bounds}],'boat','lingcod',at).regionId,'');});

test('actual overview host rejects a restored foreign waypoint without moving or rebinding its displayed position',()=>{
 const source=readFileSync(new URL('../dist/coastal-discovery.js',import.meta.url),'utf8');const start=source.indexOf('  let selectedHabitat='),end=source.indexOf('  const regionConfigs=',start),positionStart=source.indexOf('  let logicalPoint='),positionEnd=source.indexOf('  function resizeMap',positionStart);const hostSource=source.slice(positionStart,positionEnd)+source.slice(start,end).replace(/  const notifyLocation=.*\n/, '  const notifyLocation=()=>{};\n');
 const make=new Function('p','map',hostSource+';return {locationUI,currentPoint,getSelection:()=>selectedHabitat};');let center={lat:36.6,lng:-121.9};const map={getCenter:()=>center};const h=make({latitude:36.6,longitude:-121.9},map);
 h.locationUI.restore({...point,id:'original',region:'morro-bay'});assert.equal(h.getSelection(),null);assert.deepEqual(h.currentPoint(),{latitude:36.6,longitude:-121.9});assert.equal(overviewReportContext(h.currentPoint(),h.getSelection(),[region],'boat','lingcod',at).regionId,'');assert.deepEqual(center,{lat:36.6,lng:-121.9});
 center={lat:point.latitude+.00003,lng:point.longitude-.0001};h.locationUI.select({...point,id:'original',region:'morro-bay'});assert.deepEqual(h.currentPoint(),point);assert.equal(overviewReportContext(h.currentPoint(),h.getSelection(),[region],'boat','lingcod',at).regionId,'morro-bay');center={lat:point.latitude+.001,lng:point.longitude};assert.notDeepEqual(h.currentPoint(),point);
});
