import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../dist/coastal-selection.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export function initCoastalSelection','function initCoastalSelection');
function fixture(t,resolver){const saved={document:globalThis.document,window:globalThis.window,location:globalThis.location,MutationObserver:globalThis.MutationObserver},events=new Map(),timers=[];let selected=null,clears=0,mutation;
Object.assign(globalThis,{document:{hidden:false,body:{dataset:{view:'forecast'}},addEventListener(k,f){events.set(k,f)},removeEventListener(k){events.delete(k)}},window:{addEventListener(k,f){events.set(k,f)},removeEventListener(k){events.delete(k)}},location:{href:'https://example.test/?coast=central&habitat=original#forecast'},MutationObserver:class{constructor(f){mutation=f}observe(){}disconnect(){}}});
const init=new Function('resolveHabitatSelection','coastTarget','setTimeout','clearTimeout',source+';return initCoastalSelection')(resolver,x=>x,(f,ms)=>{timers.push({f,ms});return timers.length},()=>{});
const handle=init({scopeId:'coast:central',getPoint:()=>({latitude:35.3,longitude:-121}),getTarget:()=> 'lingcod',getProfile:()=> 'boat',getSelection:()=>selected,restore:p=>selected=p,clear:()=>{selected=null;clears++}});t.after(()=>{handle.destroy();Object.assign(globalThis,saved)});return {handle,events,timers,mutation,get selected(){return selected},get clears(){return clears},flush:async()=>{for(let i=0;i<8;i++)await Promise.resolve()}};}
const receipt=()=>({id:'original',latitude:35.3,longitude:-121,region:'morro-bay',expiresAt:new Date(Date.now()+40*86400000).toISOString(),kind:'reef'});
test('fresh Conditions link restores exact admitted source context without graphics and retains expiry while hidden',async t=>{let calls=0;const h=fixture(t,async()=>{calls++;return receipt()});await h.flush();assert.equal(h.selected.id,'original');assert.equal(calls,1);assert.ok(h.timers[0].ms<=2147483647);document.body.dataset.view='map';h.mutation();assert.equal(h.selected.id,'original');assert.equal(calls,1);});
test('delayed shared-link reply cannot restore superseded, hidden or destroyed context',async t=>{let release;const h=fixture(t,()=>new Promise(r=>release=r));document.body.dataset.view='map';h.mutation();release(receipt());await h.flush();assert.equal(h.selected,null);});
test('unpublished identity or differing exact original point remains a gap',async t=>{const h=fixture(t,async()=>({...receipt(),latitude:35.31}));await h.flush();assert.equal(h.selected,null);assert.ok(h.clears>=1);});
