// Strings for the charter fleet's Fleet review and Vessels views (charter-fleet
// design § 13; CF-31). Kept beside the views rather than in web/advisor/copy.ts, the
// Text Advisor's, so the fleet admin tasks built in parallel each keep their own
// copy module. English only, under the copy lint like ADMIN_COPY.
export const FLEET_COPY = {
  views: {'fleet-review': 'Fleet review', 'fleet-vessels': 'Vessels'},
  regionLabel: 'Region',
  regionHint: 'Empty for every region',
  // Fleet review
  reviewHeading: 'Fleet review',
  reviewHelp: 'Registry runs open these when sources disagree or a match is unsure. A decision is final for that candidate: the next run reads it back and asks no more.',
  kindLabel: 'Kind',
  allKinds: 'All kinds',
  kinds: {merge: 'Possible match', mmsi: 'MMSI match', class: 'Vessel class', 'fact-conflict': 'Conflicting facts', change: 'Change',
    vanished: 'Gone from sources', 'advisor-link': 'Advisor boat link', scope: 'Scope'} as Record<string, string>,
  statusLabel: 'Status',
  reviewStatuses: {open: 'Open', decided: 'Decided', dismissed: 'Dismissed', all: 'All'} as Record<string, string>,
  reviewsNone: 'No reviews match.',
  subject: 'Subject',
  subjectItself: 'The subject vessel',
  advisorBoat: (id: string): string => `Advisor boat ${id}`,
  score: 'Score',
  scoreParts: 'Score parts',
  basis: 'Basis',
  candidate: 'Candidate',
  proposal: 'Proposed vessel',
  candidates: 'Proposed vessels',
  chooseVessel: 'Which registry vessel this is',
  openVessel: (name: string): string => `Open ${name}`,
  decisionLabel: 'Decision',
  noteLabel: 'Note (optional)',
  actions: {'same-vessel': 'Same vessel', 'new-vessel': 'New vessel', 'set-mmsi': 'Set MMSI', 'reject-mmsi': 'Wrong MMSI',
    'set-class': 'Set class', 'set-status': 'Set status', confirm: 'Confirm', dismiss: 'Dismiss'} as Record<string, string>,
  markVanished: 'Mark vanished',
  markActive: 'Mark active',
  outOfScope: 'Out of scope',
  decidedAs: (action: string): string => `Decided: ${action}.`,
  repeated: 'Already decided that way; nothing changed.',
  decidedAt: (when: string): string => `Decided ${when}`,
  // Vessels
  vesselsHeading: 'Vessels',
  vesselsCaption: 'Registry vessels by name',
  vesselsNone: 'No vessels match.',
  port: 'Port',
  anyValue: 'Any',
  notClassified: 'Not classified',
  profileLabel: 'Profile',
  aisLabel: 'AIS',
  aisWatched: 'Watched',
  aisUnwatched: 'Not watched',
  completenessLabel: 'Completeness',
  completenessAtMost: (n: number): string => `At most ${n}%`,
  columns: {name: 'Name', port: 'Port', class: 'Class', status: 'Status', profile: 'Profile', complete: 'Complete', ais: 'AIS', reviews: 'Open reviews', pinned: 'Pinned'},
  classes: {'six-pack': 'Six-pack', 'inspected-party': 'Inspected party boat', 'long-range': 'Long-range'} as Record<string, string>,
  vesselStatuses: {active: 'Active', inactive: 'Inactive', sold: 'Sold', excluded: 'Excluded'} as Record<string, string>,
  profileStatuses: {listed: 'Listed', hidden: 'Hidden'} as Record<string, string>,
  mapConsents: {none: 'None', aggregate: 'Aggregate only', named: 'Named'} as Record<string, string>,
  allPinned: 'Every field (pin record unreadable)',
  // Vessel detail
  backToVessels: 'Back to Vessels',
  vesselMissing: 'This vessel no longer exists.',
  publicHeading: 'Public profile',
  publicShown: (slug: string): string => `Public at /boats/${slug} when its facts pass the display rules.`,
  publicHidden: 'Off public pages: the profile is hidden or the vessel is inactive.',
  removalRequested: (when: string): string => `Removal requested ${when}: off public pages, even if the profile is set to listed, until the request is cleared.`,
  recordRemoval: 'Record a removal request',
  recordRemovalHelp: 'Use this when the operator asks for the boat to come down: it hides the profile and keeps the request date.',
  removalRecorded: 'Removal request recorded; the profile is hidden.',
  mapConsentHelp: 'The operator’s consent for this boat on public activity layers.',
  operator: 'Operator',
  region: 'Region',
  lastSeenSource: 'Last listed by a source',
  updated: 'Updated',
  fieldsHeading: 'Resolved fields',
  fieldsCaption: 'Each field with its value, pin and winning fact',
  fieldsHelp: 'Saving a field records an admin fact and pins it, so registry runs leave it alone until you unpin it. The name stays with the resolver, which normalises it.',
  field: 'Field',
  value: 'Value',
  pin: 'Pin',
  winningFact: 'Winning fact',
  pinned: 'Pinned',
  pinnedAt: (when: string): string => `Pinned ${when}`,
  pinnedAll: 'Pinned (pin record unreadable)',
  noFact: 'No matching fact',
  edit: 'Edit',
  editField: (label: string): string => `Edit ${label}`,
  save: 'Save and pin',
  cancel: 'Cancel',
  unpin: 'Unpin',
  unpinField: (label: string): string => `Unpin ${label}`,
  clearValue: 'Empty clears the value.',
  fieldSaved: (label: string): string => `${label} saved and pinned.`,
  fieldUnpinned: (label: string): string => `${label} unpinned; the next registry run may replace it.`,
  fieldLabels: {name: 'Name', name_norm: 'Normalised name', operator_id: 'Operator id', port_id: 'Port', landing_id: 'Landing', vessel_class: 'Class',
    waters_json: 'Waters', uscg_doc: 'USCG documentation number', state_reg: 'State registration', hull_id: 'Hull id', call_sign: 'Call sign', mmsi: 'MMSI',
    year_built: 'Year built', passengers_max: 'Passengers (max)', bunks: 'Bunks', length_ft: 'Length (ft)', beam_ft: 'Beam (ft)', cruise_kn: 'Cruise speed (kn)',
    website: 'Website', booking_url: 'Booking link', booking_platform: 'Booking platform', phone_business: 'Business phone', email_business: 'Business email',
    status: 'Status', profile_status: 'Profile', map_display_consent: 'Map display consent'} as Record<string, string>,
  factsHeading: 'Facts',
  factsCaption: 'Every observed value, current first within each field',
  source: 'Source',
  method: 'Method',
  confidence: 'Confidence',
  rights: 'Rights',
  retrieved: 'Retrieved',
  state: 'State',
  current: 'Current',
  winning: 'Winning',
  superseded: (when: string): string => `Superseded ${when}`,
  adminSource: 'Admin edit',
  offeringsHeading: 'Offerings',
  tripType: 'Trip',
  price: 'Price',
  departs: 'Departs',
  season: 'Season',
  aliasesHeading: 'Aliases',
  alias: 'Alias',
  aliasKind: 'Kind',
  firstSeen: 'First seen',
  lastSeen: 'Last seen',
  changesHeading: 'Changes',
  change: 'Change',
  before: 'Before',
  after: 'After',
  detected: 'Detected',
  watchHeading: 'AIS watch',
  matchMethod: 'Match',
  positions30: 'Positions (30 days)',
  tripsHeading: 'Recent trips',
  date: 'Date',
  distance: 'Distance (nm)',
  fishingMin: 'Fishing (min)',
  advisorBoatsHeading: 'Linked advisor boats',
  openReviewsHeading: 'Open reviews',
  opened: 'Opened',
  noneRecorded: 'None recorded.',
} as const;
