// Security headers for every response the Worker returns, and (via the
// generated dist/client/_headers file) for static assets Cloudflare serves
// without invoking the Worker. One definition, so the two cannot drift.
//
// The Content-Security-Policy lists every origin the app contacts. To add a
// provider, add its origin here and to tests/test_security_headers.mjs, and
// check the pages in a browser (see docs/cloudflare.md).

// Hosts the browser fetches from directly (fetch/XHR and MapLibre tile loads).
export const CONNECT_ORIGINS = [
  'https://api.weather.gov',                  // NWS alerts and station observations (live-conditions.js, marine-data.js)
  'https://api.tidesandcurrents.noaa.gov',    // NOAA CO-OPS tides and water level
  'https://raw.githubusercontent.com',        // region feed URLs not routed through /feeds/ (fallbacks)
  'https://services2.arcgis.com',             // CDFW MPA boundary query (protected-areas.js)
  'https://tile.openstreetmap.org',           // base map tiles (MapLibre fetches tiles)
  'https://gis.charttools.noaa.gov',          // NOAA ENC chart WMS
];
// Hosts that serve map tile images (Leaflet loads tiles as <img>).
export const IMAGE_ORIGINS = ['https://tile.openstreetmap.org', 'https://gis.charttools.noaa.gov'];

export const CSP = [
  "default-src 'self'",
  "script-src 'self'",
  // Inline style *attributes* are used throughout the rendered UI (and by
  // Leaflet/MapLibre markup); no <style> elements are injected. CSP3 browsers
  // apply the narrower -elem/-attr directives; older ones fall back to style-src.
  "style-src 'self' 'unsafe-inline'",
  "style-src-elem 'self'",
  "style-src-attr 'unsafe-inline'",
  `img-src 'self' data: blob: ${IMAGE_ORIGINS.join(' ')}`,
  `connect-src 'self' ${CONNECT_ORIGINS.join(' ')}`,
  "worker-src 'self'",
  "font-src 'self'",
  "manifest-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'none'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

export const SECURITY_HEADERS = {
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'Content-Security-Policy': CSP,
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'geolocation=(self), camera=(), microphone=(), payment=(), usb=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
};

/** The response with the security headers set (copied when its headers are immutable). */
export function secure(response) {
  if (!(response instanceof Response)) return response;
  let out = response;
  try { for (const [k, v] of Object.entries(SECURITY_HEADERS)) out.headers.set(k, v); return out; }
  catch { out = new Response(response.body, response); }
  for (const [k, v] of Object.entries(SECURITY_HEADERS)) out.headers.set(k, v);
  return out;
}

/** Cloudflare static-assets `_headers` file applying the same headers to every asset. */
export function headersFile() {
  return '# Generated by scripts/build-worker.mjs from server/security-headers.js. Do not edit.\n/*\n'
    + Object.entries(SECURITY_HEADERS).map(([k, v]) => `  ${k}: ${v}\n`).join('');
}
