"""Landing-report ports come from configuration and parse exactly as the hard-coded version did."""
import json
import unittest

from skippercast.pipeline import parsers
from skippercast.pipeline.settings import settings
from skippercast.platform.contracts import REPO, load_catalogs
from tests._support import FIXTURES

FIXTURE = FIXTURES / 'charter-reports'
URL = 'https://www.socalfishreports.com/dock_totals/boats.php?date=2026-09-20'


class CharterPortTests(unittest.TestCase):
    def test_configured_ports_equal_the_previous_constants(self):
        # Previously hard-coded in parsers.charter_reports: these labels, this order, these names.
        self.assertEqual(list(settings('morro-bay')['report_ports'].items()),
                         [('Morro Bay, CA', 'Morro Bay'), ('Avila Beach, CA', 'Avila Beach')])

    def test_every_region_with_landings_reads_the_same_ports(self):
        # Behaviour is preserved for every region, including those that currently
        # receive Morro Bay/Avila rows (flagged for review in P2-08).
        ports = load_catalogs()[1]['landing-reports']['report_ports']
        for path in sorted((REPO / 'regions').glob('*/region.json')):
            with self.subTest(region=path.parent.name):
                self.assertEqual(settings(path.parent.name)['report_ports'], ports)

    def test_output_matches_the_hard_coded_parser_byte_for_byte(self):
        # Expected output was produced by the pre-change parser from the same page: other
        # landings skipped, a row naming both landings takes Morro Bay, duplicates dropped.
        page = (FIXTURE / 'dock-totals-2026-09-20.html').read_text()
        expected = json.loads((FIXTURE / 'dock-totals-2026-09-20.expected.json').read_text())
        result = parsers.charter_reports(page, '2026-09-20', URL, ports=settings('morro-bay')['report_ports'])
        self.assertEqual(json.loads(json.dumps(result)), expected)
        self.assertEqual([(r['boat'], r['port']) for r in result['reports']],
                         [('Example Boat', 'Morro Bay'), ('Other Boat', 'Avila Beach'),
                          ('Twin Port Boat', 'Morro Bay'), ('Example Boat', 'Morro Bay')])

    def test_ports_are_parameters_not_constants(self):
        page = (FIXTURE / 'dock-totals-2026-09-20.html').read_text()
        rows = parsers.charter_reports(page, '2026-09-20', URL, ports={'Crescent City, CA': 'Crescent City'})['reports']
        self.assertEqual([(r['boat'], r['port']) for r in rows], [('North Boat', 'Crescent City')])
        with self.assertRaises(ValueError):
            parsers.charter_reports(page, '2026-09-20', URL, ports={})
        self.assertNotIn('Morro Bay, CA', (REPO / 'src/skippercast/pipeline/parsers.py').read_text())


class RegionDefaultTests(unittest.TestCase):
    def test_build_uses_the_single_default_constant(self):
        from skippercast.platform.contracts import DEFAULT_REGION
        index = json.loads((REPO / 'dist/regions/index.json').read_text())
        self.assertEqual(index['default_region'], DEFAULT_REGION)
        self.assertEqual((REPO / 'dist/region-default.js').read_text().split('\n', 1)[0],
                         f'// Generated by skippercast.platform.build; edit regions/{DEFAULT_REGION}/region.json.')
        self.assertNotIn('"morro-bay"', (REPO / 'src/skippercast/platform/build.py').read_text())

    def test_dead_buoy_constant_is_gone(self):
        from skippercast.pipeline import live
        self.assertFalse(hasattr(live, 'BUOYS'))


if __name__ == '__main__':
    unittest.main()
