import type {County} from './types.ts';
export const slo:County={
 id:'slo', name:'San Luis Obispo County',shortName:'SLO County',brand:'SLO Fish Report',brandPrefix:'SLO',defaultAreaId:'central',temperatureStationId:'46215',domain:'slofishreport.com',timezone:'America/Los_Angeles',center:[-120.95,35.32],bounds:[[-121.34,34.92],[-120.51,35.82]],marineBounds:[[-121.65,35.04],[-120.80,35.67]],
 tideStation:{id:'9412110',name:'Port San Luis',url:'https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=9412110',note:'Port San Luis reference · MLLW. Morro Bay tide and entrance currents can differ.'},
 buoys:[{id:'46215',name:'Diablo Canyon',lat:35.204,lon:-120.859,note:'Local offshore waves and sea temperature. No wind observations.'},{id:'46028',name:'Cape San Martin',lat:35.77,lon:-121.903,note:'Offshore wind and waves; exposure differs from the nearshore coast.'}],
 areas:[
 {id:'north',name:'Cambria & San Simeon',coast:'North coast',mapLabel:'San Simeon / Cambria',lat:35.63,lon:-121.20,landLat:35.57,landLon:-121.10,modes:['boat','shore','spear'],exposure:'Exposed northwest coastline',accessNote:'Check beach access, swell at entry, and a clear exit before entering the water.',targets:{boat:['Rockfish','Lingcod'],shore:['Surfperch'],spear:['Rockfish','Lingcod']},forecastZone:'PZZ645',waterQualityUrl:'https://www.slocounty.ca.gov/departments/slo-health/public-health/environmental-health-services/all-environmental-health-services/recreational-health/beach-water-quality-monitoring'},
 {id:'central',name:'Morro Bay & Point Estero',coast:'Central coast',mapLabel:'Morro Bay',lat:35.35,lon:-120.95,landLat:35.365,landLon:-120.85,modes:['boat','shore','spear'],exposure:'Harbor entrance and exposed open coast',accessNote:'Offshore conditions do not establish Morro Bay bar conditions. Check the harbor and entrance separately.',targets:{boat:['Rockfish','Lingcod'],shore:['Surfperch','California halibut'],spear:['Rockfish','Lingcod']},forecastZone:'PZZ645',waterQualityUrl:'https://www.slocounty.ca.gov/departments/slo-health/public-health/environmental-health-services/all-environmental-health-services/recreational-health/beach-water-quality-monitoring'},
 {id:'south',name:'Avila Beach & Pismo',coast:'South coast',mapLabel:'Avila / Pismo',lat:35.16,lon:-120.78,landLat:35.17,landLon:-120.74,modes:['boat','shore','spear'],exposure:'Sheltered coves and exposed sandy beaches',accessNote:'Avila shelter does not represent Pismo surf. Conditions at the exact beach remain unverified.',targets:{boat:['Rockfish','Lingcod','California halibut'],shore:['Surfperch','California halibut'],spear:['Rockfish','California halibut']},forecastZone:'PZZ645',waterQualityUrl:'https://www.slocounty.ca.gov/departments/slo-health/public-health/environmental-health-services/all-environmental-health-services/recreational-health/beach-water-quality-monitoring'}],
 ruleLinks:[{label:'Current Central Coast fishing rules',url:'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Fishing-Map/Central'},{label:'In-season changes',url:'https://wildlife.ca.gov/Fishing/Ocean/Regulations/Inseason'},{label:'Marine protected areas',url:'https://wildlife.ca.gov/Conservation/Marine/MPAs'},{label:'Morro Bay harbor information',url:'https://www.morrobayca.gov/144/Harbor'},{label:'Beach water quality',url:'https://www.slocounty.ca.gov/departments/slo-health/public-health/environmental-health-services/all-environmental-health-services/recreational-health/beach-water-quality-monitoring'}],
 catchLinks:[{label:'Local boat fish counts',url:'https://www.socalfishreports.com/dock_totals/boats.php'},{label:"Virg’s Landing",url:'https://www.virgslanding.com/'},{label:'Morro Bay Landing',url:'https://www.morrobaylanding.com/'},{label:'Patriot Sportfishing',url:'https://www.patriotsportfishing.com/'}]
};
export const counties:Record<string,County>={slo};
// New counties require reviewed stations, actual forecast points, method rules and access records.
export const hostCounties:Record<string,string>={'slofishreport.com':'slo','www.slofishreport.com':'slo'};
