import type {County,Area,Report,Mode,ForecastHour} from './types.ts';
import {availableDays,buildDaily,dateKey,type DailyBrief} from './daily.ts';
import type {NearshoreSite} from './enrichment-types.ts';
export const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const n=(v:number|null|undefined,d=0)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'—';
export const clock=(at:string,tz='America/Los_Angeles',options:Intl.DateTimeFormatOptions={hour:'numeric',minute:'2-digit'})=>Number.isFinite(Date.parse(at))?new Intl.DateTimeFormat('en-US',{timeZone:tz,...options}).format(new Date(at)):'Unavailable';
export const modeNames:Record<Mode,string>={boat:'Boat fishing',shore:'Shore fishing',spear:'Spearfishing'};
export const symbols:Record<string,string>={boat:'<path d="M3 16l3 4h12l3-4-9-4-9 4ZM6 14V8h12v6M12 8V4M3 22c2-2 4 2 6 0s4 2 6 0 4 2 6 0"/>',shore:'<path d="M3 19c3-3 5 3 8 0s5 3 10 0M4 10h16M12 3v7M6 4l2 2m10-2-2 2M12 13v3"/>',spear:'<path d="M3 10h18l-2 7h-5l-2-3-2 3H5l-2-7ZM21 10V4h-4M7 10V7m10 3V7"/>',wind:'<path d="M3 8h11c5 0 5-6 1-6M3 12h15c5 0 5 7 1 7M3 16h7"/>',wave:'<path d="M2 9c3-3 4 3 7 0s4 3 7 0 4 3 6 0M2 15c3-3 4 3 7 0s4 3 7 0 4 3 6 0"/>',tide:'<path d="M3 19h18M3 15h18M8 10V3m-3 3 3-3 3 3M17 3v7m-3-3 3 3 3-3"/>',temp:'<path d="M9 15V5a3 3 0 0 1 6 0v10a5 5 0 1 1-6 0ZM12 7v11"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',pin:'<path d="M19 10c0 6-7 11-7 11S5 16 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',layers:'<path d="m12 3 10 6-10 6L2 9l10-6ZM2 14l10 6 10-6M2 19l10 6 10-6"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',arrow:'<path d="m9 5 7 7-7 7"/>',check:'<path d="m5 12 4 4L19 6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',source:'<circle cx="12" cy="12" r="9"/><path d="M12 10v7M12 7h.01"/>'};
export const icon=(id:string)=>`<svg class="icon" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${symbols[id]??symbols.wave}</svg>`;
const range=(v:{min:number|null;max:number|null},d=0)=>v.min===null?'—':v.min===v.max?n(v.min,d):`${n(v.min,d)}–${n(v.max,d)}`;
export function freshNearshore(report:Report,areaId:string,now:Date){return (report.nearshore??[]).filter(s=>{const issue=s.issuedAt?now.getTime()-Date.parse(s.issuedAt):NaN,fetchAge=now.getTime()-Date.parse(s.fetchedAt);return s.areaId===areaId&&s.availability==='available'&&s.freshness==='current'&&issue>=-300000&&issue<48*3600000&&fetchAge>=-300000&&fetchAge<3*3600000;});}
export function nearshoreAt(site:NearshoreSite,at:string){const time=Date.parse(at);return site.hours.filter(h=>Math.abs(Date.parse(h.at)-time)<=1.5*3600000).sort((a,b)=>Math.abs(Date.parse(a.at)-time)-Math.abs(Date.parse(b.at)-time))[0];}
export function selectedHour(brief:DailyBrief,at?:string):ForecastHour|undefined{return brief.hours.find(h=>h.at===at)??brief.hours[0];}
function spark(points:{at:string;v:number|null|undefined}[],color:string){
 const valid=points.filter(p=>typeof p.v==='number'&&Number.isFinite(p.v));if(valid.length<2)return '<span class="spark-gap">No series</span>';
 const min=Math.min(...valid.map(p=>p.v!)),max=Math.max(...valid.map(p=>p.v!)),first=Date.parse(points[0].at),last=Date.parse(points.at(-1)!.at);let move=true;
 const path=points.map(p=>{if(p.v===null||p.v===undefined||!Number.isFinite(p.v)){move=true;return '';}const cmd=move?'M':'L';move=false;return `${cmd}${((Date.parse(p.at)-first)/(last-first||1)*100).toFixed(1)},${(26-(p.v-min)/(max-min||1)*19).toFixed(1)}`;}).join(' ');
 return `<svg class="spark" viewBox="0 0 100 30" aria-hidden="true"><path d="${path}" stroke="${color}" stroke-width="1.8" fill="none" vector-effect="non-scaling-stroke"/></svg>`;
}
export function dayStrip(report:Report,county:County,area:Area,mode:Mode,selected:string,now:Date){
 return availableDays(report,county,area,now).map(day=>{const b=buildDaily(report,county,area,mode,day.date,now);return `<button class="day-card ${day.date===selected?'selected':''}" type="button" data-day="${day.date}" aria-pressed="${day.date===selected}"><span class="day-card-top"><b>${day.label}</b><span>${clock(day.date+'T20:00:00Z',county.timezone,{month:'short',day:'numeric'})}</span></span><span class="day-card-values">${icon('wave')}<strong>${range(b.seas,1)} <small>ft</small></strong><span>${range(b.wind)} kt</span></span><span class="day-card-note"><i class="status-dot ${b.status.toLowerCase()}"></i>${day.provisional?'Provisional outlook':b.status==='Unknown'?'Local checks needed':b.windows.length?'Lighter periods available':'Read the conditions'}</span></button>`;}).join('');
}
function metric(label:string,value:string,unit:string,note:string,symbol:string,series='',type='Forecast'){
 return `<article class="daily-metric"><div class="metric-top">${icon(symbol)}<span>${label}</span></div><div class="metric-value">${value}<small>${unit}</small></div><div class="metric-bottom"><span>${esc(note)}</span>${series}</div><span class="data-kind">${esc(type)}</span></article>`;
}
export function trendChart(b:DailyBrief,county:County,at?:string){
 const start=Date.parse(b.hours[0]?.at??b.tides[0]?.at??b.date+'T20:00:00Z'),end=b.hours.length?Date.parse(b.hours.at(-1)!.at)+3600000:Date.parse(b.tides.at(-1)?.at??b.date+'T23:00:00Z')+360000;
 const x=(time:string)=>88+(Date.parse(time)-start)/(end-start||1)*874;
 const lines=[{label:'Wind',unit:'kt',color:'#147a83',points:b.hours.map(h=>({at:h.at,v:h.windKnots})),offset:36},{label:'Seas',unit:'ft',color:'#338bab',points:b.hours.map(h=>({at:h.at,v:h.waveFt})),offset:111},{label:'Tide',unit:'ft MLLW',color:'#b68648',points:b.tides.filter(p=>Date.parse(p.at)>=start&&Date.parse(p.at)<=end).map(h=>({at:h.at,v:h.heightFt})),offset:186}];
 let svg=lines.map(row=>{const vals=row.points.map(p=>p.v).filter((v):v is number=>typeof v==='number'&&Number.isFinite(v)),min=Math.min(0,...vals),max=Math.max(row.label==='Wind'?10:row.label==='Seas'?3:1,...vals)*1.15;let move=true;const path=row.points.map(p=>{if(p.v===null||!Number.isFinite(p.v)){move=true;return '';}const cmd=move?'M':'L';move=false;return `${cmd}${x(p.at).toFixed(2)},${(row.offset+38-(p.v-min)/(max-min||1)*38).toFixed(2)}`;}).join(' ');return `<text class="plot-label" x="0" y="${row.offset+16}">${row.label}</text><text class="plot-unit" x="0" y="${row.offset+34}">${row.unit}</text><line x1="88" x2="962" y1="${row.offset+39}" y2="${row.offset+39}" stroke="#d9e5e5" stroke-dasharray="3 4"/>${vals.length?`<path d="${path}" stroke="${row.color}" stroke-width="2.5" fill="none"/>`:`<text x="470" y="${row.offset+23}" text-anchor="middle" class="plot-unit">No fresh series</text>`}<text x="980" y="${row.offset+9}" class="plot-unit">${n(max,0)}</text>`;}).join('');
 svg=b.windows.map(w=>`<rect x="${Math.max(88,x(w.start))}" y="24" width="${Math.max(0,Math.min(962,x(w.end))-Math.max(88,x(w.start)))}" height="204" fill="#38a490" opacity=".07"/>`).join('')+svg;
 svg+=[0,.25,.5,.75,1].map(t=>`<text x="${88+t*874}" y="258" text-anchor="middle" class="plot-time">${clock(new Date(start+t*(end-start)).toISOString(),county.timezone,{hour:'numeric'})}</text>`).join('');
 const pointer=x(at??b.hours[0]?.at??new Date(start).toISOString());svg+=`<line x1="${pointer}" x2="${pointer}" y1="20" y2="230" stroke="#183e4d" stroke-opacity=".45" stroke-dasharray="4 4"/><circle cx="${pointer}" cy="19" r="4" fill="#183e4d"/>`;
 return `<svg class="conditions-chart" viewBox="0 0 1010 273" role="img" aria-label="Wind in knots, offshore significant wave height in feet, and ${esc(county.tideStation.name)} tide prediction in feet above MLLW. Each row has its own scale. Missing samples remain gaps.">${svg}</svg>`;
}
export function hourReadout(report:Report,county:County,area:Area,b:DailyBrief,at?:string,now=new Date()){
 const hour=selectedHour(b,at);if(!hour)return '<div class="hour-focus empty-state">No fresh hourly forecast is available for this date.</div>';
 const tide=b.tides.find(p=>Math.abs(Date.parse(p.at)-Date.parse(hour.at))<=4*60000),site=freshNearshore(report,area.id,now)[0],near=site?nearshoreAt(site,hour.at):undefined;
 return `<div class="hour-focus"><span class="hour-time">${icon('sun')}<strong>${clock(hour.at,county.timezone,{weekday:'short',hour:'numeric',timeZoneName:'short'})}</strong><span>Forecast hour</span></span><div><b>${n(hour.windKnots)}<small> kt</small></b><span>wind · ${n(hour.gustKnots)} kt gust</span></div><div><b>${n(hour.waveFt,1)}<small> ft</small></b><span>offshore · ${n(hour.wavePeriodS)} sec</span></div><div><b>${n(near?.waveFt,1)}<small> ft</small></b><span>${esc(site?.name??'nearshore unavailable')} · 3h sample</span></div><div><b>${n(tide?.heightFt,1)}<small> ft</small></b><span>${esc(county.tideStation.name)} · MLLW</span></div></div>`;
}
export function reportPanel(report:Report,county:County,area:Area,mode:Mode,date:string,now:Date,at?:string){
 const b=buildDaily(report,county,area,mode,date,now),current=date===dateKey(now,county.timezone),site=freshNearshore(report,area.id,now)[0];
 const waves=site?.hours.filter(h=>dateKey(h.at,county.timezone)===date&&Date.parse(h.at)>=now.getTime()-3*3600000).map(h=>h.waveFt).filter((v):v is number=>v!==null)??[];
 const near=waves.length?{min:Math.min(...waves),max:Math.max(...waves)}:{min:null,max:null};
 const window=b.windows[0],temp=b.tempObservation,beaches=(report.waterQuality??[]).filter(s=>s.areaId===area.id),beachFresh=beaches.length&&report.sources.some(s=>s.id==='slo-beach-water-quality'&&s.outcome==='ok'&&now.getTime()-Date.parse(s.fetchedAt)<3*3600000);
 const advisories=beachFresh?beaches.filter(s=>/advisory|closed|warning/i.test(s.status)):[];
 const exposureHeadline=b.alerts.length?b.alerts[0].event:!b.hours.length?'Fresh conditions are unavailable.':mode==='spear'?'Read the swell. Confirm the visibility.':b.seas.max!==null&&b.seas.max>4?'Some swell. Choose your water carefully.':b.wind.max!==null&&b.wind.max>=12?'Watch the wind before your return.':window?'A lighter stretch. A little local knowledge.':'Know the water before you head out.';
 return `<section class="daily-brief" aria-label="Selected day's fishing briefing"><div class="brief-heading"><div><span class="eyebrow">${esc(b.label.toUpperCase())}’S FISHING BRIEFING <span class="heading-sep">/</span> ${esc(area.name)}</span><h2>${esc(exposureHeadline)}</h2><p>${esc(b.summary)}</p></div><aside class="brief-window"><span class="eyebrow">BEST CONDITIONS WINDOW</span><strong>${window?clock(window.start,county.timezone)+' – '+clock(window.end,county.timezone):'No window qualified'}</strong><p>${window?'Lower wind & offshore seas. Local checks required.':'Fresh data and local conditions need a closer look.'}</p><span class="window-footnote">Bite timing · unverified ${icon('source')}</span></aside></div>
 <div class="brief-signal"><span class="status-tag ${b.status.toLowerCase()}"><i></i>${b.status==='Mixed'?'LOCAL CHECKS NEEDED':b.status==='Caution'?'CONDITIONS TO WATCH':'LIMITED LOCAL CONFIDENCE'}</span><span>${esc(b.confidence)}</span>${advisories.length?`<a class="health-notice" href="${esc(advisories[0].url)}" target="_blank" rel="noopener">${advisories.length} beach health advisory · check before water contact</a>`:''}</div>
 <div class="daily-metrics">${metric('Wind',range(b.wind),'kt',`Gusts to ${n(b.wind.gust)} kt`,'wind',spark(b.hours.map(h=>({at:h.at,v:h.windKnots})),'#18848d'))}${metric('Offshore seas',range(b.seas,1),'ft',`Period up to ${n(b.seas.period)} sec`,'wave',spark(b.hours.map(h=>({at:h.at,v:h.waveFt})),'#3b88ac'))}${metric('Nearshore waves',range(near,1),'ft',site?.name??'No fresh site model','wave',site?spark(site.hours.filter(h=>dateKey(h.at,county.timezone)===date).map(h=>({at:h.at,v:h.waveFt})),'#437b87'):'','3-hour model')}${metric('Sea temperature',n(temp?.waterTempF,1),'°F',temp?'Buoy · '+clock(temp.observedAt,county.timezone):current?'Fresh buoy data unavailable':'Future SST not forecast','temp','','Observed')}${metric('Tide range',range(b.tideRange,1),'ft',county.tideStation.name+' · MLLW','tide',spark(b.tides.map(t=>({at:t.at,v:t.heightFt})),'#b58c54'),'Predicted')}${metric(mode==='spear'?'Visibility':'Daylight',mode==='spear'?'Unknown':b.sunrise&&b.sunset?n((Date.parse(b.sunset)-Date.parse(b.sunrise))/3600000,1):'—',mode==='spear'?'':'hr',mode==='spear'?'Get a local in-water check':`${b.sunrise?clock(b.sunrise,county.timezone):'—'} – ${b.sunset?clock(b.sunset,county.timezone):'—'}`,mode==='spear'?'eye':'sun','',mode==='spear'?'Local check':'Astronomy')}</div>
 <section class="forecast-navigation"><div class="section-topline"><span class="eyebrow">YOUR NEXT THREE DAYS</span><span>Slide through the outlook ${icon('arrow')}</span></div><div class="day-track" id="day-track" aria-label="Choose forecast day">${dayStrip(report,county,area,mode,date,now)}</div></section>
 <div class="chart-heading"><div><span class="eyebrow">THE DAY, HOUR BY HOUR</span><h3>See the conditions move together.</h3></div><span class="chart-legend"><i class="wind"></i>Wind <i class="seas"></i>Seas <i class="tides"></i>Tide <i class="window"></i>Conditions window</span></div><div class="conditions-chart-scroll">${trendChart(b,county,at)}</div>${hourReadout(report,county,area,b,at,now)}
 <div class="brief-details"><span>${icon('sun')} ${b.sunrise?'Sunrise '+clock(b.sunrise,county.timezone):'Sunrise unavailable'}</span><span>${b.sunset?'Sunset '+clock(b.sunset,county.timezone):'Sunset unavailable'}</span><span><i class="moon-mark"></i>${esc(b.moon.label)} · ${n(b.moon.fraction===null?null:b.moon.fraction*100)}% illuminated</span><span>${b.rainPct===null?'Rain probability unavailable':n(b.rainPct)+'% rain'} · ${range(b.air)}°F air</span></div>
 <div class="tide-detail">${b.tideEvents.map(t=>`<span><i class="${t.type==='H'?'high':'low'}"></i>${t.type==='H'?'High':'Low'} <b>${clock(t.at,county.timezone)}</b> ${n(t.heightFt,1)} ft</span>`).join('')}<small>High or low tide does not identify slack current.</small></div>
 <details class="confidence-details"><summary>What this briefing knows—and what still needs a local check</summary><ul>${b.missing.map(m=>`<li>${esc(m)}</li>`).join('')}<li>Catch probability has not been modeled. Underwater visibility is unknown without a local observation.</li><li>${esc(county.tideStation.note)}</li><li>Surface temperature does not measure bottom temperature.</li></ul><a href="/methodology">Read the methodology</a></details></section>`;
}
