#!/usr/bin/env node
// The landing's static shoreline (FE-07, docs/plans/front-end/design.md § 7):
// projects catalog/shoreline/<region>.geojson (NOAA NGS CUSP, display extract
// with its provenance) into one SVG path for web/landing/Shoreline.tsx and
// writes web/landing/shoreline-path.ts. Only mean-high-water and built
// shoreline lines are drawn (no ponds or marsh edges); each line is
// simplified to about half a viewBox unit, under a pixel at desktop width.
//
//   node scripts/build_landing_shoreline.mjs           write
//   node scripts/build_landing_shoreline.mjs --check   fail when the committed file differs
//
// FE-10 replaces the catalog extract with the full CUSP import; rerun this
// script then. tests/test_landing_shoreline.mjs runs the check.
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
export const REGION = 'morro-bay';
/** [west, south, east, north]: the shore plus open water to the west, where the headline sits. */
export const FRAME = [-121.9, 34.9, -120.55, 35.85];
export const WIDTH = 1000;
const TOLERANCE = 0.5;
const DRAWN = /^(Natural\.Mean High Water|Man-made|Jetty|Breakwater)/;

/** Equirectangular at the frame's middle latitude, scaled to WIDTH: [x, y] in viewBox units. */
export function projector([west, south, east, north] = FRAME, width = WIDTH) {
  const k = width / ((east - west) * Math.cos(((south + north) / 2) * Math.PI / 180));
  const scaleX = k * Math.cos(((south + north) / 2) * Math.PI / 180);
  return {height: Math.round((north - south) * k), project: ([lon, lat]) => [(lon - west) * scaleX, (north - lat) * k]};
}

/** Douglas-Peucker over projected points. */
export function simplify(points, tolerance = TOLERANCE) {
  if (points.length < 3) return points;
  const keep = new Uint8Array(points.length);
  keep[0] = keep[points.length - 1] = 1;
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = points[a], [bx, by] = points[b];
    const dx = bx - ax, dy = by - ay, length = Math.hypot(dx, dy);
    let worst = -1, index = -1;
    for (let i = a + 1; i < b; i++) {
      const [px, py] = points[i];
      const d = length ? Math.abs(dy * px - dx * py + bx * ay - by * ax) / length : Math.hypot(px - ax, py - ay);
      if (d > worst) { worst = d; index = i; }
    }
    if (worst > tolerance) { keep[index] = 1; stack.push([a, index], [index, b]); }
  }
  return points.filter((_, i) => keep[i]);
}

const fixed = n => String(Math.round(n * 10) / 10);

/** The module text for `geojson`: viewBox, one path, the attribution and the source dates. */
export function shorelineModule(geojson) {
  const {height, project} = projector();
  const parts = [];
  const dates = new Set();
  for (const feature of geojson.features) {
    if (!DRAWN.test(feature.properties?.ATTRIBUTE ?? '')) continue;
    dates.add(String(feature.properties.SRC_DATE).slice(0, 4));
    const lines = feature.geometry.type === 'MultiLineString' ? feature.geometry.coordinates : [feature.geometry.coordinates];
    for (const line of lines) {
      const points = simplify(line.map(project));
      // Fragments under a unit long (pier stubs, tile seams) draw as specks at landing scale.
      if (points.length < 2 || points.slice(1).reduce((n, q, i) => n + Math.hypot(q[0] - points[i][0], q[1] - points[i][1]), 0) < 1) continue;
      let [px, py] = points[0].map(n => Math.round(n * 10) / 10);
      let d = `M${fixed(px)} ${fixed(py)}`;
      for (const [x, y] of points.slice(1)) {
        const [rx, ry] = [Math.round(x * 10) / 10, Math.round(y * 10) / 10];
        if (rx === px && ry === py) continue;
        d += `l${fixed(rx - px)} ${fixed(ry - py)}`;
        [px, py] = [rx, ry];
      }
      if (d.includes('l')) parts.push(d);
    }
  }
  const p = geojson.provenance;
  return `// Generated by scripts/build_landing_shoreline.mjs from catalog/shoreline/${REGION}.geojson; do not edit.
// ${p.source} (${p.license}); display geometry for the landing outline only.
export const SHORELINE = {
  region: '${REGION}',
  viewBox: '0 0 ${WIDTH} ${height}',
  attribution: ${JSON.stringify(p.attribution)},
  sourceYears: ${JSON.stringify([...dates].sort())},
  d: '${parts.join('')}',
} as const;
`;
}

const OUT = `${ROOT}web/landing/shoreline-path.ts`;
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const text = shorelineModule(JSON.parse(readFileSync(`${ROOT}catalog/shoreline/${REGION}.geojson`, 'utf8')));
  if (process.argv.includes('--check')) {
    let committed = '';
    try { committed = readFileSync(OUT, 'utf8'); } catch { /* missing */ }
    if (committed !== text) { console.error('web/landing/shoreline-path.ts is out of date: run node scripts/build_landing_shoreline.mjs'); process.exit(1); }
    console.log('Landing shoreline is current.');
  } else {
    writeFileSync(OUT, text);
    console.log(`Wrote web/landing/shoreline-path.ts (${text.length} bytes).`);
  }
}
