import {matchingHour,plannerURL} from "../links.ts";
import {coastFetch} from '../transport.ts';
import {slo} from '../counties.ts';
import type {Report,Mode} from '../types.ts';
import type {SpeciesId} from '../habitat-types.ts';
import type {HistoryBundle,HistoryMetric} from '../history-types.ts';
import {createState,daily,defaultSpecies,forecastHour,localWave,quietestHours,selectedArea,type AppState} from '../state/experience.ts';
import {availableDays} from '../daily.ts';
import {briefing,conditions,sourceSheet,tideAt,timeSpan} from '../ui/briefing.ts';
import {catchSheet} from '../ui/catches.ts';
import {historyView,type HistorySelection} from '../ui/history.ts';
import {escapeHTML as esc,time,value,ageLabel} from '../ui/format.ts';
const placeAreas:Record<string,string>={morro:'central',cambria:'north',avila:'south'};
export function forecastAreaForPlace(place:string):string|null{return placeAreas[place]??null;}
const $=<T=HTMLElement>(id:string)=>document.getElementById(id) as T;
const tabs=['Overview','Forecast & tides','Buoys','History','Fleet reports','Sources'] as const;
/** Method-specific summary; original observation and forecast clocks remain distinct. */
export function methodMetrics(s:AppState):string{
 const b=daily(s),h=forecastHour(s),tide=tideAt(s),wave=localWave(s),window=quietestHours(s);
 const metric=(label:string,reading:string,note='',cls='')=>`<div class="${cls}"><span>${esc(label)}</span><b>${reading}</b>${note?`<small>${esc(note)}</small>`:''}</div>`;
 const wind=metric('Wind / gust · forecast',`${value(h?.windKnots)} / ${value(h?.gustKnots)} <small>kt</small>`);
 const seas=metric('Seas / period · forecast',`${value(h?.waveFt,1)} <small>ft</small> · ${value(h?.wavePeriodS)} <small>s</small>`);
 const tideMetric=metric('Tide · Port San Luis',`${value(tide.point?.heightFt,1)} <small>ft MLLW</small>`,s.mode==='shore'?tide.trend:'',s.mode==='spear'?'dive-tide-metric':'');
 const water=metric('Latest buoy · observed',`${value(b.tempObservation?.waterTempF,1)} <small>°F</small>`,b.tempObservation?time(b.tempObservation.observedAt,slo.timezone,{hour:'numeric',minute:'2-digit'}):'No fresh temperature',s.mode==='spear'?'dive-water-metric':'water-metric');
 const planning=metric('Planning window',window?timeSpan(s,window.start,window.end):'No qualified window',window?.qualified?'Wind + seas screening':'Not a bite prediction','window-metric');
 if(s.mode==='boat')return wind+seas+tideMetric+water+planning;
 const nearshore=metric('Nearshore swell · model',`${value(wave?.hour?.waveFt,1)} <small>ft</small> · ${value(wave?.hour?.periodS)} <small>s</small>`,wave?.site.name??'No local model');
 if(s.mode==='shore')return tideMetric+nearshore+wind+metric('Beach & access checks','Local check','Open full conditions','water-metric')+planning;
 const v=s.report.visibility,age=v.observedAt?s.now.getTime()-Date.parse(v.observedAt):Infinity;
 const fresh=v.status==='observed'&&Number.isFinite(v.feet)&&age>=-300000&&age<=3*3600000;
 return metric('In-water visibility',fresh?`${value(v.feet)} <small>ft</small>`:'Unknown',fresh?time(v.observedAt!,slo.timezone,{month:'short',day:'numeric',hour:'numeric'}):'Needs a dated dive report')+water+nearshore+tideMetric+planning;
}
export class CoastReport{
 private state:AppState|null=null;private place='morro';private history:HistoryBundle|null=null;private tab=0;private timer=0;private clockTimer=0;private alive=true;private generation=0;
 private selection:HistorySelection={station:slo.temperatureStationId,metric:'waterTempF',days:14};
 private shadow:ShadowRoot;
 constructor(){
  const params=new URLSearchParams(location.search);this.place=params.get('place')??({north:'cambria',south:'avila'}[params.get('area')??'']??'morro');
  this.shadow=$('report-content').attachShadow({mode:'open'});
  $('daily-report-open').onclick=()=>this.open();$('report-close').onclick=()=>$<HTMLDialogElement>('report-dialog').close();
  window.addEventListener('coast-place-change',this.onPlace);window.addEventListener('coast-home-change',this.onHome);$('species').addEventListener('change',this.onSpecies);
  $('report-bar').addEventListener('click',this.onBarClick);$('report-bar').addEventListener('change',this.onBarChange);$('report-bar').addEventListener('input',this.onBarInput);
  this.shadow.addEventListener('click',this.onPanelClick);this.shadow.addEventListener('change',this.onPanelChange);
  void this.refresh();this.timer=window.setInterval(()=>void this.refresh(),10*60000);window.addEventListener('pagehide',()=>this.destroy(),{once:true});
 }
 private onPlace=(event:Event)=>{const id=(event as CustomEvent).detail?.id;if(typeof id!=='string')return;this.place=id;const area=forecastAreaForPlace(id);if(area&&this.state){this.state.areaId=area;this.ensureDay();this.address();}this.render();};
 private onHome=(event:Event)=>{const mode=(event as CustomEvent).detail?.mode;if(['boat','shore','spear'].includes(mode)){this.setMode(mode);if(this.state){this.ensureDay();this.address();this.render();}}};
 private setMode(mode:Mode){if(this.state)this.state.mode=mode;const species=$<HTMLSelectElement>('species');species.value=defaultSpecies(mode);species.dispatchEvent(new Event('change'));const depth=$<HTMLInputElement>('depth-limit');depth.value=String(mode==='spear'?60:300);depth.dispatchEvent(new Event('input'));}
 private onSpecies=()=>{if(this.state){this.state.species=$<HTMLSelectElement>('species').value as SpeciesId;this.render();}};
 private async refresh(){const generation=++this.generation;try{const response=await coastFetch('/api/report',{signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('Report unavailable');const report=await response.json() as Report;if(report.schemaVersion!==1||report.countyId!=='slo'||!Array.isArray(report.forecasts))throw Error('Wrong report binding');if(!this.alive||generation!==this.generation)return;
  if(this.state){this.state.report=report;this.state.now=new Date();this.ensureDay();}else{const params=new URLSearchParams(location.search),mode=params.get('profile') as Mode;this.state=createState(report,slo,['boat','shore','spear'].includes(mode)?mode:'boat',forecastAreaForPlace(this.place)??params.get('area')??'central',params.get('day')??undefined,$<HTMLSelectElement>('species').value as SpeciesId);const hour=params.get('hour');const matched=matchingHour(daily(this.state).hours,hour);if(matched)this.state.at=matched;}
  this.render();
 }catch{if(this.alive&&this.state){this.state.now=new Date();this.ensureDay();this.render();}if(this.alive&&!this.state)$('report-bar').innerHTML='<div class="report-unavailable"><b>Current report unavailable</b><span>The map remains available. Forecast and observation gaps are not filled.</span><a href="/#forecast">Full report</a></div>';}
 }
 private ensureDay(){const s=this.state!;const days=availableDays(s.report,s.county,selectedArea(s),s.now);if(!days.some(d=>d.date===s.date))s.date=days[0].date;const hours=daily(s).hours;if(!hours.some(h=>h.at===s.at))s.at=hours[0]?.at??s.now.toISOString();}
 private address(){if(!this.state)return;const s=this.state,url=new URL(location.href);for(const [k,v]of Object.entries({profile:s.mode,area:s.areaId,day:s.date,hour:s.at}))url.searchParams.set(k,v);history.replaceState(null,'',url);}
 private render(keepClock=false){if(!this.state)return;const s=this.state,b=daily(s),h=forecastHour(s),tide=tideAt(s),planningWindow=quietestHours(s),area=forecastAreaForPlace(this.place);const days=availableDays(s.report,s.county,selectedArea(s),s.now);
  if(!area){$('report-bar').innerHTML=`<div class="report-unavailable"><div><span class="eyebrow">REGIONAL DATA COVERAGE</span><b>Local forecasts are not integrated for this map area yet.</b><span>SLO conditions remain available with their own location and source clocks.</span></div><button data-report-open>View SLO report ↗</button></div>`;}
  else{const selectedIndex=Math.max(0,b.hours.findIndex(hour=>hour.at===s.at));const html=`<div class="report-context"><span class="eyebrow">${esc(b.label)} · ${esc(selectedArea(s).name)}</span><div class="report-controls"><select id="report-mode" aria-label="Fishing method">${(['boat','shore','spear'] as Mode[]).map(m=>`<option value="${m}" ${s.mode===m?'selected':''}>${m==='spear'?'Spearfishing':m==='shore'?'Shore fishing':'Boat fishing'}</option>`).join('')}</select><select id="report-day" aria-label="Report day">${days.map(d=>`<option value="${d.date}" ${s.date===d.date?'selected':''}>${esc(d.label)} · ${time(d.date+'T20:00:00Z',slo.timezone,{month:'short',day:'numeric'})}${d.provisional?' · outlook':''}</option>`).join('')}</select></div></div><div class="report-metrics">${methodMetrics(s)}</div><button class="report-open" data-report-open>Full conditions ↗</button><div class="report-clock"><label for="coast-hour">${h?time(s.at,slo.timezone,{weekday:'short',hour:'numeric',minute:'2-digit'}):'No supported forecast hour'}</label><input id="coast-hour" type="range" min="0" max="${Math.max(0,b.hours.length-1)}" value="${selectedIndex}" step="1" ${b.hours.length?'':'disabled'} aria-label="Selected forecast hour"><span>NWS · NOAA · CDIP · report assembled ${ageLabel(s.report.generatedAt,s.now)}</span></div>`;if(keepClock){const staging=document.createElement('div');staging.innerHTML=html;const metrics=staging.querySelector('.report-metrics')!;$('report-bar').querySelector('.report-metrics')?.replaceWith(metrics);const label=$('report-bar').querySelector('.report-clock label');if(label)label.textContent=staging.querySelector('.report-clock label')?.textContent??'';}else $('report-bar').innerHTML=html;}
  $('full-report-link').setAttribute('href',plannerURL(location.href,this.place).href);
  clearTimeout(this.clockTimer);this.clockTimer=window.setTimeout(()=>{if(this.alive&&this.state)window.dispatchEvent(new CustomEvent('coast-report-clock-change',{detail:{at:this.state.at}}));},180);if($<HTMLDialogElement>('report-dialog').open)this.renderPanel();
 }
 private onBarClick=(e:Event)=>{if((e.target as HTMLElement).closest('[data-report-open]'))this.open();};
 private onBarChange=(e:Event)=>{const el=e.target as HTMLSelectElement;if(!this.state)return;if(el.id==='report-mode'){this.setMode(el.value as Mode);}if(el.id==='report-day'){this.state.date=el.value;}this.ensureDay();this.address();this.render();};
 private onBarInput=(e:Event)=>{const el=e.target as HTMLInputElement;if(el.id!=='coast-hour'||!this.state)return;const h=daily(this.state).hours[Number(el.value)];if(!h)return;this.state.at=h.at;this.address();this.render(true);};
 private open(){const dialog=$<HTMLDialogElement>('report-dialog');if(!dialog.open)dialog.showModal();this.renderPanel();dialog.scrollTop=0;}
 private async loadHistory(){if(this.history)return;try{const response=await coastFetch('/api/history',{signal:AbortSignal.timeout(20000)});if(!response.ok)return;const bundle=await response.json() as HistoryBundle;if(bundle.countyId!=='slo')return;this.history=bundle;if(this.alive&&this.tab===3)this.renderPanel();}catch{}}
 private buoys(){const s=this.state!;return `<div class="view-heading"><div><span class="eyebrow">OBSERVED WATER · ORIGINAL CLOCKS</span><h2>What the buoys measured.</h2><p>These are observations, independently of the selected forecast day.</p></div></div><div class="buoy-grid">${s.report.observations.map(o=>`<article class="buoy-card"><h3>${esc(slo.buoys.find(b=>b.id===o.stationId)?.name??o.stationId)}</h3><p>${esc(o.stationId)} · ${time(o.observedAt,slo.timezone,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})} · ${ageLabel(o.observedAt,s.now)}</p><dl><div><dt>Water</dt><dd>${value(o.waterTempF,1)} °F</dd></div><div><dt>Waves / period</dt><dd>${value(o.waveFt,1)} ft / ${value(o.wavePeriodS)} s</dd></div><div><dt>Wind / gust</dt><dd>${value(o.windKnots)} / ${value(o.gustKnots)} kt</dd></div></dl><a href="${esc(o.url)}" target="_blank" rel="noopener">Original station data ↗</a></article>`).join('')}</div><h3>Nearshore models</h3>${(s.report.nearshore??[]).filter(p=>p.areaId===s.areaId).map(p=>`<p>${esc(p.name)} · ${esc(p.kind)} · issue ${p.issuedAt?time(p.issuedAt,slo.timezone,{month:'short',day:'numeric',hour:'numeric'}):'unknown'} · ${esc(p.availability)} · ${esc(p.freshness)} · <a href="${esc(p.url)}" target="_blank" rel="noopener">source</a></p>`).join('')}<h3>Beach and dive context</h3><p>Visibility: ${s.report.visibility.status==='observed'?value(s.report.visibility.feet)+' ft · observed '+(s.report.visibility.observedAt?time(s.report.visibility.observedAt,slo.timezone,{month:'short',day:'numeric',hour:'numeric'}):'at an unknown time'):'Unknown without an in-water observation'}.</p>${(s.report.waterQuality??[]).filter(p=>p.areaId===s.areaId).map(p=>`<p>${esc(p.name)} · ${esc(p.status)}${p.sampledAt?' · sampled '+time(p.sampledAt,slo.timezone,{month:'short',day:'numeric'}):' · sample date unavailable'} · retrieved ${ageLabel(p.fetchedAt,s.now)}; last published status, not entry clearance · <a href="${esc(p.url)}" target="_blank" rel="noopener">original advisory</a></p>`).join('')}`;}
 private renderPanel(){const s=this.state;if(!s){this.shadow.innerHTML='<p>Loading the SLO report…</p>';return;}
  const html=this.tab===0?briefing(s):this.tab===1?conditions(s):this.tab===2?this.buoys():this.tab===3?historyView(s,this.history,this.selection):this.tab===4?catchSheet(s):sourceSheet(s);
  this.shadow.innerHTML=`<link rel="stylesheet" href="${$('report-content').dataset.styles??''}"><div class="report-heading"><div><span class="eyebrow">SLO FISH REPORT · ${esc(slo.shortName)}</span><h2>${esc(selectedArea(s).name)}</h2></div><select id="panel-area" aria-label="SLO report area">${slo.areas.map(a=>`<option value="${a.id}" ${s.areaId===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></div><p>Forecasts, tide predictions, buoy observations, fleet reports and historical records retain their own locations and source times. ${!forecastAreaForPlace(this.place)?'These are SLO conditions, not a forecast for the displayed map area.':''}</p><nav class="report-tabs" role="tablist" aria-label="Report data">${tabs.map((t,i)=>`<button role="tab" data-report-tab="${i}" aria-selected="${this.tab===i}">${t}</button>`).join('')}</nav><div class="${this.tab===0?'report-brief':'report-section'}">${html}</div>`;
  this.shadow.querySelectorAll('.spot-heading,#spot-list,[data-explore-map]').forEach(el=>el.remove());if(this.tab===3&&!this.history)void this.loadHistory();
 }
 private onPanelClick=(e:Event)=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!button||!this.state)return;if(button.dataset.reportTab!==undefined){this.tab=Number(button.dataset.reportTab);this.renderPanel();$<HTMLDialogElement>('report-dialog').scrollTop=0;}else if(button.dataset.open==='catches'){this.tab=4;this.renderPanel();$<HTMLDialogElement>('report-dialog').scrollTop=0;}else if(button.dataset.open==='sources'){this.tab=5;this.renderPanel();$<HTMLDialogElement>('report-dialog').scrollTop=0;}else if(button.dataset.historyDays){this.selection.days=Number(button.dataset.historyDays);this.renderPanel();}else if(button.hasAttribute('data-next-day')){const days=availableDays(this.state.report,slo,selectedArea(this.state),this.state.now);if(days[1]){this.state.date=days[1].date;this.ensureDay();this.address();this.render();}}};
 private onPanelChange=(e:Event)=>{const select=e.target as HTMLSelectElement;if(!this.state)return;if(select.id==='panel-area'&&slo.areas.some(a=>a.id===select.value)){this.state.areaId=select.value;this.ensureDay();const location=$<HTMLSelectElement>('location');location.value=({north:'cambria',central:'morro',south:'avila'} as Record<string,string>)[select.value];location.dispatchEvent(new Event('change'));}else if(select.id==='history-station')this.selection.station=select.value;else if(select.id==='history-metric')this.selection.metric=select.value as HistoryMetric;this.renderPanel();};
 destroy(){this.alive=false;this.generation++;clearInterval(this.timer);clearTimeout(this.clockTimer);window.removeEventListener('coast-place-change',this.onPlace);window.removeEventListener('coast-home-change',this.onHome);$('species').removeEventListener('change',this.onSpecies);}
}
