import {coastFetch} from '../transport.ts';
import * as T from 'three';
import {habitatDisplay,habitatTriangles} from './habitat-display.ts';
import {coastPlaces as places,habitatPlace,reportAreaPlace} from './places.ts';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {coastPoint,coastLonLat,nearestDepth,type Grid} from './grid.ts';
import {verifiedAsset,decodeTerrain,displayElevations,roundEven,continuousTriangles,chooseTiles,reefBindingMatches,rankedHabitat,type RegionalManifest,type RegionTile,type Asset,type TerrainSource} from './regional.ts';
import {readReviewedHabitat,validateHabitatHeads,type ReviewedHabitat} from '../map/habitat-lifecycle.ts';
import {speciesOptions} from '../habitat-types.ts';
import {selectCurrentFrame} from '../map-sources.ts';
import {surfaceField} from '../map/surface-field.ts';
import type {OceanData} from '../ocean-types.ts';
export type CoastViewerOptions={root?:Document|ShadowRoot|HTMLElement;managed?:boolean;onSelection?:(point:{latitude:number;longitude:number;region?:string;id?:string})=>void;onPlace?:(id:string)=>void;onView?:(view:{latitude:number;longitude:number;span:number})=>void;onPerspective?:(mode:'2d'|'3d')=>void};
async function json(url:string){const r=await coastFetch(url,{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Dataset unavailable');return r.json();}
type Loaded={tile:RegionTile;grid:Grid;level:number;mesh:T.Mesh;water:T.Mesh;child:boolean};
type Reading={height:number;source:number;spacing:number;sampleX?:number;sampleZ?:number};
// Immutable decoded grids can reuse the presentation filter across relief and
// seam redraws. A new source inventory invalidates this display-only cache.
const displayedHeights=new WeakMap<Grid,{sources:readonly TerrainSource[]|undefined;values:Float32Array}>();
function terrainDisplay(grid:Grid,sources?:readonly TerrainSource[]){const old=displayedHeights.get(grid);if(old&&old.sources===sources)return old.values;const values=displayElevations(grid,sources);displayedHeights.set(grid,{sources,values});return values;}

export class CoastViewer{
 private renderer:T.WebGLRenderer;private scene=new T.Scene();private camera:T.PerspectiveCamera|T.OrthographicCamera=new T.PerspectiveCamera(42,1,2,1000000);private controls:OrbitControls;
 private manifest!:RegionalManifest;private seams=new T.Group();private atlas:T.Texture|undefined;private detailImages=new Set<string>();private terrain=new T.Group();private waters=new T.Group();private habitat=new T.Group();private currents=new T.Group();private overview:Grid|null=null;private background:Grid|null=null;
 private loaded=new Map<string,Loaded>();private textures=new Map<string,Promise<T.Texture>>();private textureValues:T.Texture[]=[];private pending=new Set<string>();
 private coverage!:T.DataTexture;private harborCoverage!:T.DataTexture;private cols=0;private rows=0;
 private relief={value:5};private contours={value:1};private sourceColors={value:0};private waterOpacity={value:.5};
 private alive=true;private frame=0;private resize:ResizeObserver;private refreshTimer=0;private lodTimer=0;private refining=false;private revision=0;
 private perspective:'2d'|'3d'='3d';private orbit=new T.Vector3(-4600,3600,4800);private orthoHeight=7000;private down=[0,0];private ray=new T.Raycaster();
 private reviewed:ReviewedHabitat|null=null;private allFeatures:any[]=[];private features:any[]=[];private selectedTarget:string|null=null;private requestedHabitat:string|null=null;private reefIndex=0;private habitatGeneration=0;private context:any=null;private currentGeneration=0;
 private readingGeneration=0;private chartManifest:Promise<any>|null=null;private chartEvidenceCache=new Map<string,Promise<{ranges:Float32Array;kinds:Uint8Array;values:Float32Array}>>();
 private shoreGeneration=0;private shoreFeatures:any[]=[];private depthLimit=300;private visualClasses=new Uint8Array(256);private allowedSources=new Set<number>();
 private pins:{el:HTMLButtonElement;point:T.Vector3;id:string}[]=[];private labels:{el:HTMLElement;point:T.Vector3}[]=[];
 private host:HTMLElement;private root:Document|ShadowRoot|HTMLElement;private options:CoastViewerOptions;private visible=true;private speciesSupported=true;
 private $<E extends HTMLElement=HTMLElement>(id:string):E{return this.root.querySelector('[id="'+id+'"]') as E;}
 constructor(host:HTMLElement,options:CoastViewerOptions={}){this.host=host;this.options=options;this.root=options.root??document;
  this.renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.setClearColor('#dce8e7');this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1;
  host.prepend(this.renderer.domElement);this.renderer.domElement.setAttribute('role','img');this.renderer.domElement.setAttribute('aria-label','Coastal terrain; drag to orbit, scroll to zoom, click to inspect source depth');this.renderer.domElement.tabIndex=0;
  this.scene.add(new T.HemisphereLight('#effbff','#4b655d',.95));const sun=new T.DirectionalLight('#fff2d4',1.5);sun.position.set(-30000,50000,-20000);this.scene.add(sun);this.scene.add(this.terrain,this.waters,this.seams,this.habitat,this.currents);
  this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.screenSpacePanning=false;this.controls.minDistance=160;this.controls.maxDistance=400000;this.controls.maxPolarAngle=Math.PI*.46;this.controls.minPolarAngle=.08;
  this.controls.mouseButtons={LEFT:T.MOUSE.ROTATE,MIDDLE:T.MOUSE.DOLLY,RIGHT:T.MOUSE.PAN};this.controls.touches={ONE:T.TOUCH.ROTATE,TWO:T.TOUCH.DOLLY_PAN};
  this.controls.addEventListener('end',()=>this.userViewChanged());
  if(!this.options.managed)window.addEventListener('coast-report-clock-change',this.reportClock);
  this.resize=new ResizeObserver(()=>this.onResize());this.resize.observe(host);const [x,z]=coastPoint(places[0][2],places[0][3]);this.moveTo(x,z,places[0][4]);this.onResize();this.bind();this.animate=this.animate.bind(this);this.animate();
 }
 async load():Promise<boolean>{try{
  this.manifest=await json('/data/coast-wide/manifest.json');if(this.manifest.schemaVersion!==1||this.manifest.origin[0]!==-120.98||this.manifest.origin[1]!==35.43)throw Error('Unsupported coast release');
  for(const source of this.manifest.sources){if(!Number.isInteger(source.id)||source.id<1||source.id>255||this.allowedSources.has(source.id))throw Error('Invalid terrain source inventory');this.allowedSources.add(source.id);this.visualClasses[source.id]=source.kind==='lidar'?7:source.kind==='land'?2:source.kind==='model'?1:source.kind==='estimate'?3:4;}
  const [x,z,r,b]=this.manifest.bounds;this.cols=(r-x)/4096;this.rows=(b-z)/4096;
  this.coverage=this.coverageTexture(this.cols,this.rows);this.harborCoverage=this.coverageTexture(this.cols*4,this.rows*4);
  const a=this.manifest.overview;this.overview=decodeTerrain(await verifiedAsset(a),a.size,a.x,a.z,a.dx,a.dz,this.allowedSources);const image=this.manifest.overviewImagery;let atlas:T.Texture|undefined;try{if(image)atlas=await this.texture(image);}catch{}this.atlas=atlas;this.addSurface(this.overview,0,false,atlas,image?.bounds);
  const background=this.manifest.background;if(background){this.background=decodeTerrain(await verifiedAsset(background),background.size,background.x,background.z,background.dx,background.dz,this.allowedSources);this.addSurface(this.background,4,false,atlas,image?.bounds);}
  this.$('loading').remove();this.$('source-list').replaceChildren();for(const s of this.manifest.sources){const link=document.createElement('a');link.href=s.url;link.target='_blank';link.rel='noopener';link.textContent=`${s.label} · ${s.sourceDate}`;this.$('source-list').append(link);}
  this.placeLabels();void this.loadShore();await this.refine();void this.refreshHabitat();void this.refreshCurrents();this.refreshTimer=window.setInterval(()=>{if(this.visible){void this.refreshHabitat();void this.refreshCurrents();}},60000);return true;
 }catch(e){const loading=this.$('loading');if(loading)loading.innerHTML='The coast could not load. Reload or <a href="/">open the chart and trip tools</a>.';console.error(e);return false;}}
 private coverageTexture(width:number,height:number){const texture=new T.DataTexture(new Uint8Array(width*height*4),width,height,T.RGBAFormat);texture.minFilter=texture.magFilter=T.NearestFilter;texture.needsUpdate=true;return texture;}
 private setCoverage(tile:RegionTile,child:boolean,active:boolean){const texture=child?this.harborCoverage:this.coverage,w=child?this.cols*4:this.cols,step=child?1024:4096,x=(tile.x-this.manifest.bounds[0])/step,z=(tile.z-this.manifest.bounds[1])/step;const data=texture.image.data as Uint8Array;data[(z*w+x)*4]=active?255:0;texture.needsUpdate=true;}
 private visualSource(id:number){return this.visualClasses[id];}
 private geometry(grid:Grid,skirts=true){const display=terrainDisplay(grid,this.manifest.sources),n=grid.size,count=n*n+16*(n-1),pos=new Float32Array(count*3),h=new Float32Array(count),visualHeight=new Float32Array(count),source=new Float32Array(count),transition=new Float32Array(count);
  for(let row=0;row<n;row++)for(let col=0;col<n;col++){const i=row*n+col;pos.set([grid.x+col*grid.dx,display[i]<this.manifest.waterReferenceM?this.manifest.waterReferenceM+(display[i]-this.manifest.waterReferenceM)*this.relief.value:display[i],grid.z+row*grid.dz],i*3);h[i]=grid.values[i];visualHeight[i]=display[i];source[i]=this.visualSource(grid.sources![i]);transition[i]=[col>0?i-1:i,col<n-1?i+1:i,row>0?i-n:i,row<n-1?i+n:i].some(j=>grid.sources![j]!==grid.sources![i])?1:0;}
  const surface=continuousTriangles(n),indices=new Uint32Array(surface.length+24*(n-1));indices.set(surface);let vertex=n*n,at=surface.length;
  // Rendering-only skirts close gaps between levels of detail. Separate top
  // vertices preserve surface normals; inspection excludes every skirt face.
  const depth=Math.max(250,grid.dx*4)*this.relief.value;
  const edge=(a:number,b:number)=>{const base=vertex;for(const [index,lower] of [[a,false],[b,false],[a,true],[b,true]] as [number,boolean][]){pos.set([pos[index*3],pos[index*3+1]-(lower?depth:0),pos[index*3+2]],vertex*3);h[vertex]=grid.values[index];visualHeight[vertex]=display[index];source[vertex]=this.visualSource(grid.sources![index]);vertex++;}indices.set([base,base+2,base+1,base+1,base+2,base+3],at);at+=6;};
  for(let i=0;i<n-1;i++){edge(i,i+1);edge(i*n+n-1,(i+1)*n+n-1);edge((n-1)*n+i+1,(n-1)*n+i);edge((i+1)*n,i*n);}
  const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(pos,3));g.setAttribute('sourceHeight',new T.BufferAttribute(h,1));g.setAttribute('displayHeight',new T.BufferAttribute(visualHeight,1));g.setAttribute('sourceClass',new T.BufferAttribute(source,1));g.setAttribute('sourceTransition',new T.BufferAttribute(transition,1));g.setIndex(new T.BufferAttribute(indices,1));g.userData.surfaceTriangleCount=surface.length/3;if(!skirts)g.setDrawRange(0,surface.length);g.computeVertexNormals();g.computeBoundingSphere();return g;}
 private material(grid:Grid,kind:number,water:boolean,texture?:T.Texture,extent?:number[]){
  const m=kind===3?new T.MeshBasicMaterial({color:'#ffffff',side:T.DoubleSide}):new T.MeshStandardMaterial({color:'#ffffff',roughness:water?.75:.88,metalness:0,side:T.DoubleSide,transparent:water,depthWrite:!water});
  m.onBeforeCompile=s=>{
   Object.assign(s.uniforms,{relief:this.relief,showContours:this.contours,sourceColors:this.sourceColors,waterOpacity:this.waterOpacity,mainCoverage:{value:this.coverage},childCoverage:{value:this.harborCoverage},bounds:{value:new T.Vector4(...this.manifest.bounds as [number,number,number,number])},coverageSize:{value:new T.Vector2(this.cols,this.rows)},waterReference:{value:this.manifest.waterReferenceM},landImage:{value:texture??null},atlasImage:{value:this.atlas??null},atlasExtent:{value:new T.Vector4(...(this.manifest.overviewImagery?.bounds??[0,0,1,1]) as [number,number,number,number])},imageExtent:{value:new T.Vector4(...(extent??[0,0,1,1]) as [number,number,number,number])}});
   if(water)s.vertexShader=s.vertexShader.replace('#include <beginnormal_vertex>','vec3 objectNormal=vec3(0.0,1.0,0.0);');
   s.vertexShader='attribute float sourceHeight; attribute float displayHeight; attribute float sourceClass; attribute float sourceTransition; varying float coastTransition; varying float coastHeight; varying float coastSource; varying vec2 coastXZ; uniform float relief; uniform float waterReference;\n'+s.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\ncoastTransition=sourceTransition;coastHeight=displayHeight;coastSource=sourceClass;coastXZ=position.xz;transformed.y=${water?'waterReference':'position.y'};`);
   s.fragmentShader='varying float coastTransition; varying float coastHeight; varying float coastSource; varying vec2 coastXZ; uniform sampler2D mainCoverage; uniform sampler2D childCoverage; uniform vec4 bounds; uniform vec2 coverageSize; uniform float waterReference; uniform float waterOpacity; uniform float showContours; uniform float sourceColors; uniform sampler2D landImage; uniform vec4 imageExtent; uniform sampler2D atlasImage; uniform vec4 atlasExtent;\n'+s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
    vec2 mainCell=floor((coastXZ-bounds.xy)/4096.0);vec2 childCell=floor((coastXZ-bounds.xy)/1024.0);
    ${kind===4?'if(all(greaterThanEqual(coastXZ,bounds.xy))&&all(lessThanEqual(coastXZ,bounds.zw)))discard;':''}
    ${kind===0?'if(all(greaterThanEqual(mainCell,vec2(0.0)))&&all(lessThan(mainCell,coverageSize))&&texture2D(mainCoverage,(mainCell+.5)/coverageSize).r>.5)discard;':''}
    ${kind===1?'if(texture2D(childCoverage,(childCell+.5)/(coverageSize*4.0)).r>.5)discard;':''}
    float d=max(0.0,waterReference-coastHeight);
    vec3 shallow=vec3(.32,.69,.63),channel=vec3(.035,.28,.39),shelf=vec3(.035,.28,.39),deep=vec3(.015,.095,.19);
    vec3 ocean=d<8.0?mix(shallow,channel,smoothstep(0.0,8.0,d)):d<100.0?mix(channel,shelf,smoothstep(8.0,100.0,d)):mix(shelf,deep,smoothstep(100.0,1800.0,d));
    ${water?'if(coastHeight>=waterReference)discard;diffuseColor.rgb=mix(ocean,vec3(.17,.57,.66),.2);diffuseColor.a=waterOpacity*(.65+.35*smoothstep(0.0,4.0,d));':`diffuseColor.rgb=ocean;
    if(coastHeight>=waterReference){diffuseColor.rgb=mix(vec3(.51,.56,.38),vec3(.72,.71,.53),clamp(coastHeight/600.0,0.0,1.0));${this.atlas?'vec2 auv=(coastXZ-atlasExtent.xy)/(atlasExtent.zw-atlasExtent.xy);if(all(greaterThanEqual(auv,vec2(0.0)))&&all(lessThanEqual(auv,vec2(1.0)))){vec4 widePhoto=texture2D(atlasImage,vec2(auv.x,1.0-auv.y));diffuseColor.rgb=mix(diffuseColor.rgb,widePhoto.rgb,widePhoto.a*smoothstep(.001,.012,max(widePhoto.r,max(widePhoto.g,widePhoto.b)))*.85);}':''}${texture?'vec2 uv=(coastXZ-imageExtent.xy)/(imageExtent.zw-imageExtent.xy);if(all(greaterThanEqual(uv,vec2(0.0)))&&all(lessThanEqual(uv,vec2(1.0)))){vec4 photo=texture2D(landImage,vec2(uv.x,1.0-uv.y));vec2 edgeDistance=min(uv,1.0-uv)*(imageExtent.zw-imageExtent.xy);float photoBlend=smoothstep(0.0,96.0,min(edgeDistance.x,edgeDistance.y));diffuseColor.rgb=mix(diffuseColor.rgb,photo.rgb,photo.a*smoothstep(.001,.012,max(photo.r,max(photo.g,photo.b)))*.85*photoBlend);}':''}}
    float interval=coastSource>6.5?3.048:coastSource<1.5?152.4:9.144;float level=d/interval;float edge=abs(fract(level-.5)-.5)/max(fwidth(level),.001);float line=(1.0-smoothstep(.4,1.3,edge))*showContours*(1.0-smoothstep(0.0,.02,coastTransition));
    if(coastHeight<waterReference)diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.05,.22,.28),line*.35);
    vec3 evidence=coastSource>6.5?vec3(.22,.8,.66):coastSource>3.5?vec3(.32,.64,.88):coastSource>2.5?vec3(.95,.67,.3):coastSource>1.5?vec3(.73,.76,.48):vec3(.53,.48,.72);diffuseColor.rgb=mix(diffuseColor.rgb,evidence,sourceColors*.65);`}
   `);
  };m.customProgramCacheKey=()=>`coastal-${kind}-${water}-${!!texture}-${!!this.atlas}`;return m;
 }
 private imageryFor(grid:Grid,detail=true){const cx=grid.x+(grid.size-1)*grid.dx/2,cz=grid.z+(grid.size-1)*grid.dz/2;return this.manifest.imagery.filter(a=>(a.kind!=='detail'||(detail&&this.detailImages.has(a.url)))&&cx>=a.bounds[0]&&cx<=a.bounds[2]&&cz>=a.bounds[1]&&cz<=a.bounds[3]).sort((a,b)=>Number(b.kind==='detail')-Number(a.kind==='detail')||Number(b.kind==='harbor')-Number(a.kind==='harbor')||(b.bounds[2]-b.bounds[0])-(a.bounds[2]-a.bounds[0]))[0];}
 private async texture(asset:Asset){let pending=this.textures.get(asset.url);if(!pending){pending=(async()=>{const data=await verifiedAsset(asset),bitmap=await createImageBitmap(new Blob([data],{type:asset.url.endsWith('.png')?'image/png':'image/jpeg'}),{imageOrientation:'flipY',...(this.host.clientWidth<600&&asset.url.endsWith('/harbor.jpg')?{resizeWidth:2048,resizeHeight:2048}:{})});if(!this.alive){bitmap.close();throw Error('Viewer disposed');}const t=new T.CanvasTexture(bitmap);t.colorSpace=T.SRGBColorSpace;t.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());t.name=asset.url;this.textureValues.push(t);return t;})();this.textures.set(asset.url,pending);}return pending;}
 private addSurface(grid:Grid,kind:number,child:boolean,texture?:T.Texture,extent?:number[]){const g=this.geometry(grid,false);const mesh=new T.Mesh(g,this.material(grid,kind,false,texture,extent)),water=new T.Mesh(g,this.material(grid,kind,true));mesh.frustumCulled=water.frustumCulled=false;mesh.userData.grid=grid;mesh.userData.kind=kind;mesh.userData.imageURL=texture?.name;water.renderOrder=2;this.terrain.add(mesh);this.waters.add(water);return {mesh,water};}
 private notifyView(){if(!this.alive||!this.visible)return;const [longitude,latitude]=coastLonLat(this.controls.target.x,this.controls.target.z),span=this.span();if([latitude,longitude,span].every(Number.isFinite)&&span>0)this.options.onView?.({latitude,longitude,span});}
 private userViewChanged(){if(!this.alive||!this.visible)return;this.notifyView();clearTimeout(this.lodTimer);this.lodTimer=window.setTimeout(()=>{void this.refine();this.drawPins();},180);}
 private span(){return this.camera instanceof T.OrthographicCamera?this.orthoHeight/this.camera.zoom:this.camera.position.distanceTo(this.controls.target);}
 private removeLoaded(key:string,item:Loaded){this.setCoverage(item.tile,item.child,false);this.terrain.remove(item.mesh);this.waters.remove(item.water);item.mesh.geometry.dispose();(item.mesh.material as T.Material).dispose();(item.water.material as T.Material).dispose();this.loaded.delete(key);}
 private async loadTile(tile:RegionTile,level:number,child:boolean,rev:number){const key=(child?'h':'t')+tile.x+':'+tile.z;const old=this.loaded.get(key),centreGrid={x:tile.x,z:tile.z,size:2,dx:tile.width,dz:tile.width,values:new Float32Array(4)};const desired=this.imageryFor(centreGrid);if(this.pending.has(key)||(old?.level===level&&old.mesh.userData.imageURL===desired?.url))return;this.pending.add(key);
  try{const a=tile.lods[level],grid=old?.level===level?old.grid:decodeTerrain(await verifiedAsset(a),a.size,tile.x,tile.z,a.spacing,a.spacing,this.allowedSources);let image=desired,texture:T.Texture|undefined;try{if(image)texture=await this.texture(image);}catch{image=this.imageryFor(grid,false);try{if(image)texture=await this.texture(image);}catch{/* Geographic context remains available. */}}
   if(!this.alive||rev!==this.revision)return;const previous=this.loaded.get(key);if(previous)this.removeLoaded(key,previous);const surfaces=this.addSurface(grid,child?2:1,child,texture,image?.bounds);this.loaded.set(key,{tile,grid,level,child,...surfaces});this.setCoverage(tile,child,true);
  }catch(e){console.warn('Keeping regional context while detail is unavailable',e);}finally{this.pending.delete(key);}}
 private async refine(){if(!this.manifest||!this.alive||!this.visible)return;const rev=++this.revision;if(this.refining)return;this.refining=true;
  try{const span=this.span();if(this.perspective==='3d')this.scene.fog=new T.Fog('#dce8e7',span*1.8,span*5);const x=this.controls.target.x,z=this.controls.target.z,mobile=this.host.clientWidth<600;this.detailImages=new Set(span<16000?this.manifest.imagery.filter(a=>a.kind==='detail').sort((a,b)=>Math.hypot((a.bounds[0]+a.bounds[2])/2-x,(a.bounds[1]+a.bounds[3])/2-z)-Math.hypot((b.bounds[0]+b.bounds[2])/2-x,(b.bounds[1]+b.bounds[3])/2-z)).slice(0,mobile?3:8).map(a=>a.url):[]);
   const mains=span<110000?chooseTiles(this.manifest.tiles,x,z,span*Math.max(1,this.host.clientWidth/this.host.clientHeight),mobile?70:110):[];
   const children=span<18000?chooseTiles(this.manifest.harborTiles,x,z,Math.min(span,9000),54):[];
   const jobs=[...mains.map(t=>({t,child:false})),...children.map(t=>({t,child:true}))];const keep=new Set(jobs.map(({t,child})=>(child?'h':'t')+t.x+':'+t.z));
   for(const [key,item] of this.loaded)if(!keep.has(key))this.removeLoaded(key,item);
   let fineMain=0,fineHarbor=0,mediumMain=0,mediumHarbor=0;const queue=jobs.map(({t,child})=>{const distance=Math.hypot(t.x+t.width/2-x,t.z+t.width/2-z);let level=0;
    if(child&&span<12000&&distance<4500&&(t.lidarFraction??1)>.03&&mediumHarbor++<(mobile?12:18)){level=1;if(span<2700&&distance<1600&&fineHarbor++<(mobile?1:2))level=2;}
    else if(!child&&t.lods.length>1&&span<30000&&mediumMain++<(mobile?10:16)){level=1;if(span<6500&&distance<4200&&!children.some(c=>c.x>=t.x&&c.x<t.x+t.width&&c.z>=t.z&&c.z<t.z+t.width)&&fineMain++<(mobile?1:2))level=2;}
    level=Math.min(level,t.lods.length-1);return {t,child,level};}).sort((a,b)=>Number(b.child)-Number(a.child));
   await Promise.all(Array.from({length:4},async()=>{while(queue.length&&this.alive&&this.visible&&rev===this.revision){const job=queue.shift()!;await this.loadTile(job.t,job.level,job.child,rev);}}));
   const used=new Set(this.terrain.children.map(t=>t.userData.imageURL));for(const t of [...this.textureValues])if(this.textureValues.length>12&&!used.has(t.name)){this.textures.delete(t.name);this.textureValues.splice(this.textureValues.indexOf(t),1);(t.image as ImageBitmap)?.close?.();t.dispose();}
   this.drawCoverageSeams();
   this.$('mesh-status').textContent=`${this.loaded.size} streamed tiles · ${children.length?'Morro lidar refinement':'regional relief'} · source detail varies`;
  }finally{this.refining=false;if(this.alive&&rev!==this.revision)void this.refine();}}
 private drawCoverageSeams(){
  this.clear(this.seams);if(!this.overview)return;
  const overviewMesh=this.terrain.children.find(m=>m.userData.kind===0) as T.Mesh;
  // Refresh only display positions. Source heights, identities, evidence and
  // inspection readings remain untouched. A short inner band meets its parent
  // surface instead of exposing tall vertical curtains at streaming boundaries.
  const ordered=[...this.loaded.values()].sort((a,b)=>Number(a.child)-Number(b.child)||b.grid.dx-a.grid.dx||a.tile.x-b.tile.x||a.tile.z-b.tile.z),processed=new Set<Loaded>();
  for(const item of ordered){const p=item.mesh.geometry.getAttribute('position') as T.BufferAttribute,display=terrainDisplay(item.grid,this.manifest.sources);for(let i=0;i<display.length;i++)p.setY(i,display[i]<this.manifest.waterReferenceM?this.manifest.waterReferenceM+(display[i]-this.manifest.waterReferenceM)*this.relief.value:display[i]);}
  const sample=(grid:Grid,mesh:T.Mesh,x:number,z:number)=>{const gx=Math.max(0,Math.min(grid.size-1,(x-grid.x)/grid.dx)),gz=Math.max(0,Math.min(grid.size-1,(z-grid.z)/grid.dz)),col=Math.min(grid.size-2,Math.floor(gx)),row=Math.min(grid.size-2,Math.floor(gz)),fx=gx-col,fz=gz-row,a=row*grid.size+col,b=a+1,c=a+grid.size,d=c+1,p=mesh.geometry.getAttribute('position');return fx+fz<=1?p.getY(a)*(1-fx-fz)+p.getY(b)*fx+p.getY(c)*fz:p.getY(b)*(1-fz)+p.getY(c)*(1-fx)+p.getY(d)*(fx+fz-1);};
  for(const item of ordered){const {tile,grid,child}=item,p=item.mesh.geometry.getAttribute('position') as T.BufferAttribute,n=grid.size,w=tile.width,band=Math.min(n-1,Math.max(2,Math.ceil(256/grid.dx))),edgeTargets=new Map<number,number>();
   for(const side of ['west','east','north','south']){const vertical=side==='west'||side==='east',fixed=vertical?tile.x+(side==='east'?w:0):tile.z+(side==='south'?w:0);const nx=tile.x+(side==='west'?-w:side==='east'?w:0),nz=tile.z+(side==='north'?-w:side==='south'?w:0);const neighbor=this.loaded.get((child?'h':'t')+nx+':'+nz);if(neighbor&&!processed.has(neighbor))continue;
    let parentGrid=neighbor?.grid??this.overview,parentMesh=neighbor?.mesh??overviewMesh;if(child&&!neighbor){const epsilon=side==='west'||side==='north'?-1:1,px=vertical?fixed+epsilon:tile.x+w/2,pz=vertical?tile.z+w/2:fixed+epsilon,parent=ordered.find(t=>!t.child&&px>=t.tile.x&&px<=t.tile.x+t.tile.width&&pz>=t.tile.z&&pz<=t.tile.z+t.tile.width);if(parent){parentGrid=parent.grid;parentMesh=parent.mesh;}}
    for(let along=0;along<n;along++){const bx=vertical?fixed:tile.x+along*grid.dx,bz=vertical?tile.z+along*grid.dz:fixed,target=sample(parentGrid,parentMesh,bx,bz);edgeTargets.set((vertical?along:side==='north'?0:n-1)*n+(vertical?(side==='west'?0:n-1):along),target);for(let depth=0;depth<band;depth++){const row=vertical?along:side==='north'?depth:n-1-depth,col=vertical?(side==='west'?depth:n-1-depth):along,i=row*n+col,t=depth/band,weight=1-t*t*(3-2*t);p.setY(i,p.getY(i)+(target-p.getY(i))*weight);}}
   }
   // Re-pin exterior edges after all bands: intersecting corner blends must
   // never pull an already matched boundary away from its parent.
   for(const [i,y] of edgeTargets)p.setY(i,y);
   // Skirts follow their softened surface vertices and keep their original
   // downward extent. They are never included in terrain inspection.
   let at=n*n;const depth=Math.max(250,grid.dx*4)*this.relief.value,edge=(a:number,b:number)=>{for(const [i,lower] of [[a,false],[b,false],[a,true],[b,true]] as [number,boolean][])p.setY(at++,p.getY(i)-(lower?depth:0));};for(let i=0;i<n-1;i++){edge(i,i+1);edge(i*n+n-1,(i+1)*n+n-1);edge((n-1)*n+i+1,(n-1)*n+i);edge((i+1)*n,i*n);}
   // Every edge now meets either its existing neighbor or its parent surface.
   // Closed borders must not expose the old kilometre-deep rendering skirts.
   item.mesh.geometry.setDrawRange(0,item.mesh.geometry.userData.surfaceTriangleCount*3);
   const visualHeight=item.mesh.geometry.getAttribute('displayHeight') as T.BufferAttribute|undefined;if(visualHeight){for(let i=0;i<visualHeight.count;i++){const y=p.getY(i),water=this.manifest.waterReferenceM;visualHeight.setX(i,y<water?water+(y-water)/this.relief.value:y);}visualHeight.needsUpdate=true;}
   p.needsUpdate=true;item.mesh.geometry.computeVertexNormals();item.mesh.geometry.computeBoundingSphere();processed.add(item);
  }
 }
 private readingAt(x:number,z:number):Reading|null{const ordered=[...this.loaded.values()].sort((a,b)=>Number(b.child)-Number(a.child)||a.grid.dx-b.grid.dx);for(const item of ordered){const h=nearestDepth(item.grid,x,z);if(h!==null){const i=Math.round((z-item.grid.z)/item.grid.dz)*item.grid.size+Math.round((x-item.grid.x)/item.grid.dx);return {height:h,source:item.grid.sources![i],spacing:item.grid.dx,sampleX:item.grid.x+Math.round((x-item.grid.x)/item.grid.dx)*item.grid.dx,sampleZ:item.grid.z+Math.round((z-item.grid.z)/item.grid.dz)*item.grid.dz};}}
  for(const grid of [this.overview,this.background])if(grid){const h=nearestDepth(grid,x,z);if(h!==null){const i=Math.round((z-grid.z)/grid.dz)*grid.size+Math.round((x-grid.x)/grid.dx);return {height:h,source:grid.sources![i],spacing:Math.max(grid.dx,grid.dz)};}}return null;}
 private clear(group:T.Group){for(const child of [...group.children]){group.remove(child);child.traverse(node=>{const item=node as T.Mesh;item.geometry?.dispose();const mats=Array.isArray(item.material)?item.material:[item.material];for(const m of mats)m?.dispose();});}}
 private async refreshHabitat(){if(!this.visible||!this.alive)return;const gen=++this.habitatGeneration;try{
  if(this.reviewed)await validateHabitatHeads(this.reviewed.manifest);const reviewed=await readReviewedHabitat('/data/skippercast-manifest.json','/data/skippercast-habitat.geojson');let full=reviewed.details,context:any=null;
  // A fresh reviewed upstream edition can still upgrade the curated layer while
  // a separately compiled full-context edition awaits its exact source binding.
  try{const proposed=await json('/data/coast-wide/reef-context.json');if(reefBindingMatches(proposed,reviewed.manifest)){context=proposed;if(this.context?.asset.sha256===context.asset.sha256)full=this.allFeatures;else{const decoded=await verifiedAsset(context.asset,64*1024*1024);full=JSON.parse(new TextDecoder().decode(decoded)).features;if(!Array.isArray(full)||full.length!==context.featureCount)throw Error('Reef context shape changed');}}}catch{full=reviewed.details;context=null;}
  await validateHabitatHeads(reviewed.manifest);if(!this.alive||gen!==this.habitatGeneration)return;const detailed=new Map(reviewed.details.map(f=>[String(f.id??f.properties.id),f]));this.allFeatures=full.map(f=>detailed.get(String(f.id??f.properties.id))??f);this.context=context;this.reviewed=reviewed;this.drawHabitat();
 }catch{if(gen!==this.habitatGeneration)return;this.reviewed=null;this.allFeatures=[];this.features=[];this.context=null;this.clear(this.habitat);this.clearPins();this.$('rank-list').replaceChildren();this.$('habitat-status').textContent='Reviewed reefs withheld: source binding or current screening unavailable.';this.$<HTMLButtonElement>('next-reef').disabled=true;this.$('target-detail').hidden=true;if(this.speciesSupported&&['halibut','surfperch'].includes(this.option().id))this.drawShore();}}
 private option(){return speciesOptions.find(s=>s.id===this.$<HTMLSelectElement>('species').value)??speciesOptions[0];}
 private drawHabitat(){this.clear(this.habitat);this.clearPins();if(!this.speciesSupported){this.features=[];this.$('rank-list').replaceChildren();this.$('target-detail').hidden=true;this.$<HTMLButtonElement>('next-reef').disabled=true;this.$('habitat-status').textContent='Terrain habitat unavailable for this target. No substitute species is assumed.';return;}const option=this.option();if(['halibut','surfperch'].includes(option.id)){this.drawShore();return;}if(!this.reviewed)return;this.features=rankedHabitat(this.allFeatures,option.field).filter(f=>f.properties.depth_max_ft<=this.depthLimit);const position:number[]=[],colors:number[]=[],fill:number[]=[],fillColors:number[]=[];
  for(const f of this.features){const tri=habitatTriangles(f.geometry.coordinates);for(const v of tri)fill.push(v);const p=f.properties,color=new T.Color(p.terrain_grade==='A'?'#f8d69a':p.terrain_grade==='B'?'#afd7ba':'#abcad8');const areaColor=new T.Color('#69e6c3');for(let i=0;i<tri.length;i+=3)fillColors.push(areaColor.r,areaColor.g,areaColor.b);for(const ring of f.geometry.coordinates)for(let i=1;i<ring.length;i++){for(const coordinate of [ring[i-1],ring[i]]){const [x,z]=coastPoint(coordinate[0],coordinate[1]);position.push(x,3,z);colors.push(color.r,color.g,color.b);}}}
  const fg=new T.BufferGeometry();fg.setAttribute('position',new T.Float32BufferAttribute(fill,3));fg.setAttribute('color',new T.Float32BufferAttribute(fillColors,3));const filled=new T.Mesh(fg,new T.MeshBasicMaterial({vertexColors:true,transparent:true,opacity:.3,depthTest:false,depthWrite:false,side:T.DoubleSide}));filled.userData.habitatFill=true;filled.renderOrder=3;this.habitat.add(filled);
  const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(position,3));g.setAttribute('color',new T.Float32BufferAttribute(colors,3));this.habitat.add(new T.LineSegments(g,new T.LineBasicMaterial({vertexColors:true,transparent:true,opacity:.78,depthTest:false})));this.habitat.visible=this.$<HTMLInputElement>('habitat').checked;
  this.$('habitat-status').textContent=`${this.features.length.toLocaleString()} screened ${option.id==='all'?'reef footprints':option.label+' candidates'} · ${this.context?'complete context':'curated current edition; full context pending'} · physical fit, not catch probability.`;this.$<HTMLButtonElement>('next-reef').disabled=!this.features.length;this.restoreHabitatSelection();this.drawRanks();this.drawPins();
 }
 private async loadShore(){if(!this.visible||!this.alive)return;const gen=++this.shoreGeneration;try{const a=(this.manifest as RegionalManifest&{shoreAsset:Asset}).shoreAsset;const data=JSON.parse(new TextDecoder().decode(await verifiedAsset(a)));if(!this.alive||!this.visible||gen!==this.shoreGeneration)return;this.shoreFeatures=data.features.filter((f:any)=>f.geometry?.type==='MultiLineString'&&Date.parse(f.properties.reviewExpiresAt)>Date.now());if(['halibut','surfperch'].includes(this.option().id))this.drawHabitat();}catch{if(gen===this.shoreGeneration)this.shoreFeatures=[];}}
 private selectShoreFeature(f:any,move:boolean,notify=true){const p=f.properties,c=p.access?.[0]?.coordinates??f.geometry.coordinates[0][0];this.selectedTarget=String(f.id??p.id);if(notify)this.requestedHabitat=this.selectedTarget;
  if(move){const [x,z]=coastPoint(c[0],c[1]);this.moveTo(x,z,4500);this.identifySelectionPlace(reportAreaPlace(p.areaId));void this.refine();}
  if(notify)this.options.onSelection?.({latitude:c[1],longitude:c[0],...(typeof p.region==='string'?{region:p.region}:{}),id:this.selectedTarget});
  this.$('target-detail').hidden=false;this.$('target-title').textContent=p.name;this.$('target-facts').textContent=p.shoreClass+' · '+p.sourceYear;this.$('target-evidence').textContent='Original NOAA shoreline vertices; no offshore depth or species fit inferred. Physical context only. Access inventory checked '+new Date(p.checkedAt).toLocaleDateString()+'. Current legal/access conditions require rechecking; the prior legal review expired '+new Date(p.legalReviewExpiresAt).toLocaleDateString()+'.';
 }
 private drawShore(){this.clear(this.habitat);this.clearPins();this.features=[];const positions:number[]=[];const list=this.$('rank-list');list.replaceChildren();for(const f of this.shoreFeatures){const p=f.properties;for(const line of f.geometry.coordinates)for(let i=1;i<line.length;i++)for(const c of [line[i-1],line[i]]){const [x,z]=coastPoint(c[0],c[1]);positions.push(x,5,z);}const button=document.createElement('button');button.className='rank';button.textContent=p.name+' · sandy-shore context';const select=()=>this.selectShoreFeature(f,true);button.onclick=select;list.append(button);const c=p.access?.[0]?.coordinates??f.geometry.coordinates[0][0],[x,z]=coastPoint(c[0],c[1]),el=document.createElement('button');el.className='species-pin shore-pin';el.setAttribute('aria-label',p.name+' · sandy-shore context');el.innerHTML='<span class=reef-dot aria-hidden=true></span>';el.onclick=select;this.$('pins').append(el);this.pins.push({el,point:new T.Vector3(x,10,z),id:p.id});}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));this.habitat.add(new T.LineSegments(g,new T.LineBasicMaterial({color:'#f8d69a',depthTest:false})));this.habitat.visible=this.$<HTMLInputElement>('habitat').checked;this.$('habitat-status').textContent=this.shoreFeatures.length+' sandy-shore context segments. No ranked offshore '+this.option().label+' habitat is admitted.';this.$<HTMLButtonElement>('next-reef').disabled=true;this.restoreHabitatSelection();}
 private drawRanks(){const list=this.$('rank-list');list.replaceChildren();for(const [i,f] of this.features.slice(0,12).entries()){const p=f.properties,button=document.createElement('button');button.className='rank';const title=document.createElement('b');title.textContent=`${i+1}. ${({'morro-bay':'Morro / Estero reef','cambria-san-simeon':'Cambria / San Simeon reef','monterey-point-sur':'Monterey / Carmel / Sur reef','point-arguello-conception':'Arguello / Conception reef'} as Record<string,string>)[p.region]??p.region} · grade ${p.terrain_grade}`;const sub=document.createElement('small');sub.textContent=`${Math.round(p.depth_min_ft)}–${Math.round(p.depth_max_ft)} ft · ${this.option().field?'fit '+p[this.option().field!]+'/3':'screened'} · terrain ${p.terrain_score}/100`;button.append(title,sub);button.onclick=()=>this.selectFeature(f,true);list.append(button);}}
 private drawPins(){if(!this.speciesSupported){this.clearPins();return;}if(['halibut','surfperch'].includes(this.option().id)){this.drawShore();return;}this.clearPins();if(!this.reviewed)return;const target=this.controls.target;const candidates=this.features.map((f,rank)=>({f,rank,d:Math.hypot(...this.featureDistance(f,target))})).sort((a,b)=>Number(String(b.f.id??b.f.properties.id)===this.selectedTarget)-Number(String(a.f.id??a.f.properties.id)===this.selectedTarget)||a.d-b.d).slice(0,90);
  for(const {f,rank} of candidates){const p=f.properties,[x,z]=coastPoint(p.waypoint_longitude,p.waypoint_latitude),el=document.createElement('button');el.className='species-pin grade-'+p.terrain_grade;const label=`#${rank+1} · ${this.option().id==='all'?'Reef':this.option().label} · ${p.terrain_grade} · ${Math.round(p.depth_min_ft)}–${Math.round(p.depth_max_ft)} ft`;el.setAttribute('aria-label',label+' nominal; physical habitat, presence unverified');el.innerHTML='<span class=reef-dot aria-hidden=true></span>';el.title='Reef habitat · grade '+p.terrain_grade;el.onclick=()=>this.selectFeature(f,false);this.$('pins').append(el);this.pins.push({el,point:new T.Vector3(x,12,z),id:String(f.id??p.id)});}}
 private featureDistance(f:any,target:T.Vector3):[number,number]{const [x,z]=coastPoint(f.properties.waypoint_longitude,f.properties.waypoint_latitude);return [x-target.x,z-target.z];}
 private clearPins(){for(const p of this.pins)p.el.remove();this.pins=[];}
 private selectFeature(f:any,move:boolean,notify=true){const p=f.properties;if(notify)this.options.onSelection?.({latitude:p.waypoint_latitude,longitude:p.waypoint_longitude,region:p.region,id:String(f.id??p.id)});this.selectedTarget=String(f.id??p.id);if(notify)this.requestedHabitat=this.selectedTarget;if(move){const [x,z]=coastPoint(p.waypoint_longitude,p.waypoint_latitude);this.moveTo(x,z,4200);this.identifySelectionPlace(habitatPlace(p.region,p.waypoint_longitude,p.waypoint_latitude));void this.refine();this.drawPins();}
  this.$('target-detail').hidden=false;this.$('target-title').textContent=`${this.option().id==='all'?'Reviewed reef':this.option().label+' habitat'} · grade ${p.terrain_grade}`;
  this.$('target-facts').textContent=`Nominal ${Math.round(p.depth_min_ft)}–${Math.round(p.depth_max_ft)} ft · physical score ${p.terrain_score}/100${this.option().field?' · species fit '+p[this.option().field!]+'/3':''}`;
  this.$('target-evidence').textContent=`${p.region.replaceAll('-',' ')} · ${p.resolution_m} m source grid · ${p.source_year} · ${Math.round(p.metric_support_fraction*100)}% metric support. ${p.independent_substrate_confirmation?'Independent substrate confirmation.':'Independent substrate confirmation absent.'} Depth reference ${p.vertical_datum??'unresolved'}. Screening valid until ${new Date(p.screen_expires_at).toLocaleDateString()}. Fish presence unverified.${p.source_ids?.includes('bathymetry-2m-offshoremonterey-zip-172dbd1794')?' USGS / CSUMB Seafloor Mapping Lab; acoustic 1998–2012, lidar 2009–2010; producer-resampled grid.':''}`;
 }
 private currentAt:Date|null=null;private reportClock=(event:Event)=>{const at=(event as CustomEvent).detail?.at;if(typeof at==='string'&&Number.isFinite(Date.parse(at)))this.setHour(new Date(at));};
 private habitatSpan(){return this.camera instanceof T.OrthographicCamera?this.span()/(2*Math.tan(T.MathUtils.degToRad(21))):this.span();}
 private async refreshCurrents(){if(!this.visible||!this.alive)return;const gen=++this.currentGeneration;try{const ocean=await json('/api/ocean') as OceanData,now=new Date(),choices=ocean.currents.map(field=>({field,frame:selectCurrentFrame(field,this.currentAt??now,now)})).filter(x=>x.frame),choice=choices.find(x=>x.field.id==='wcofs')??choices.find(x=>x.field.id==='hfr-1')??choices[0];if(gen!==this.currentGeneration||!this.alive)return;this.clear(this.currents);if(!choice){this.$('current-status').textContent='No reviewed current field covers this selected time.';return;}
  const {field,frame}=choice,smooth=surfaceField(frame!.cells.map(c=>({lon:c.lon,lat:c.lat,values:[c.uMs,c.vMs]})));let count=0;const step=Math.max(600,Math.min(4000,this.span()/12)),target=this.controls.target,radius=Math.min(22000,Math.max(8000,this.span()));
  if(smooth)for(let z=target.z-radius;z<=target.z+radius;z+=step)for(let x=target.x-radius;x<=target.x+radius;x+=step){const [lon,lat]=coastLonLat(x,z),value=smooth.sample(lon,lat),sample=this.readingAt(x,z);if(!value||!sample||sample.height>=0)continue;const speed=Math.hypot(value[0],value[1]);if(speed<.005)continue;this.currents.add(new T.ArrowHelper(new T.Vector3(value[0],0,-value[1]).normalize(),new T.Vector3(x,20,z),Math.min(step*.7,step*.2+speed*step),'#fcfaf0',step*.1,step*.05));count++;}
  this.currents.visible=this.$<HTMLInputElement>('currents').checked;this.$('current-status').textContent=`${field.label} · ${field.nativeResolutionKm} km source · ${new Date(frame!.validAt).toLocaleString()} · surface only · ${count?'blended within complete wet cells':'no usable local coverage'}`;
 }catch{if(gen===this.currentGeneration){this.clear(this.currents);this.$('current-status').textContent='Current observations unavailable.';}}}
 private placeLabels(){for(const [,title,lon,lat] of places.filter(p=>p[0]!=='coast')){const el=document.createElement('div');el.className='place';el.textContent=title;const [x,z]=coastPoint(lon,lat);this.$('labels').append(el);this.labels.push({el,point:new T.Vector3(x,70,z)});}}
 private moveTo(x:number,z:number,span:number){this.controls.target.set(x,0,z);if(this.camera instanceof T.PerspectiveCamera)this.camera.position.copy(this.controls.target).add(new T.Vector3(-.56,.46,.6).normalize().multiplyScalar(span));else{this.orthoHeight=span*.8;this.camera.zoom=1;this.camera.position.set(x,Math.max(span,25000),z+.01);this.onResize();}this.controls.update();}
 private identifySelectionPlace(id:string){const place=places.find(p=>p[0]===id)??places.at(-1)!;this.$('place-title').textContent=place[1];this.$<HTMLSelectElement>('location').value=place[0];if(!this.options.managed){const url=new URL(location.href);url.searchParams.delete('region');url.searchParams.delete('coast');url.searchParams.delete('area');url.searchParams.set('place',place[0]);history.replaceState(null,'',url);window.dispatchEvent(new CustomEvent('coast-place-change',{detail:{id:place[0]}}));}this.options.onPlace?.(place[0]);this.readingGeneration++;this.$('reading').hidden=true;}
 private goPlace(id:string){const place=places.find(p=>p[0]===id)??places[0];const [x,z]=coastPoint(place[2],place[3]);this.moveTo(x,z,place[4]*(this.host.clientWidth<500?1.25:1));this.identifySelectionPlace(place[0]);this.$('target-detail').hidden=true;this.selectedTarget=null;}

 setPerspective(mode:'2d'|'3d'){if(mode===this.perspective)return;const target=this.controls.target.clone();if(mode==='2d'){this.orbit.copy(this.camera.position).sub(target);this.orthoHeight=this.orbit.length()*2*Math.tan(T.MathUtils.degToRad(21));this.camera=new T.OrthographicCamera(-1,1,1,-1,2,1000000);this.camera.position.copy(target).add(new T.Vector3(0,Math.max(25000,this.orbit.length()),.01));}else{const span=this.orthoHeight/this.camera.zoom/(2*Math.tan(T.MathUtils.degToRad(21)));this.camera=new T.PerspectiveCamera(42,1,2,1000000);this.camera.position.copy(target).add(this.orbit.clone().normalize().multiplyScalar(span));}
  this.scene.fog=mode==='2d'?null:new T.Fog('#dce8e7',this.span()*1.8,this.span()*5);this.perspective=mode;this.controls.object=this.camera;this.controls.enableRotate=mode==='3d';this.controls.minPolarAngle=mode==='2d'?0:.08;this.controls.maxPolarAngle=mode==='2d'?0:Math.PI*.46;this.controls.mouseButtons.LEFT=mode==='2d'?T.MOUSE.PAN:T.MOUSE.ROTATE;this.controls.touches.ONE=mode==='2d'?T.TOUCH.PAN:T.TOUCH.ROTATE;this.onResize();this.controls.update();(this.options.managed?this.host:document.body).dataset.perspective=mode;this.$('perspective-2d').setAttribute('aria-pressed',String(mode==='2d'));this.$('perspective-3d').setAttribute('aria-pressed',String(mode==='3d'));if(!this.options.managed){const url=new URL(location.href);url.searchParams.set('perspective',mode);history.replaceState(null,'',url);}this.options.onPerspective?.(mode);void this.refine();}
 private onResize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(w<=0||h<=0)return;this.renderer.setSize(w,h);if(this.camera instanceof T.PerspectiveCamera)this.camera.aspect=w/h;else{const half=this.orthoHeight/2;this.camera.left=-half*w/h;this.camera.right=half*w/h;this.camera.top=half;this.camera.bottom=-half;}this.camera.updateProjectionMatrix();}
 private animate(){if(!this.alive||!this.visible)return;this.frame=requestAnimationFrame(this.animate);this.controls.update();this.renderer.render(this.scene,this.camera);for(const label of this.labels){const p=label.point.clone().project(this.camera);label.el.hidden=Math.abs(p.x)>1||Math.abs(p.y)>1||Math.abs(p.z)>1;label.el.style.left=(p.x*.5+.5)*this.host.clientWidth+'px';label.el.style.top=(-p.y*.5+.5)*this.host.clientHeight+'px';}
  const display=habitatDisplay(this.habitatSpan());for(const item of this.habitat.children){const material=(item as T.Mesh).material as T.Material&{opacity:number};material.opacity=item.userData.habitatFill?display.fillOpacity:display.outlineOpacity;}this.host.dataset.habitatView=display.mode;const habitatNote=this.$('habitat-view-note');const message=display.mode==='areas'?'Habitat areas · zoom in for individual reefs':'Individual reefs · select a pin for evidence';if(habitatNote&&habitatNote.textContent!==message)habitatNote.textContent=message;
  const occupied:{x:number;y:number}[]=[];for(const pin of this.pins){const p=pin.point.clone().project(this.camera),x=(p.x*.5+.5)*this.host.clientWidth,y=(-p.y*.5+.5)*this.host.clientHeight;const hidden=!this.habitat.visible||(!habitatDisplay(this.habitatSpan()).pins&&pin.id!==this.selectedTarget)||Math.abs(p.z)>1||x<40||x>this.host.clientWidth-50||y<40||y>this.host.clientHeight-95||occupied.some(o=>Math.abs(o.x-x)<28&&Math.abs(o.y-y)<28);pin.el.hidden=hidden;pin.el.classList.toggle('selected',pin.id===this.selectedTarget);if(!hidden){occupied.push({x,y});pin.el.style.left=x+'px';pin.el.style.top=y+'px';}}
 };
 private showReading(x:number,z:number,sample:Reading){const generation=++this.readingGeneration;const s=this.manifest.sources.find(s=>s.id===sample.source)!,[lon,lat]=coastLonLat(sample.sampleX??x,sample.sampleZ??z);this.$('reading').hidden=false;this.$('reading-kind').textContent=s.kind==='model'?'REGIONAL MODEL':s.kind==='estimate'?'CHART ESTIMATE':s.kind==='lidar'?'MEASURED LIDAR · NAVD88':s.kind==='land'?'LAND ELEVATION CONTEXT':'ORIGINAL SURVEY SAMPLE';this.$('depth-value').textContent=sample.source===7?`${sample.height.toFixed(1)} m elevation`:`${Math.abs(sample.height*3.28084).toFixed(0)} ft ${sample.height>0?'elevation':'depth'}`;this.$('depth-location').textContent=`${lat.toFixed(5)}° N · ${Math.abs(lon).toFixed(5)}° W`;this.$('depth-spacing').textContent=`${s.label} · ${s.sourceDate} · ${sample.spacing} m display spacing. ${s.datum}. Original spacing ${s.resolutionM??'varies'} m. ${sample.source===7?'Water is illustrative; this is not an observed water depth.':'Vertical references have not been reconciled.'}`;if(sample.source===3)void this.showChartEvidence(sample.sampleX??x,sample.sampleZ??z,sample.height,generation);}
 private async showChartEvidence(x:number,z:number,height:number,generation:number){try{this.chartManifest??=json('/data/coast3d/chart-model.json');const chart=await this.chartManifest;if(chart.kind!=='chart-derived-estimate')return;const candidates=chart.tiles.filter((t:any)=>x>=t.x&&x<=t.x+t.width&&z>=t.z&&z<=t.z+t.width).reverse();for(const tile of candidates){const a=tile.lods.at(-1);if(!a.rangeAsset||!a.kindAsset)continue;let pending=this.chartEvidenceCache.get(a.url);if(!pending){pending=Promise.all([verifiedAsset(a.rangeAsset),verifiedAsset(a.kindAsset),verifiedAsset(a)]).then(([r,k,v])=>({ranges:new Float32Array(r),kinds:new Uint8Array(k),values:new Float32Array(v)}));this.chartEvidenceCache.set(a.url,pending);}const {ranges,kinds,values}=await pending;const index=roundEven((z-tile.z)/a.spacing)*a.size+roundEven((x-tile.x)/a.spacing);if(!this.alive||generation!==this.readingGeneration)return;if(!Number.isFinite(values[index])||Math.abs(values[index]+height)>.0001||!Number.isFinite(ranges[index*2])||!Number.isFinite(ranges[index*2+1]))continue;this.$('depth-spacing').textContent+=` Original chart band ${Math.round(ranges[index*2]*3.28084)}–${Math.round(ranges[index*2+1]*3.28084)} ft · ${kinds[index]===1?'bounded sounding interpolation':'range-only midpoint'}. This band is not a confidence interval.`;return;}}catch{/* The estimate retains its explicit source label if original band evidence is unavailable. */}}
 private bind(){const params=new URLSearchParams(this.options.managed?'':location.search),select=this.$<HTMLSelectElement>('species');if(!this.options.managed&&!params.has('target'))select.value=params.get('profile')==='shore'?'surfperch':params.get('profile')==='spear'?'cabezon-shallow-reef':'lingcod';if(params.get('profile')==='spear'){this.depthLimit=60;this.$<HTMLInputElement>('depth-limit').value='60';this.$('depth-limit-label').textContent='60 ft';}if([...select.options].some(s=>s.value===params.get('target')))select.value=params.get('target')!;
  this.$('sources-open').onclick=()=>this.$<HTMLDialogElement>('sources').showModal();this.$('sources-close').onclick=()=>this.$<HTMLDialogElement>('sources').close();this.$('layers-toggle').onclick=()=>{const expanded=this.root.querySelector('.layers')!.classList.toggle('expanded');this.$('layers-toggle').setAttribute('aria-expanded',String(expanded));};
  this.$('reset').onclick=()=>{this.goPlace(this.$('reset').dataset.homePlace??'morro');this.notifyView();void this.refine();this.drawPins();void this.refreshCurrents();};this.$('location').onchange=()=>{this.goPlace(this.$<HTMLSelectElement>('location').value);if(!this.options.managed){const url=new URL(location.href);url.searchParams.set('place',this.$<HTMLSelectElement>('location').value);history.replaceState(null,'',url);}void this.refine();this.drawPins();void this.refreshCurrents();};
  this.$('perspective-2d').onclick=()=>this.setPerspective('2d');this.$('perspective-3d').onclick=()=>this.setPerspective('3d');this.$('top').onclick=()=>this.setPerspective('2d');
  const zoom=(factor:number)=>{if(this.camera instanceof T.OrthographicCamera){this.camera.zoom=Math.max(.05,Math.min(100,this.camera.zoom/factor));this.camera.updateProjectionMatrix();}else{const delta=this.camera.position.clone().sub(this.controls.target);delta.multiplyScalar(factor);if(delta.length()>=160&&delta.length()<=400000)this.camera.position.copy(this.controls.target).add(delta);}this.controls.update();this.notifyView();void this.refine();this.drawPins();};this.$('zoom-in').onclick=()=>zoom(.7);this.$('zoom-out').onclick=()=>zoom(1.4);
  this.$('contours').onchange=()=>{this.contours.value=this.$<HTMLInputElement>('contours').checked?1:0;};this.$('source-coverage').onchange=()=>{this.sourceColors.value=this.$<HTMLInputElement>('source-coverage').checked?1:0;};this.$('water').onchange=()=>{this.waters.visible=this.$<HTMLInputElement>('water').checked;};this.$('water-opacity').oninput=()=>{this.waterOpacity.value=Number(this.$<HTMLInputElement>('water-opacity').value);};this.$('habitat').onchange=()=>{this.habitat.visible=this.$<HTMLInputElement>('habitat').checked;};this.$('currents').onchange=()=>{this.currents.visible=this.$<HTMLInputElement>('currents').checked;if(this.currents.visible)void this.refreshCurrents();};
  this.$('depth-limit').oninput=()=>{this.depthLimit=Number(this.$<HTMLInputElement>('depth-limit').value);this.$('depth-limit-label').textContent=this.depthLimit+' ft';this.drawHabitat();};this.$('species').onchange=()=>{this.setSpecies(select.value);if(!this.options.managed){const url=new URL(location.href);url.searchParams.set('target',select.value);history.replaceState(null,'',url);}};this.$('relief').oninput=()=>{this.relief.value=Number(this.$<HTMLInputElement>('relief').value);this.$('relief-label').textContent='×'+this.relief.value;for(const mesh of this.terrain.children as T.Mesh[]){const grid=mesh.userData.grid as Grid;const old=mesh.geometry;const replacement=this.geometry(grid,false);mesh.geometry=replacement;const water=this.waters.children.find(w=>(w as T.Mesh).geometry===old) as T.Mesh|undefined;if(water)water.geometry=replacement;old.dispose();}this.drawCoverageSeams();};this.$('next-reef').onclick=()=>{const f=this.features[this.reefIndex++%this.features.length];if(f)this.selectFeature(f,true);};this.$('target-close').onclick=()=>this.selectHabitat(null);
  this.renderer.domElement.addEventListener('pointerdown',e=>{this.down=[e.clientX,e.clientY];});this.renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-this.down[0],e.clientY-this.down[1])>6||!this.manifest)return;const r=this.renderer.domElement.getBoundingClientRect();this.ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),this.camera);const hits=this.ray.intersectObjects(this.terrain.children,false);for(const hit of hits){const object=hit.object as T.Mesh;if((hit.faceIndex??0)>=object.geometry.userData.surfaceTriangleCount)continue;const kind=hit.object.userData.kind;if(kind===0&&[...this.loaded.values()].some(t=>nearestDepth(t.grid,hit.point.x,hit.point.z)!==null))continue;if(kind===1&&[...this.loaded.values()].some(t=>t.child&&nearestDepth(t.grid,hit.point.x,hit.point.z)!==null))continue;const sample=this.readingAt(hit.point.x,hit.point.z);if(sample)this.showReading(hit.point.x,hit.point.z,sample);break;}});
  this.renderer.domElement.addEventListener('keydown',e=>{if(e.key==='+'||e.key==='=')zoom(.8);if(e.key==='-')zoom(1.25);if(e.key==='Home'){e.preventDefault();this.$('reset').click();return;}const delta=this.span()/30,t=this.controls.target;if(e.key==='ArrowLeft'){t.x-=delta;this.camera.position.x-=delta;}if(e.key==='ArrowRight'){t.x+=delta;this.camera.position.x+=delta;}if(e.key==='ArrowUp'){t.z-=delta;this.camera.position.z-=delta;}if(e.key==='ArrowDown'){t.z+=delta;this.camera.position.z+=delta;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','+','-','='].includes(e.key)){e.preventDefault();this.controls.update();this.notifyView();void this.refine();}});
  window.addEventListener('pagehide',()=>this.destroy(),{once:true});const place=params.get('place')??({north:'cambria',south:'avila',central:'morro'}[params.get('area')??''])??'morro';if(!this.options.managed){this.goPlace(place);if(params.get('perspective')==='2d')this.setPerspective('2d');}else this.host.dataset.perspective=this.perspective;
 }
 private restoreHabitatSelection(){if(!this.requestedHabitat||!this.speciesSupported)return;const shore=['halibut','surfperch'].includes(this.option().id),feature=(shore?this.shoreFeatures:this.features).find(f=>String(f.id??f.properties.id)===this.requestedHabitat);if(feature){if(shore)this.selectShoreFeature(feature,false,false);else this.selectFeature(feature,false,false);}}
 /** Restore only exact admitted public habitat identity, without selection callbacks. */
 selectHabitat(id:string|null):void{this.requestedHabitat=id;this.selectedTarget=null;this.$('target-detail').hidden=true;this.restoreHabitatSelection();this.drawPins();}
 /** Host-owned choices never infer source coverage or substitute a species. */
 setPlace(id:string){if(!places.some(p=>p[0]===id))return;this.goPlace(id);void this.refine();this.drawPins();void this.refreshCurrents();}
 setLocation(point:{latitude:number;longitude:number;span?:number}){if(!Number.isFinite(point.latitude)||!Number.isFinite(point.longitude)||Math.abs(point.latitude)>90||Math.abs(point.longitude)>180)return;const [x,z]=coastPoint(point.longitude,point.latitude);this.moveTo(x,z,point.span&&Number.isFinite(point.span)&&point.span>0?point.span:Math.max(160,this.span()));this.readingGeneration++;this.$('reading').hidden=true;void this.refine();this.drawPins();void this.refreshCurrents();}
 setSpecies(id:string):boolean{this.speciesSupported=speciesOptions.some(s=>s.id===id);this.$<HTMLSelectElement>('species').value=this.speciesSupported?id:'';this.reefIndex=0;this.selectedTarget=null;this.$('target-detail').hidden=true;this.drawHabitat();return this.speciesSupported;}
 setHour(at:Date|null){if(at!==null&&!Number.isFinite(at.getTime()))return;this.currentAt=at===null?null:new Date(at.getTime());if(this.manifest)void this.refreshCurrents();}
 setDepthLimit(ft:number){if(!Number.isFinite(ft)||ft<0||ft>300)return;this.depthLimit=ft;this.$<HTMLInputElement>('depth-limit').value=String(ft);this.$('depth-limit-label').textContent=ft+' ft';this.drawHabitat();}
 /** Cached admission is withdrawn before any hidden or resumed frame can render. */
 private withholdOverlays(){this.reviewed=null;this.allFeatures=[];this.features=[];this.context=null;this.shoreFeatures=[];this.selectedTarget=null;this.clear(this.habitat);this.clearPins();this.clear(this.currents);this.$('rank-list').replaceChildren();this.$('target-detail').hidden=true;this.$<HTMLButtonElement>('next-reef').disabled=true;this.$('habitat-status').textContent='Reviewed habitat withheld until source binding and current screening are rechecked.';this.$('current-status').textContent='Current vectors withheld until source time and coverage are rechecked.';}
 setVisible(visible:boolean){if(!this.alive||this.visible===visible)return;this.visible=visible;this.currentGeneration++;this.habitatGeneration++;this.shoreGeneration++;this.withholdOverlays();if(!visible){cancelAnimationFrame(this.frame);clearTimeout(this.lodTimer);this.revision++;return;}this.onResize();this.animate();if(this.manifest){void this.refine();void this.refreshHabitat();void this.loadShore();void this.refreshCurrents();}}

 destroy(){window.removeEventListener('coast-report-clock-change',this.reportClock);this.alive=false;this.revision++;this.habitatGeneration++;this.currentGeneration++;this.shoreGeneration++;cancelAnimationFrame(this.frame);clearInterval(this.refreshTimer);clearTimeout(this.lodTimer);this.resize.disconnect();this.controls.dispose();this.clearPins();this.clear(this.habitat);this.clear(this.currents);this.clear(this.seams);for(const item of this.loaded.values()){item.mesh.geometry.dispose();(item.mesh.material as T.Material).dispose();(item.water.material as T.Material).dispose();}for(const mesh of [...this.terrain.children,...this.waters.children] as T.Mesh[]){mesh.geometry.dispose();(mesh.material as T.Material).dispose();}for(const t of this.textureValues){(t.image as ImageBitmap)?.close?.();t.dispose();}this.coverage?.dispose();this.harborCoverage?.dispose();this.renderer.dispose();}
}
