import test from 'node:test';
import assert from 'node:assert/strict';
import {CoastReport,methodMetrics} from '../../packages/coast/src/coast3d/report.ts';
import {managedReportState,resolveReportBinding,type ManagedReportContext} from '../../packages/coast/src/state/report-context.ts';
import {forecastHour,daily,quietestHours,createState,localWave} from '../../packages/coast/src/state/experience.ts';
import {nearshoreAt,nearshoreSampleLabel,clock} from '../../packages/coast/src/presentation.ts';
import {briefing,conditions} from '../../packages/coast/src/ui/briefing.ts';
import {dateKey} from '../../packages/coast/src/daily.ts';
import {historyView} from '../../packages/coast/src/ui/history.ts';
import {recentCatchTrips} from '../../packages/coast/src/ui/catches.ts';
import {slo} from '../../packages/coast/src/counties.ts';
import type {Report} from '../../packages/coast/src/types.ts';
import type {HistoryBundle} from '../../packages/coast/src/history-types.ts';
const now=new Date(),start=Math.floor(now.getTime()/3600000)*3600000;
function context(patch:Partial<ManagedReportContext>={}):ManagedReportContext{return {regionId:'morro-bay',point:{latitude:35.35,longitude:-120.9},localAreas:[{id:'estero-bay',bounds:[-121.05,35.32,-120.78,35.47]},{id:'avila',bounds:[-120.85,35.05,-120.67,35.21]}],localId:'estero-bay',profile:'boat',target:'lingcod',at:new Date(start),...patch};}
function report():Report{return {schemaVersion:1,countyId:'slo',generatedAt:now.toISOString(),forecasts:[{id:'central',sourceId:'nws-central',hours:Array.from({length:48},(_,i)=>({at:new Date(start+i*3600000).toISOString(),windKnots:5,gustKnots:8,waveFt:2,wavePeriodS:10,airTempF:60,precipPct:0}))}],sources:[{id:'nws-central',label:'NWS',url:'https://api.weather.gov',kind:'forecast',outcome:'ok',fetchedAt:now.toISOString(),issuedAt:now.toISOString()},{id:'nws-alerts',label:'Alerts',url:'https://api.weather.gov',kind:'forecast',outcome:'ok',fetchedAt:now.toISOString()}],observations:[{stationId:slo.temperatureStationId,observedAt:now.toISOString(),url:'https://www.ndbc.noaa.gov',waterTempF:58,windKnots:null,gustKnots:null,waveFt:2,wavePeriodS:10}],tides:[],tideEvents:[],alerts:[],catches:[{id:'trip-1',tripDate:dateKey(now,slo.timezone),boat:'Fixture vessel',landing:'Fixture landing',anglers:10,tripType:'Day',species:[{name:'Lingcod',count:4,disposition:'reported'}],sourceUrl:'https://example.com/trip',retrievedAt:now.toISOString()}],catchContext:{feedUrl:'https://example.com/feed',feedGeneratedAt:now.toISOString(),receivedAt:now.toISOString(),windowStart:dateKey(now,slo.timezone),windowEnd:dateKey(now,slo.timezone),latestTripDate:dateKey(now,slo.timezone),rights:{scope:'linked-factual-counts',reviewedAt:now.toISOString(),sourceCatalogUrl:'https://example.com/rights'}},catchStatus:'Linked facts',visibility:{status:'unknown',feet:null,observedAt:null,sourceUrl:null},habitatStatus:'Pending'};}
function root(){const listeners=new Map<string,EventListener>();return {innerHTML:'',scrollTop:0,listeners,addEventListener(key:string,fn:EventListener){listeners.set(key,fn);},removeEventListener(key:string,fn:EventListener){if(listeners.get(key)===fn)listeners.delete(key);},querySelector(){throw Error('Managed report requested a legacy DOM ID');},querySelectorAll(){return [] as Element[];}};}
async function browser<T>(run:()=>Promise<T>|T):Promise<T>{
 const names=['document','location','history','window'] as const,saved=names.map(name=>Object.getOwnPropertyDescriptor(globalThis,name));
 for(const name of names)Object.defineProperty(globalThis,name,{configurable:true,get(){if(name==='window')return {setInterval(){return 0;},addEventListener(){throw Error('Managed report attached a global listener');},dispatchEvent(){throw Error('Managed report emitted a global event');}};throw Error('Managed report accessed '+name);}});
 try{return await run();}finally{names.forEach((name,i)=>{if(saved[i])Object.defineProperty(globalThis,name,saved[i]!);else delete (globalThis as any)[name];});}
}
function click(target:any){return {target:{closest:()=>target}} as unknown as Event;}
test('local report binding requires the canonical package and original containing local bounds',()=>{
 assert.deepEqual(resolveReportBinding(context()),{areaId:'central',localAreaId:'estero-bay'});
 assert.deepEqual(resolveReportBinding(context({point:{latitude:35.16,longitude:-120.76},localId:'avila'})),{areaId:'south',localAreaId:'avila'});
 assert.deepEqual(resolveReportBinding(context({regionId:'cambria-san-simeon',point:{latitude:35.6,longitude:-121.1},localId:'san-simeon',localAreas:[{id:'san-simeon',bounds:[-121.5,35.49,-120.92,35.75]}]})),{areaId:'north',localAreaId:'san-simeon'});
 for(const patch of [{regionId:'monterey-point-sur'},{regionId:'constructor'},{localId:'avila'},{localId:'missing'},{localId:''},{localAreas:[]},{point:{latitude:36,longitude:-121}},{localAreas:[{id:'estero-bay',bounds:[-200,0,200,90]}]}])assert.equal(resolveReportBinding(context(patch)),null);
});
test('without explicit local identity, overlap uses the smallest reviewed containing area',()=>{
 const c=context({localId:null,localAreas:[{id:'cayucos',bounds:[-121.2,35,-120.6,35.6]},{id:'estero-bay',bounds:[-121,35.3,-120.8,35.4]}]});assert.equal(resolveReportBinding(c)?.localAreaId,'estero-bay');assert.equal(c.localAreas[0].id,'cayucos');
});
test('managed state preserves unsupported target, selected profile and exact day four/seven without forecast fallback',()=>{
 for(const offset of [4,7]){const c=context({at:new Date(start+offset*86400000),profile:'spear',target:'albacore'}),s=managedReportState(report(),c,now)!;assert.equal(s.at,c.at.toISOString());assert.equal(s.date,dateKey(c.at,slo.timezone));assert.equal(s.mode,'spear');assert.equal(s.species,'albacore');assert.equal(forecastHour(s),undefined);assert.equal(daily(s).hours.length,0);assert.equal(quietestHours(s),null);assert.equal(s.report.generatedAt,now.toISOString());assert.equal(s.report.observations[0].observedAt,now.toISOString());}
 assert.equal(managedReportState(report(),context({at:new Date(start+1000)}),now),null);assert.equal(managedReportState({...report(),countyId:'other'},context(),now),null);
});
test('exact forecast hour accepts ISO serialization variants but never fills a missing hour',()=>{
 const data=report(),s=managedReportState(data,context(),now)!;s.at=new Date(start).toISOString().slice(0,16)+'Z';assert.equal(forecastHour(s)?.windKnots,5);data.forecasts[0].hours=data.forecasts[0].hours.filter(h=>Date.parse(h.at)!==start);assert.equal(forecastHour(s),undefined);assert.equal(s.at,new Date(start).toISOString().slice(0,16)+'Z');
 const standalone=createState(report(),slo,'boat','central',undefined,'lingcod',now);assert.ok(forecastHour(standalone));
});
test('future date leaves factual catches and measured history clocks unchanged',()=>{
 const data=report(),a=managedReportState(data,context(),now)!,b=managedReportState(data,context({at:new Date(start+7*86400000)}),now)!;assert.deepEqual(recentCatchTrips(a),recentCatchTrips(b));assert.equal(recentCatchTrips(b)[0].tripDate,dateKey(now,slo.timezone));assert.equal(b.report.catchContext?.feedGeneratedAt,now.toISOString());
});
test('managed mount owns no URL, global listener or extra place/profile/day/hour picker',async()=>browser(async()=>{
 const host=root(),r:any=new CoastReport({root:host as unknown as HTMLElement,managed:true,stylesURL:'/assets/report.css'});await r.refresh();r.snapshot=report();r.setContext(context({at:new Date(start+4*86400000),profile:'shore',target:'surfperch'}));assert.equal(r.state.at,new Date(start+4*86400000).toISOString());assert.equal(r.state.species,'surfperch');assert.equal(r.state.mode,'shore');assert.match(host.innerHTML,/No supported local NWS forecast hour/);assert.doesNotMatch(host.innerHTML,/id="(?:panel-area|report-mode|report-day|coast-hour|hour-slider|location|species)"|type="range"/);r.setTab('local-conditions');assert.match(host.innerHTML,/LOCAL SLO SOURCES/);r.setContext(context({profile:'spear',target:'gopher-rockfish'}));assert.equal(r.state.species,'gopher-rockfish');assert.match(host.innerHTML,/Visibility is unknown/);r.destroy();assert.equal(host.listeners.size,0);
}));
test('nonSLO managed context is unavailable rather than defaulting to Morro or transferring catch relevance',async()=>browser(async()=>{
 const host=root(),r:any=new CoastReport({root:host as unknown as HTMLElement,managed:true});await r.refresh();r.snapshot=report();r.setContext(context({regionId:'monterey-point-sur'}));r.setTab('fleet');assert.equal(r.state,null);assert.match(host.innerHTML,/Local SLO report unavailable/);assert.doesNotMatch(host.innerHTML,/Fixture vessel|Morro Bay|Wind \/ gust/);r.destroy();
}));
test('source refresh preserves the context arriving during the request and never refreshes observation clocks',async()=>browser(async()=>{
 const originalFetch=globalThis.fetch;let resolve!:(response:Response)=>void;let requests=0;globalThis.fetch=((path:string,init:any)=>{assert.equal(path,'/api/coast/report');assert.equal(init.credentials,'omit');requests++;return new Promise(done=>resolve=done);}) as typeof fetch;
 try{const host=root(),r:any=new CoastReport({root:host as unknown as HTMLElement,managed:true,initialContext:context()});const loading=r.refresh();r.setContext(context({at:new Date(start+7*86400000),target:'albacore'}));assert.equal(requests,1);resolve(new Response(JSON.stringify(report()),{headers:{'Content-Type':'application/json'}}));assert.equal(await loading,true);assert.equal(r.state.at,new Date(start+7*86400000).toISOString());assert.equal(r.state.species,'albacore');assert.equal(r.state.report.observations[0].observedAt,now.toISOString());r.destroy();}finally{globalThis.fetch=originalFetch;}
}));
test('hidden or destroyed managed report never publishes a late source response',async()=>browser(async()=>{
 const originalFetch=globalThis.fetch;let resolve!:(response:Response)=>void;globalThis.fetch=(()=>new Promise(done=>resolve=done)) as typeof fetch;
 try{const host=root(),r:any=new CoastReport({root:host as unknown as HTMLElement,managed:true,initialContext:context()});const loading=r.refresh(),before=host.innerHTML;r.setVisible(false);resolve(new Response(JSON.stringify(report())));assert.equal(await loading,false);assert.equal(r.snapshot,null);assert.equal(host.innerHTML,before);r.destroy();}finally{globalThis.fetch=originalFetch;}
}));
test('nonSLO history reference requires explicit opt-in and retains its own geography label',async()=>browser(async()=>{
 const originalFetch=globalThis.fetch;const history:HistoryBundle={schemaVersion:1,countyId:'slo',generatedAt:now.toISOString(),recentWindowDays:45,stations:[]};const paths:string[]=[];globalThis.fetch=(async(path:any)=>{paths.push(path);return new Response(JSON.stringify(history));}) as typeof fetch;
 try{const host=root(),r:any=new CoastReport({root:host as unknown as HTMLElement,managed:true,historyReference:true,initialContext:context({regionId:'monterey-point-sur'})});await r.refresh();r.setTab('history');await r.loadHistory();assert.equal(r.state,null);assert.match(host.innerHTML,/SLO BUOY HISTORY REFERENCE/);assert.match(host.innerHTML,/not conditions for the selected map location \(monterey-point-sur\)/);assert.doesNotMatch(host.innerHTML,/Morro Bay|forecast-hour-summary/);assert.deepEqual(paths,['/api/coast/history']);r.setTab('fleet');assert.match(host.innerHTML,/Local SLO report unavailable/);r.destroy();}finally{globalThis.fetch=originalFetch;}
}));

test('measured SLO history is identical for today and day seven because forecast time is not its clock',()=>{
 const a=managedReportState(report(),context(),now)!,b=managedReportState(report(),context({at:new Date(start+7*86400000)}),now)!;
 const metrics={waterTempF:58,airTempF:60,windKnots:5,gustKnots:8,waveFt:2,periodS:10},counts={waterTempF:1,airTempF:1,windKnots:1,gustKnots:1,waveFt:1,periodS:1};
 const data:HistoryBundle={schemaVersion:1,countyId:'slo',generatedAt:now.toISOString(),recentWindowDays:45,stations:[{stationId:slo.temperatureStationId,name:'Fixture buoy',lat:35.2,lon:-120.85,recent:{from:new Date(start-45*86400000).toISOString(),through:new Date(start).toISOString(),firstObservedAt:new Date(start).toISOString(),lastObservedAt:new Date(start).toISOString(),stale:false,expectedHours:1080,observedHours:1,hourCoverageFraction:1/1080,maxGapHours:1079,hours:[{...metrics,at:new Date(start).toISOString(),sampleCount:1,counts}],qc:{inputRows:1,acceptedRows:1,rejectedRows:0,duplicateRows:0,conflictingValues:0,maskedValues:0,trailingMissingRows:0}},baseline:{kind:'unavailable',label:'Unavailable',years:[],periodStart:null,periodEnd:null,aggregation:'UTC-hour means, weighted equally',months:[]},archive:{indexUrl:'https://example.com/index',availableYears:[],discoveredAt:now.toISOString(),outcome:'ok'},sources:[{url:'https://example.com/recent',role:'recent',outcome:'ok',fetchedAt:now.toISOString()}],limitations:[]}]};
 const selection={station:slo.temperatureStationId,metric:'waterTempF' as const,days:14};const before=JSON.stringify(data),first=historyView(a,data,selection),later=historyView(b,data,selection);assert.equal(later,first);assert.match(later,/Latest source report/);assert.match(later,/58.0/);assert.equal(JSON.stringify(data),before);
});
test('wrong-county and failed refresh cannot replace retained source clocks or canonical context',async()=>browser(async()=>{
 const originalFetch=globalThis.fetch;globalThis.fetch=(async()=>new Response(JSON.stringify({...report(),countyId:'other'}))) as typeof fetch;
 try{const host=root(),r:any=new CoastReport({root:host as unknown as HTMLElement,managed:true});await r.refresh();r.snapshot=report();r.setContext(context({at:new Date(start+7*86400000),profile:'spear',target:'gopher-rockfish'}));assert.equal(await r.refresh(),false);assert.equal(r.snapshot.countyId,'slo');assert.equal(r.state.at,new Date(start+7*86400000).toISOString());assert.equal(r.state.report.sources[0].fetchedAt,now.toISOString());assert.match(host.innerHTML,/Source refresh unavailable/);r.destroy();}finally{globalThis.fetch=originalFetch;}
}));

test('managed context is copied so caller mutation cannot change its geography or selected hour',async()=>browser(async()=>{
 const host=root(),r:any=new CoastReport({root:host as unknown as HTMLElement,managed:true});await r.refresh();r.snapshot=report();const c=context();r.setContext(c);c.at.setUTCDate(c.at.getUTCDate()+7);c.point.latitude=36;(c.localAreas[0].bounds as number[])[0]=0;r.setTab('sources');assert.equal(r.state.at,new Date(start).toISOString());assert.equal(r.state.areaId,'central');assert.equal(r.context.point.latitude,35.35);assert.equal(r.context.localAreas[0].bounds[0],-121.05);r.destroy();
}));

test('nearshore sampling never extends before first or after last valid model frame',()=>{
 const site={id:'fixture-cdip',name:'Fixture CDIP point',areaId:'central',lat:35.35,lon:-120.9,sourceId:'cdip',issuedAt:now.toISOString(),fetchedAt:now.toISOString(),hours:[{at:new Date(start+3*3600000).toISOString(),waveFt:1.2,periodS:11,directionDeg:300,qualityFlag:null,secondaryFlag:null},{at:new Date(start+6*3600000).toISOString(),waveFt:1.4,periodS:12,directionDeg:300,qualityFlag:null,secondaryFlag:null}],url:'https://example.com/cdip',kind:'forecast' as const,availability:'available' as const,freshness:'current' as const,temporalResolutionMinutes:180,waterDepthM:null,depthDatum:'nominal',directionConvention:'from degrees true' as const,modelInputCycleAt:null,validThrough:new Date(start+6*3600000).toISOString()};
 assert.equal(nearshoreAt(site,new Date(start+2*3600000).toISOString()),undefined);assert.equal(nearshoreAt(site,new Date(start+7*3600000).toISOString()),undefined);assert.equal(nearshoreAt(site,new Date(start+3*3600000).toISOString()),site.hours[0]);assert.equal(nearshoreAt(site,new Date(start+6*3600000).toISOString()),site.hours[1]);
 const sample=nearshoreAt(site,new Date(start+4*3600000).toISOString());assert.equal(sample,site.hours[0]);assert.equal(sample?.at,site.hours[0].at);assert.equal(nearshoreAt({...site,validThrough:new Date(start+4*3600000).toISOString()},new Date(start+5*3600000).toISOString()),undefined);assert.equal(nearshoreAt({...site,hours:[]},now.toISOString()),undefined);
 const data=report();data.nearshore=[site];const supported=managedReportState(data,context({profile:'shore',at:new Date(start+4*3600000)}),now)!;
 const label=nearshoreSampleLabel(site,sample,slo.timezone);assert.match(label,/3h model sampling/);assert.ok(label.includes(clock(site.hours[0].at,slo.timezone,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'})));
 for(const html of [methodMetrics(supported),briefing(supported),conditions(supported)])assert.ok(html.includes(label),'Every selected model sample shows its original clock and sampling');
 const after=managedReportState(data,context({profile:'shore',at:new Date(start+7*3600000)}),now)!;assert.equal(localWave(after)?.hour,undefined);assert.match(methodMetrics(after),/no model sample covers the selected time/);assert.equal(site.hours[0].at,new Date(start+3*3600000).toISOString());
});
test('failed history load exposes a source gap and retries only when explicitly requested',async()=>browser(async()=>{
 const originalFetch=globalThis.fetch;let requests=0;globalThis.fetch=(async()=>{requests++;return requests===1?new Response('',{status:503}):new Response(JSON.stringify({schemaVersion:1,countyId:'slo',generatedAt:now.toISOString(),recentWindowDays:45,stations:[]}));}) as typeof fetch;
 try{const host=root(),r:any=new CoastReport({root:host as unknown as HTMLElement,managed:true,historyReference:true,initialContext:context({regionId:'monterey-point-sur'})});await r.refresh();r.tab=3;await r.loadHistory();assert.equal(r.historyLoading,false);assert.equal(r.historyFailed,true);assert.equal(requests,1);assert.match(host.innerHTML,/Measured history source unavailable/);assert.match(host.innerHTML,/data-history-retry/);r.renderPanel();assert.equal(requests,1);await r.loadHistory(true);assert.equal(requests,2);assert.equal(r.historyFailed,false);assert.equal(r.historyLoading,false);assert.equal(r.history.countyId,'slo');assert.doesNotMatch(host.innerHTML,/Measured history source unavailable|Loading measured history/);r.destroy();}finally{globalThis.fetch=originalFetch;}
}));
test('saved report labels preserve original clocks and live refresh clears the saved marker',async()=>browser(async()=>{
 const originalFetch=globalThis.fetch,data=report(),saved='2026-01-02T00:00:00.000Z';let offline=true;
 globalThis.fetch=(async()=>Response.json(data,{headers:offline?{'X-SC-Offline':saved}:{}})) as typeof fetch;
 try{const host=root(),r:any=new CoastReport({root:host as unknown as HTMLElement,managed:true,initialContext:context()});await r.refresh();assert.match(host.innerHTML,/Saved offline copy/);assert.ok(host.innerHTML.includes(saved));assert.equal(r.snapshot.generatedAt,data.generatedAt);assert.equal(r.snapshot.sources[0].fetchedAt,data.sources[0].fetchedAt);assert.equal(r.snapshot.observations[0].observedAt,data.observations[0].observedAt);offline=false;await r.refresh();assert.doesNotMatch(host.innerHTML,/Saved offline copy/);r.destroy();}finally{globalThis.fetch=originalFetch;}
}));
test('saved history retains SLO reference context and original measurements',async()=>browser(async()=>{
 const originalFetch=globalThis.fetch,data={schemaVersion:1,countyId:'slo',generatedAt:now.toISOString(),recentWindowDays:45,stations:[]},saved='2026-01-02T00:00:00.000Z';globalThis.fetch=(async()=>Response.json(data,{headers:{'X-SC-Offline':saved}})) as typeof fetch;
 try{const host=root(),r:any=new CoastReport({root:host as unknown as HTMLElement,managed:true,historyReference:true,initialContext:context({regionId:'monterey-point-sur'})});r.tab=3;await r.loadHistory();assert.match(host.innerHTML,/Saved offline copy/);assert.match(host.innerHTML,/reference/);assert.equal(r.history.generatedAt,data.generatedAt);assert.equal(r.history.recentWindowDays,45);r.destroy();}finally{globalThis.fetch=originalFetch;}
}));
